import { GREQuestion, DifficultyTier } from '@/types/gre-test';

// ── SECTION 1 POOL: 12 Medium Questions ─────────────────────────────────────

const section1Pool: GREQuestion[] = [
  {
    id: 's1-m-01',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'If 3x + 7 = 22, what is the value of x?',
    options: [
      { id: 'a', text: '3' },
      { id: 'b', text: '5' },
      { id: 'c', text: '7' },
      { id: 'd', text: '10' },
    ],
    correctAnswer: 'b',
    explanation: '3x + 7 = 22 → 3x = 15 → x = 5.',
    topics: ['algebra'],
  },
  {
    id: 's1-m-02',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'A rectangle has a length of 12 and a width of 5. What is the perimeter?',
    correctAnswer: '34',
    explanation: 'Perimeter = 2(12 + 5) = 2(17) = 34.',
    topics: ['geometry'],
  },
  {
    id: 's1-m-03',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: '√144',
    quantityB: '11',
    quantityInfo: '',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'a',
    explanation: '√144 = 12, which is greater than 11.',
    topics: ['arithmetic'],
  },
  {
    id: 's1-m-04',
    type: 'multi-select',
    difficulty: 'medium',
    prompt: 'Which of the following are factors of 36? Select ALL that apply.',
    options: [
      { id: 'a', text: '4' },
      { id: 'b', text: '6' },
      { id: 'c', text: '8' },
      { id: 'd', text: '9' },
      { id: 'e', text: '12' },
    ],
    correctAnswer: ['a', 'b', 'd', 'e'],
    explanation: '36 = 4×9 = 6×6 = 12×3. 8 does not divide 36 evenly.',
    topics: ['number-theory'],
  },
  {
    id: 's1-m-05',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'If the average of 5 numbers is 20, and four of the numbers are 15, 18, 22, and 25, what is the fifth number?',
    options: [
      { id: 'a', text: '18' },
      { id: 'b', text: '20' },
      { id: 'c', text: '22' },
      { id: 'd', text: '15' },
    ],
    correctAnswer: 'b',
    explanation: 'Sum = 5 × 20 = 100. Sum of four = 15 + 18 + 22 + 25 = 80. Fifth = 100 − 80 = 20.',
    topics: ['statistics'],
  },
  {
    id: 's1-m-06',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'If a shirt originally costs $80 and is on sale for 25% off, what is the sale price in dollars?',
    correctAnswer: '60',
    explanation: '25% of 80 = 20. Sale price = 80 − 20 = 60.',
    topics: ['arithmetic', 'percent'],
  },
  {
    id: 's1-m-07',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: '(−3)²',
    quantityB: '−(3²)',
    quantityInfo: '',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'a',
    explanation: '(−3)² = 9. −(3²) = −9. 9 > −9.',
    topics: ['arithmetic'],
  },
  {
    id: 's1-m-08',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'A circle has a radius of 7. What is its area? (Use π ≈ 22/7)',
    options: [
      { id: 'a', text: '154' },
      { id: 'b', text: '44' },
      { id: 'c', text: '49' },
      { id: 'd', text: '308' },
    ],
    correctAnswer: 'a',
    explanation: 'Area = πr² = (22/7)(49) = 154.',
    topics: ['geometry'],
  },
  {
    id: 's1-m-09',
    type: 'multi-select',
    difficulty: 'medium',
    prompt: 'Which of the following inequalities are true? Select ALL that apply.',
    options: [
      { id: 'a', text: '−5 < −3' },
      { id: 'b', text: '|−7| > 6' },
      { id: 'c', text: '0.5 > 1/3' },
      { id: 'd', text: '2³ < 3²' },
    ],
    correctAnswer: ['a', 'b', 'c', 'd'],
    explanation: '−5 < −3 ✓; |−7| = 7 > 6 ✓; 0.5 > 0.333 ✓; 8 < 9 ✓. All true.',
    topics: ['arithmetic', 'inequalities'],
  },
  {
    id: 's1-m-10',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'If f(x) = 2x² − 3x + 1, what is f(3)?',
    options: [
      { id: 'a', text: '10' },
      { id: 'b', text: '8' },
      { id: 'c', text: '12' },
      { id: 'd', text: '16' },
    ],
    correctAnswer: 'a',
    explanation: 'f(3) = 2(9) − 3(3) + 1 = 18 − 9 + 1 = 10.',
    topics: ['algebra', 'functions'],
  },
  {
    id: 's1-m-11',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'In a class of 40 students, 60% passed the exam. How many students passed?',
    correctAnswer: '24',
    explanation: '60% of 40 = 0.6 × 40 = 24.',
    topics: ['percent'],
  },
  {
    id: 's1-m-12',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: 'The number of prime numbers between 1 and 20',
    quantityB: '8',
    quantityInfo: '',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'c',
    explanation: 'Primes between 1 and 20: 2, 3, 5, 7, 11, 13, 17, 19 → 8 primes.',
    topics: ['number-theory'],
  },
];

// ── SECTION 2 POOL: EASY (15 questions) ─────────────────────────────────────

const section2EasyPool: GREQuestion[] = [
  {
    id: 's2-e-01',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'What is 15 + 27?',
    options: [
      { id: 'a', text: '32' },
      { id: 'b', text: '42' },
      { id: 'c', text: '52' },
      { id: 'd', text: '37' },
    ],
    correctAnswer: 'b',
    explanation: '15 + 27 = 42.',
    topics: ['arithmetic'],
  },
  {
    id: 's2-e-02',
    type: 'numeric-entry',
    difficulty: 'easy',
    prompt: 'What is 8 × 7?',
    correctAnswer: '56',
    explanation: '8 × 7 = 56.',
    topics: ['arithmetic'],
  },
  {
    id: 's2-e-03',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'Which fraction is equivalent to 0.25?',
    options: [
      { id: 'a', text: '1/3' },
      { id: 'b', text: '1/4' },
      { id: 'c', text: '1/5' },
      { id: 'd', text: '2/5' },
    ],
    correctAnswer: 'b',
    explanation: '0.25 = 25/100 = 1/4.',
    topics: ['fractions'],
  },
  {
    id: 's2-e-04',
    type: 'quantitative-comparison',
    difficulty: 'easy',
    prompt: 'Compare the two quantities.',
    quantityA: '50% of 80',
    quantityB: '40',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'c',
    explanation: '50% of 80 = 40. They are equal.',
    topics: ['percent'],
  },
  {
    id: 's2-e-05',
    type: 'multi-select',
    difficulty: 'easy',
    prompt: 'Which of the following are even numbers? Select ALL that apply.',
    options: [
      { id: 'a', text: '12' },
      { id: 'b', text: '15' },
      { id: 'c', text: '22' },
      { id: 'd', text: '31' },
      { id: 'e', text: '40' },
    ],
    correctAnswer: ['a', 'c', 'e'],
    explanation: '12, 22, and 40 are even. 15 and 31 are odd.',
    topics: ['number-theory'],
  },
  {
    id: 's2-e-06',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'What is the value of x if x − 4 = 10?',
    options: [
      { id: 'a', text: '6' },
      { id: 'b', text: '14' },
      { id: 'c', text: '10' },
      { id: 'd', text: '40' },
    ],
    correctAnswer: 'b',
    explanation: 'x − 4 = 10 → x = 14.',
    topics: ['algebra'],
  },
  {
    id: 's2-e-07',
    type: 'numeric-entry',
    difficulty: 'easy',
    prompt: 'A square has a side length of 9. What is its area?',
    correctAnswer: '81',
    explanation: 'Area = 9² = 81.',
    topics: ['geometry'],
  },
  {
    id: 's2-e-08',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'What is 20% of 150?',
    options: [
      { id: 'a', text: '25' },
      { id: 'b', text: '30' },
      { id: 'c', text: '35' },
      { id: 'd', text: '40' },
    ],
    correctAnswer: 'b',
    explanation: '20% of 150 = 0.2 × 150 = 30.',
    topics: ['percent'],
  },
  {
    id: 's2-e-09',
    type: 'quantitative-comparison',
    difficulty: 'easy',
    prompt: 'Compare the two quantities.',
    quantityA: '3 + 4 × 2',
    quantityB: '(3 + 4) × 2',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'b',
    explanation: 'A = 3 + 8 = 11. B = 7 × 2 = 14. B is greater.',
    topics: ['arithmetic'],
  },
  {
    id: 's2-e-10',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'If a bag contains 3 red balls and 7 blue balls, what is the probability of picking a red ball?',
    options: [
      { id: 'a', text: '3/10' },
      { id: 'b', text: '7/10' },
      { id: 'c', text: '1/3' },
      { id: 'd', text: '3/7' },
    ],
    correctAnswer: 'a',
    explanation: 'P(red) = 3/(3+7) = 3/10.',
    topics: ['probability'],
  },
  {
    id: 's2-e-11',
    type: 'numeric-entry',
    difficulty: 'easy',
    prompt: 'What is the greatest common factor (GCF) of 12 and 18?',
    correctAnswer: '6',
    explanation: 'Factors of 12: 1,2,3,4,6,12. Factors of 18: 1,2,3,6,9,18. GCF = 6.',
    topics: ['number-theory'],
  },
  {
    id: 's2-e-12',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'What is the slope of the line y = 3x + 5?',
    options: [
      { id: 'a', text: '5' },
      { id: 'b', text: '3' },
      { id: 'c', text: '−3' },
      { id: 'd', text: '1/3' },
    ],
    correctAnswer: 'b',
    explanation: 'In y = mx + b, the slope m = 3.',
    topics: ['algebra', 'coordinate-geometry'],
  },
  {
    id: 's2-e-13',
    type: 'multi-select',
    difficulty: 'easy',
    prompt: 'Which of the following equal 1? Select ALL that apply.',
    options: [
      { id: 'a', text: '5⁰' },
      { id: 'b', text: '1¹⁰⁰' },
      { id: 'c', text: '0!' },
      { id: 'd', text: '2⁻¹' },
    ],
    correctAnswer: ['a', 'b', 'c'],
    explanation: '5⁰ = 1, 1¹⁰⁰ = 1, 0! = 1. 2⁻¹ = 0.5 ≠ 1.',
    topics: ['arithmetic', 'exponents'],
  },
  {
    id: 's2-e-14',
    type: 'single-choice',
    difficulty: 'easy',
    prompt: 'A triangle has angles measuring 50° and 60°. What is the third angle?',
    options: [
      { id: 'a', text: '80°' },
      { id: 'b', text: '70°' },
      { id: 'c', text: '90°' },
      { id: 'd', text: '60°' },
    ],
    correctAnswer: 'b',
    explanation: '180 − 50 − 60 = 70°.',
    topics: ['geometry'],
  },
  {
    id: 's2-e-15',
    type: 'numeric-entry',
    difficulty: 'easy',
    prompt: 'If 2x = 18, what is x?',
    correctAnswer: '9',
    explanation: '2x = 18 → x = 9.',
    topics: ['algebra'],
  },
];

// ── SECTION 2 POOL: MEDIUM (15 questions) ───────────────────────────────────

const section2MediumPool: GREQuestion[] = [
  {
    id: 's2-m-01',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'If the ratio of boys to girls in a class is 3:5, and there are 40 students total, how many boys are there?',
    options: [
      { id: 'a', text: '12' },
      { id: 'b', text: '15' },
      { id: 'c', text: '20' },
      { id: 'd', text: '25' },
    ],
    correctAnswer: 'b',
    explanation: 'Boys = (3/8) × 40 = 15.',
    topics: ['ratios'],
  },
  {
    id: 's2-m-02',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'A car travels 180 miles in 3 hours. What is the average speed in miles per hour?',
    correctAnswer: '60',
    explanation: 'Speed = 180/3 = 60 mph.',
    topics: ['word-problems'],
  },
  {
    id: 's2-m-03',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: 'The area of a circle with radius 5',
    quantityB: 'The area of a square with side 9',
    quantityInfo: 'Use π ≈ 3.14',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'b',
    explanation: 'Circle area = π(25) ≈ 78.5. Square area = 81. B is greater.',
    topics: ['geometry'],
  },
  {
    id: 's2-m-04',
    type: 'multi-select',
    difficulty: 'medium',
    prompt: 'Which of the following are solutions to x² − 5x + 6 = 0? Select ALL that apply.',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '3' },
      { id: 'd', text: '6' },
    ],
    correctAnswer: ['b', 'c'],
    explanation: 'x² − 5x + 6 = (x − 2)(x − 3) = 0. Solutions: x = 2 and x = 3.',
    topics: ['algebra', 'quadratics'],
  },
  {
    id: 's2-m-05',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'A store marks up the cost of an item by 40%, then offers a 25% discount. If the original cost is $100, what is the final selling price?',
    options: [
      { id: 'a', text: '$100' },
      { id: 'b', text: '$105' },
      { id: 'c', text: '$110' },
      { id: 'd', text: '$115' },
    ],
    correctAnswer: 'b',
    explanation: 'Marked up: $140. After 25% off: 140 × 0.75 = $105.',
    topics: ['percent', 'word-problems'],
  },
  {
    id: 's2-m-06',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'If the sum of the interior angles of a polygon is 720°, how many sides does it have?',
    correctAnswer: '6',
    explanation: '(n − 2) × 180 = 720 → n − 2 = 4 → n = 6.',
    topics: ['geometry'],
  },
  {
    id: 's2-m-07',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'Set A = {1, 2, 3, 4, 5} and Set B = {3, 4, 5, 6, 7}. How many elements are in A ∪ B?',
    options: [
      { id: 'a', text: '5' },
      { id: 'b', text: '7' },
      { id: 'c', text: '3' },
      { id: 'd', text: '10' },
    ],
    correctAnswer: 'b',
    explanation: 'A ∪ B = {1,2,3,4,5,6,7} → 7 elements.',
    topics: ['sets'],
  },
  {
    id: 's2-m-08',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: '2⁸',
    quantityB: '8²',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'a',
    explanation: '2⁸ = 256. 8² = 64. A is greater.',
    topics: ['exponents'],
  },
  {
    id: 's2-m-09',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?',
    options: [
      { id: 'a', text: '7' },
      { id: 'b', text: '10' },
      { id: 'c', text: '12' },
      { id: 'd', text: '14' },
    ],
    correctAnswer: 'b',
    explanation: 'c = √(36 + 64) = √100 = 10.',
    topics: ['geometry', 'pythagorean-theorem'],
  },
  {
    id: 's2-m-10',
    type: 'multi-select',
    difficulty: 'medium',
    prompt: 'Which of the following are true about the number 0? Select ALL that apply.',
    options: [
      { id: 'a', text: 'It is an integer' },
      { id: 'b', text: 'It is a natural number' },
      { id: 'c', text: 'It is a rational number' },
      { id: 'd', text: 'It is neither positive nor negative' },
    ],
    correctAnswer: ['a', 'c', 'd'],
    explanation: '0 is an integer, rational, and neither positive nor negative. Convention varies for natural numbers; the GRE considers natural numbers as starting from 1.',
    topics: ['number-theory'],
  },
  {
    id: 's2-m-11',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'How many distinct ways can 5 people be arranged in a line?',
    correctAnswer: '120',
    explanation: '5! = 5 × 4 × 3 × 2 × 1 = 120.',
    topics: ['combinatorics'],
  },
  {
    id: 's2-m-12',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'If the median of the set {3, 7, x, 12, 15} (arranged in order) is 9, what is x?',
    options: [
      { id: 'a', text: '8' },
      { id: 'b', text: '9' },
      { id: 'c', text: '10' },
      { id: 'd', text: '11' },
    ],
    correctAnswer: 'b',
    explanation: 'The median of 5 ordered numbers is the 3rd one. So x = 9.',
    topics: ['statistics'],
  },
  {
    id: 's2-m-13',
    type: 'quantitative-comparison',
    difficulty: 'medium',
    prompt: 'Compare the two quantities.',
    quantityA: 'The standard deviation of {5, 5, 5, 5}',
    quantityB: 'The standard deviation of {1, 5, 5, 9}',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'b',
    explanation: 'SD of {5,5,5,5} = 0 (no spread). SD of {1,5,5,9} > 0. B is greater.',
    topics: ['statistics'],
  },
  {
    id: 's2-m-14',
    type: 'single-choice',
    difficulty: 'medium',
    prompt: 'A cylindrical tank has a radius of 3 and height of 10. What is its volume? (Use π ≈ 3.14)',
    options: [
      { id: 'a', text: '94.2' },
      { id: 'b', text: '188.4' },
      { id: 'c', text: '282.6' },
      { id: 'd', text: '314' },
    ],
    correctAnswer: 'c',
    explanation: 'V = πr²h = 3.14 × 9 × 10 = 282.6.',
    topics: ['geometry', 'volume'],
  },
  {
    id: 's2-m-15',
    type: 'numeric-entry',
    difficulty: 'medium',
    prompt: 'If 3ⁿ = 81, what is n?',
    correctAnswer: '4',
    explanation: '3⁴ = 81, so n = 4.',
    topics: ['exponents'],
  },
];

// ── SECTION 2 POOL: HARD (15 questions) ─────────────────────────────────────

const section2HardPool: GREQuestion[] = [
  {
    id: 's2-h-01',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'If x² + y² = 25 and xy = 12, what is (x + y)²?',
    options: [
      { id: 'a', text: '37' },
      { id: 'b', text: '49' },
      { id: 'c', text: '61' },
      { id: 'd', text: '169' },
    ],
    correctAnswer: 'b',
    explanation: '(x + y)² = x² + 2xy + y² = 25 + 2(12) = 49.',
    topics: ['algebra'],
  },
  {
    id: 's2-h-02',
    type: 'numeric-entry',
    difficulty: 'hard',
    prompt: 'A committee of 3 is to be formed from 7 people. How many different committees are possible?',
    correctAnswer: '35',
    explanation: 'C(7,3) = 7!/(3!4!) = 35.',
    topics: ['combinatorics'],
  },
  {
    id: 's2-h-03',
    type: 'quantitative-comparison',
    difficulty: 'hard',
    prompt: 'Compare the two quantities.',
    quantityA: 'The number of distinct prime factors of 210',
    quantityB: '4',
    quantityInfo: '',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'c',
    explanation: '210 = 2 × 3 × 5 × 7. That is 4 distinct prime factors.',
    topics: ['number-theory'],
  },
  {
    id: 's2-h-04',
    type: 'multi-select',
    difficulty: 'hard',
    prompt: 'If |2x − 3| ≤ 5, which of the following are possible values of x? Select ALL that apply.',
    options: [
      { id: 'a', text: '−1' },
      { id: 'b', text: '0' },
      { id: 'c', text: '4' },
      { id: 'd', text: '5' },
      { id: 'e', text: '−2' },
    ],
    correctAnswer: ['a', 'b', 'c'],
    explanation: '|2x − 3| ≤ 5 → −5 ≤ 2x − 3 ≤ 5 → −2 ≤ 2x ≤ 8 → −1 ≤ x ≤ 4. So −1, 0, and 4 qualify.',
    topics: ['algebra', 'absolute-value'],
  },
  {
    id: 's2-h-05',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'In how many ways can the letters of the word "LEVEL" be arranged?',
    options: [
      { id: 'a', text: '30' },
      { id: 'b', text: '60' },
      { id: 'c', text: '120' },
      { id: 'd', text: '20' },
    ],
    correctAnswer: 'a',
    explanation: '5!/(2!×2!) = 120/4 = 30. (Two L\'s and two E\'s repeat.)',
    topics: ['combinatorics'],
  },
  {
    id: 's2-h-06',
    type: 'numeric-entry',
    difficulty: 'hard',
    prompt: 'If log₂(x) = 5, what is x?',
    correctAnswer: '32',
    explanation: 'log₂(x) = 5 → x = 2⁵ = 32.',
    topics: ['exponents', 'logarithms'],
  },
  {
    id: 's2-h-07',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'Two trains leave the same station at the same time, traveling in opposite directions. One travels at 60 mph and the other at 80 mph. After how many hours will they be 420 miles apart?',
    options: [
      { id: 'a', text: '2' },
      { id: 'b', text: '3' },
      { id: 'c', text: '4' },
      { id: 'd', text: '2.5' },
    ],
    correctAnswer: 'b',
    explanation: 'Combined speed = 140 mph. Time = 420/140 = 3 hours.',
    topics: ['word-problems'],
  },
  {
    id: 's2-h-08',
    type: 'quantitative-comparison',
    difficulty: 'hard',
    prompt: 'Compare the two quantities.',
    quantityA: '(1/2)⁻³',
    quantityB: '(−2)³',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'a',
    explanation: '(1/2)⁻³ = 2³ = 8. (−2)³ = −8. A > B.',
    topics: ['exponents'],
  },
  {
    id: 's2-h-09',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'A circle is inscribed in a square with side length 10. What is the area of the shaded region between the circle and the square? (Use π ≈ 3.14)',
    options: [
      { id: 'a', text: '21.5' },
      { id: 'b', text: '25.0' },
      { id: 'c', text: '18.6' },
      { id: 'd', text: '28.5' },
    ],
    correctAnswer: 'a',
    explanation: 'Square area = 100. Circle area = π(5²) = 78.5. Shaded = 100 − 78.5 = 21.5.',
    topics: ['geometry'],
  },
  {
    id: 's2-h-10',
    type: 'multi-select',
    difficulty: 'hard',
    prompt: 'For the function f(x) = x³ − 6x² + 11x − 6, which of the following are roots? Select ALL that apply.',
    options: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '3' },
      { id: 'd', text: '−1' },
      { id: 'e', text: '6' },
    ],
    correctAnswer: ['a', 'b', 'c'],
    explanation: 'f(x) = (x−1)(x−2)(x−3). Roots are 1, 2, 3.',
    topics: ['algebra', 'polynomials'],
  },
  {
    id: 's2-h-11',
    type: 'numeric-entry',
    difficulty: 'hard',
    prompt: 'What is the sum of the first 20 positive integers?',
    correctAnswer: '210',
    explanation: 'Sum = n(n+1)/2 = 20(21)/2 = 210.',
    topics: ['arithmetic', 'series'],
  },
  {
    id: 's2-h-12',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'A fair coin is flipped 3 times. What is the probability of getting at least 2 heads?',
    options: [
      { id: 'a', text: '1/2' },
      { id: 'b', text: '3/8' },
      { id: 'c', text: '1/4' },
      { id: 'd', text: '1/8' },
    ],
    correctAnswer: 'a',
    explanation: 'P(exactly 2H) = C(3,2)/8 = 3/8. P(3H) = 1/8. P(≥2H) = 4/8 = 1/2.',
    topics: ['probability'],
  },
  {
    id: 's2-h-13',
    type: 'quantitative-comparison',
    difficulty: 'hard',
    prompt: 'Compare the two quantities.',
    quantityA: 'The remainder when 2⁴⁰ is divided by 3',
    quantityB: '1',
    quantityInfo: '',
    options: [
      { id: 'a', text: 'Quantity A is greater.' },
      { id: 'b', text: 'Quantity B is greater.' },
      { id: 'c', text: 'The two quantities are equal.' },
      { id: 'd', text: 'The relationship cannot be determined from the information given.' },
    ],
    correctAnswer: 'c',
    explanation: '2^1 mod 3 = 2, 2^2 mod 3 = 1. Pattern repeats every 2. 2^40 is even exponent → remainder 1.',
    topics: ['number-theory', 'modular-arithmetic'],
  },
  {
    id: 's2-h-14',
    type: 'single-choice',
    difficulty: 'hard',
    prompt: 'The vertices of a triangle are at (0, 0), (6, 0), and (3, 4). What is the area of the triangle?',
    options: [
      { id: 'a', text: '10' },
      { id: 'b', text: '12' },
      { id: 'c', text: '15' },
      { id: 'd', text: '24' },
    ],
    correctAnswer: 'b',
    explanation: 'Area = ½|x₁(y₂ − y₃) + x₂(y₃ − y₁) + x₃(y₁ − y₂)| = ½|0 + 24 + 0| = 12.',
    topics: ['coordinate-geometry'],
  },
  {
    id: 's2-h-15',
    type: 'numeric-entry',
    difficulty: 'hard',
    prompt: 'If the sum of two numbers is 20 and their product is 96, what is the positive difference between the two numbers?',
    correctAnswer: '4',
    explanation: 'x + y = 20, xy = 96. (x − y)² = (x + y)² − 4xy = 400 − 384 = 16. |x − y| = 4.',
    topics: ['algebra'],
  },
];

// ── Exports ─────────────────────────────────────────────────────────────────

export const questionPools: Record<string, GREQuestion[]> = {
  section1: section1Pool,
  'section2-easy': section2EasyPool,
  'section2-medium': section2MediumPool,
  'section2-hard': section2HardPool,
};

export function getSection1Questions(): GREQuestion[] {
  return [...section1Pool];
}

export function getSection2Questions(tier: DifficultyTier): GREQuestion[] {
  switch (tier) {
    case 'easy':
      return [...section2EasyPool];
    case 'medium':
      return [...section2MediumPool];
    case 'hard':
      return [...section2HardPool];
  }
}

export function getAllQuestions(): GREQuestion[] {
  return [
    ...section1Pool,
    ...section2EasyPool,
    ...section2MediumPool,
    ...section2HardPool,
  ];
}

export function getQuestionsByDifficulty(difficulty: DifficultyTier | 'mixed', count: number): GREQuestion[] {
  let pool: GREQuestion[];
  if (difficulty === 'mixed') {
    pool = getAllQuestions();
  } else {
    pool = getAllQuestions().filter((q) => q.difficulty === difficulty);
  }
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
