-- Populate lesson sat-quant-learn-sat-lid-006 with theory + practice (interactive content).
-- Topic: Interpreting Linear Models
-- Run after 20250302000000.

DO $$
DECLARE
  lid uuid;
BEGIN
  SELECT l.id INTO lid
  FROM public.courses_lessons l
  JOIN public.courses c ON c.id = l.course_id
  WHERE c.slug = 'sat-quant-learn' AND l.slug = 'sat-quant-learn-sat-lid-006'
  LIMIT 1;

  IF lid IS NULL THEN
    RAISE NOTICE 'No lesson found for sat-quant-learn-sat-lid-006; skipping content seed.';
    RETURN;
  END IF;

  UPDATE public.courses_lessons
  SET
    lesson_type = 'interactive',
    concept_title = 'Interpreting Linear Models',
    concept_content = E'A **linear model** uses the equation y = mx + b to describe real-world relationships. The SAT frequently asks what the **slope** and **y-intercept** mean in context.\n\n**Slope (m) — the rate of change:**\n- Tells you how much the dependent variable changes for every one-unit increase in the independent variable.\n- Example: In C = 15h + 25, the slope 15 means "each additional hour costs $15."\n- A negative slope indicates a decrease (e.g., fuel remaining, height of a melting candle).\n\n**Y-intercept (b) — the starting value:**\n- The value of y when x = 0 (the initial condition).\n- Example: In C = 15h + 25, the y-intercept 25 is the flat fee before any hours are added.\n\n**X-intercept — the zero point:**\n- Found by setting y = 0. It answers "when does the quantity reach zero?"\n- Example: V = 25,000 − 2,500t → set V = 0 → t = 10 years until the car is worthless.\n\n**Key SAT tip:** Always connect the number back to its real-world meaning. "What does 15 represent?" → not just "the slope," but "the cost per additional hour."',
    formula_title = 'Worked Example',
    formula_content = E'A moving company charges a flat fee of $150\nplus $0.75 per mile driven.\nTotal = 0.75m + 150\n\nQ: A customer was charged $210. How many\nmiles did they drive?\n\nStep 1 — Set up equation\n  210 = 0.75m + 150\n\nStep 2 — Subtract the flat fee\n  60 = 0.75m\n\nStep 3 — Divide by rate\n  m = 60 / 0.75 = 80\n\nThe customer drove 80 miles.\n\nSlope (0.75) = cost per mile\nY-intercept (150) = flat rental fee'
  WHERE id = lid;

  INSERT INTO public.lesson_interactive_content (lesson_id, intro, steps, quiz)
  VALUES (
    lid,
    'Master the art of interpreting slope, y-intercept, and x-intercept in real-world linear models — one of the most common SAT question types.',
    '[
      {"title": "Identify the slope and its meaning", "content": "The coefficient of the independent variable is the slope. It represents the rate of change — how much the output changes per one-unit increase in the input.", "equation": "C = 15h + 25 → slope = 15 → $15 per hour", "highlight": "slope = rate of change"},
      {"title": "Identify the y-intercept and its meaning", "content": "The constant term is the y-intercept. It represents the starting value, initial fee, or baseline — the value when the independent variable is zero.", "equation": "C(0) = 15(0) + 25 = 25 → flat fee", "highlight": "y-intercept = starting value"},
      {"title": "Find and interpret the x-intercept", "content": "Set y = 0 and solve. The x-intercept tells you when the quantity reaches zero (e.g., when the tank is empty, the car is worthless, or the candle burns out).", "equation": "V = 25000 − 2500t → 0 = 25000 − 2500t → t = 10", "highlight": "set y = 0 to find when output is zero"},
      {"title": "Handle negative slopes", "content": "A negative slope means the dependent variable is decreasing. The absolute value of the slope tells you the rate of loss (e.g., 2.5 pounds per hour of melting).", "equation": "w = 150 − 2.5t → loses 2.5 lbs/hr", "highlight": "negative slope = decreasing"},
      {"title": "Connect the number to context", "content": "SAT answer choices test whether you know the difference between slope and intercept meanings. Always ask: Does this number multiply the variable (slope/rate), or stand alone (intercept/starting value)?", "highlight": "rate vs. starting value"}
    ]'::jsonb,
    '[
      {"question": "The total cost C, in dollars, to rent a surfboard for h hours is given by C(h) = 15h + 25. What is the best interpretation of the value 25?", "options": ["The cost to rent the surfboard for each additional hour", "The total number of hours the surfboard was rented", "The minimum cost to rent the surfboard regardless of the duration", "The maximum cost a customer would pay for a rental"], "answer": 2, "explanation": "At h = 0, C = 25. This is the flat fee charged before any hours are used — the minimum cost regardless of duration.", "difficulty": "Medium"},
      {"question": "The height of a tree, H, in inches, is modeled by H = 4.5y + 36, where y is years since planting. How many inches does the tree grow each year?", "options": ["3.5", "4.5", "25", "36"], "answer": 1, "explanation": "The slope 4.5 is the coefficient of y, meaning the tree grows 4.5 inches per year.", "difficulty": "Medium"},
      {"question": "n = 1,200 − 40d models the number of laptops remaining in a warehouse after d days of sales. Which is the best interpretation of 40?", "options": ["The initial number of laptops in the warehouse", "The number of days it takes to sell all the laptops", "The number of laptops sold each day", "The total number of laptops sold after d days"], "answer": 2, "explanation": "The slope is −40, meaning 40 laptops are sold (removed) each day.", "difficulty": "Hard"},
      {"question": "A plumber charges a one-time fee of $60 plus an hourly rate of $x. If a 3-hour job costs $225, what is the value of x?", "options": ["45", "55", "65", "75"], "answer": 1, "explanation": "225 = 3x + 60 → 165 = 3x → x = 55.", "difficulty": "Medium"},
      {"question": "V(t) = 25,000 − 2,500t models a car''s value t years after purchase. What is the interpretation of the t-intercept?", "options": ["The purchase price of the car", "The annual decrease in the car''s value", "The number of years until the car has no monetary value", "The value of the car after 10 years"], "answer": 2, "explanation": "Set V = 0: 2,500t = 25,000 → t = 10. The t-intercept represents the time when the car''s value drops to zero.", "difficulty": "Hard"},
      {"question": "A moving company charges $150 flat plus $0.75 per mile. If a customer was charged $210, how many miles did they drive?", "options": ["60", "70", "80", "90"], "answer": 2, "explanation": "210 = 0.75m + 150 → 60 = 0.75m → m = 80 miles.", "difficulty": "Medium"},
      {"question": "P = 14.7 + 0.44d gives total pressure P at depth d feet below the ocean surface. Which is the best interpretation of 14.7?", "options": ["The pressure at the surface of the ocean", "The increase in pressure for every 1 foot of depth", "The depth at which the pressure is zero", "The maximum pressure the ocean can exert"], "answer": 0, "explanation": "At d = 0 (the surface), P = 14.7. This is the atmospheric pressure at sea level.", "difficulty": "Medium"},
      {"question": "A candle is 12 inches tall when lit and decreases by 0.75 inches per hour. After how many hours will the candle be 6 inches tall?", "options": ["6", "8", "10", "12"], "answer": 1, "explanation": "6 = 12 − 0.75t → 0.75t = 6 → t = 8 hours.", "difficulty": "Medium"},
      {"question": "S = 15 + 0.2(T − 60) gives speed of sound S for temperature T above 60°C. Which is the best interpretation of 0.2?", "options": ["The speed of sound when T is 60 degrees", "The temperature at which the speed of sound is 15 m/s", "The increase in speed of sound for each 1 degree increase in temperature", "The temperature at which sound cannot travel"], "answer": 2, "explanation": "The coefficient 0.2 is the slope. For each 1-degree increase in T, speed S increases by 0.2 m/s.", "difficulty": "Hard"},
      {"question": "A bank account starts with $500. Every month, $75 is deposited. How many months to reach $1,400?", "options": ["8", "10", "12", "15"], "answer": 2, "explanation": "1,400 = 75m + 500 → 900 = 75m → m = 12 months.", "difficulty": "Medium"},
      {"question": "A = 1,500 + 20t estimates total cost A for a project taking t hours of labor. What does 1,500 represent?", "options": ["The hourly rate for labor", "The total cost if no labor is required", "The number of workers on the project", "The maximum budget for the project"], "answer": 1, "explanation": "At t = 0, A = 1,500. This fixed cost applies before any labor hours, so it is the cost if no labor is required.", "difficulty": "Medium"},
      {"question": "y = 0.15x + 2.50 models the cost y of a phone call lasting x minutes. If a call costs $6.10, how many minutes did it last?", "options": ["20", "22", "24", "28"], "answer": 2, "explanation": "6.10 = 0.15x + 2.50 → 3.60 = 0.15x → x = 24 minutes.", "difficulty": "Hard"},
      {"question": "w = 150 − 2.5t gives the weight of an ice block t hours after melting begins. What is the interpretation of 2.5?", "options": ["The initial weight of the ice block", "The weight of the block after 1 hour", "The amount of weight the ice block loses each hour", "The time it takes for the ice block to melt completely"], "answer": 2, "explanation": "The slope is −2.5, meaning the block loses 2.5 pounds per hour.", "difficulty": "Medium"},
      {"question": "A car''s tank has 15 gallons. It uses 0.04 gallons per mile. How many miles can it travel before only 5 gallons remain?", "options": ["200", "250", "300", "350"], "answer": 1, "explanation": "5 = 15 − 0.04m → 0.04m = 10 → m = 250 miles.", "difficulty": "Medium"},
      {"question": "T = 72 + 1.5h gives temperature T in a room h hours after the heater is turned on. Which is the best interpretation of 72?", "options": ["The temperature of the room when the heater was turned on", "The rate at which the temperature is increasing", "The temperature of the room after 1 hour", "The maximum temperature the room can reach"], "answer": 0, "explanation": "At h = 0, T = 72. This is the initial temperature when the heater was turned on.", "difficulty": "Medium"},
      {"question": "A subscription costs $12/month with a $30 sign-up fee. A member has paid $150 total. For how many months have they been a member?", "options": ["8", "10", "12", "15"], "answer": 1, "explanation": "12m + 30 = 150 → 12m = 120 → m = 10 months.", "difficulty": "Medium"},
      {"question": "y = 100 + 4x models a salesperson''s daily earnings y for selling x units. What does the slope represent?", "options": ["The salesperson''s base daily salary", "The number of units sold each day", "The commission earned for each unit sold", "The total earnings after selling x units"], "answer": 2, "explanation": "Slope = 4. For each additional unit sold, earnings increase by $4 — the per-unit commission.", "difficulty": "Hard"},
      {"question": "A balloon is released from 5 feet and rises at 2 feet per second. After how many seconds will it be 25 feet high?", "options": ["5", "10", "15", "20"], "answer": 1, "explanation": "25 = 2t + 5 → 20 = 2t → t = 10 seconds.", "difficulty": "Medium"},
      {"question": "G = 12 − 0.05d models gas remaining after driving d miles. What does the d-intercept represent?", "options": ["The car''s fuel efficiency in miles per gallon", "The maximum distance the car can drive on a full tank", "The initial amount of gas in the tank", "The distance driven when the tank is half full"], "answer": 1, "explanation": "Set G = 0: 0.05d = 12 → d = 240. The d-intercept is the maximum distance before the tank is empty.", "difficulty": "Hard"},
      {"question": "A water tank starts with 100 gallons. A pump removes 4 gallons per minute. How many minutes until exactly 20 gallons remain?", "options": ["15", "20", "25", "30"], "answer": 1, "explanation": "20 = 100 − 4t → 4t = 80 → t = 20 minutes.", "difficulty": "Medium"},
      {"question": "L = 0.5w + 10 gives spring length L for weight w. What does 0.5 represent?", "options": ["The length of the spring with no weight attached", "The total weight required to stretch the spring to 10 inches", "The increase in length for each 1 pound of weight attached", "The maximum weight the spring can hold"], "answer": 2, "explanation": "Slope = 0.5. Each additional pound increases the spring length by 0.5 inches.", "difficulty": "Medium"},
      {"question": "A rental car costs $40/day plus $0.20/mile. A person rents for 2 days and the total bill is $110. How many miles did they drive?", "options": ["100", "150", "200", "250"], "answer": 1, "explanation": "Daily cost = 40 × 2 = 80. 110 = 0.20m + 80 → 30 = 0.20m → m = 150 miles.", "difficulty": "Hard"},
      {"question": "C = 50 + 0.15n gives cost C to print n flyers. What is the interpretation of 0.15?", "options": ["The setup fee for the printing job", "The total cost to print 50 copies", "The price to print each additional copy", "The maximum number of copies that can be printed"], "answer": 2, "explanation": "Slope = 0.15. Each additional flyer costs $0.15 to print.", "difficulty": "Medium"},
      {"question": "y = 1.25x + 10 models a taxi fare. If a passenger''s fare was $35, how many miles was the trip?", "options": ["15", "20", "25", "30"], "answer": 1, "explanation": "35 = 1.25x + 10 → 25 = 1.25x → x = 20 miles.", "difficulty": "Hard"},
      {"question": "H = 60 − 5t gives liquid height H in a draining container t minutes after opening. What does 60 represent?", "options": ["The rate at which the liquid is draining", "The time it takes for the container to empty", "The initial height of the liquid in the container", "The height of the liquid after 1 minute"], "answer": 2, "explanation": "At t = 0, H = 60. This is the starting height before any draining occurs.", "difficulty": "Medium"},
      {"question": "A phone battery is at 100% and loses 8% per hour. After how many hours will it be at 20%?", "options": ["6", "8", "10", "12"], "answer": 2, "explanation": "20 = 100 − 8t → 8t = 80 → t = 10 hours.", "difficulty": "Hard"},
      {"question": "In y = mx + b, y is total cost and x is hours. If the service provider doubles their hourly rate but keeps the same flat fee, which describes the change?", "options": ["The y-intercept doubles", "The x-intercept doubles", "The slope doubles", "The graph shifts up by m units"], "answer": 2, "explanation": "Hourly rate = slope = m. Doubling the rate changes the equation to y = 2mx + b. The slope doubles.", "difficulty": "Medium"},
      {"question": "A hiker is at 2,000 feet and descends at 400 feet per hour. What is the elevation after 3.5 hours?", "options": ["400", "500", "600", "800"], "answer": 2, "explanation": "E = 2,000 − 400(3.5) = 2,000 − 1,400 = 600 feet.", "difficulty": "Medium"},
      {"question": "A = 500(1 + 0.05t) models a simple interest savings account. What is the interpretation of 0.05?", "options": ["The initial deposit in the account", "The annual interest rate as a decimal", "The total interest earned after t years", "The amount of money added each year"], "answer": 1, "explanation": "In the simple interest formula A = P(1 + rt), r is the interest rate. Here r = 0.05, or 5% per year.", "difficulty": "Hard"},
      {"question": "A car rental charges $35 per day. If a customer was charged $245, for how many days did they rent?", "options": ["5", "7", "9", "10"], "answer": 1, "explanation": "245 = 35d → d = 7 days.", "difficulty": "Medium"},
      {"question": "y = −0.8x + 12 models medication y remaining x hours after being administered. What does 12 represent?", "options": ["The time it takes for the medication to be fully cleared", "The dosage of the medication administered", "The rate at which the medication is cleared from the blood", "The amount of medication after 1 hour"], "answer": 1, "explanation": "At x = 0, y = 12. This is the initial dosage at the moment of administration.", "difficulty": "Hard"},
      {"question": "A spring stretches 2 cm for every 5 kg added. If initially 10 cm long, how long with 15 kg?", "options": ["12", "14", "16", "18"], "answer": 2, "explanation": "Rate = 2/5 = 0.4 cm/kg. L = 0.4(15) + 10 = 6 + 10 = 16 cm.", "difficulty": "Medium"},
      {"question": "y = 50x + 200 models production cost y for x units. To decrease cost per unit, which part should the company target?", "options": ["The value 50", "The value 200", "The variable x", "The variable y"], "answer": 0, "explanation": "Cost per unit is the slope (50). To reduce it, the company must lower this rate.", "difficulty": "Medium"},
      {"question": "A pool has 5,000 gallons and is filling at 15 gallons/min. How many hours to add 1,800 gallons?", "options": ["1", "2", "3", "4"], "answer": 1, "explanation": "Time = 1,800 / 15 = 120 minutes = 2 hours.", "difficulty": "Hard"},
      {"question": "V = 1,000(0.8)^t is exponential. If the value decreased by a constant $200 each year instead, which linear equation would model V over time t?", "options": ["V = 1,000 − 0.2t", "V = 1,000 − 200t", "V = 200t + 1,000", "V = 1,000(200)t"], "answer": 1, "explanation": "Constant decrease of $200/year: initial value = 1,000, slope = −200. V = 1,000 − 200t.", "difficulty": "Medium"},
      {"question": "A student has 400 pages left. Reading 25 pages/day, after how many days will 150 pages remain?", "options": ["8", "10", "12", "14"], "answer": 1, "explanation": "150 = 400 − 25d → 25d = 250 → d = 10 days.", "difficulty": "Medium"},
      {"question": "y = 0.5x + 10 models total weight y of a box with x books. What does 10 represent?", "options": ["The weight of each book", "The total weight of the books", "The weight of the empty box", "The maximum capacity of the box"], "answer": 2, "explanation": "At x = 0, y = 10. With no books, the weight is just the box itself.", "difficulty": "Hard"},
      {"question": "An athlete runs 6 miles at 8 minutes per mile. What is the total time in minutes?", "options": ["36", "42", "48", "54"], "answer": 2, "explanation": "Total time = 8 × 6 = 48 minutes.", "difficulty": "Medium"},
      {"question": "T = 20 + 0.5(d − 100) models temperature T for pressure d above 100 units. What is T when d = 100?", "options": ["0", "20", "50", "100"], "answer": 1, "explanation": "T = 20 + 0.5(100 − 100) = 20 + 0 = 20.", "difficulty": "Hard"},
      {"question": "A car rental costs $120 for 3 days. What is the daily rate?", "options": ["30", "35", "40", "45"], "answer": 2, "explanation": "Rate = 120 / 3 = $40 per day.", "difficulty": "Medium"},
      {"question": "y = 1.5x + 3.0 models coffee price y for x extra toppings. What is the base price with no toppings?", "options": ["$1.50", "$3.00", "$4.50", "$0.00"], "answer": 1, "explanation": "At x = 0, y = 3.00. The base price is $3.00.", "difficulty": "Medium"},
      {"question": "A plane is at 30,000 feet and descends at 1,500 feet per minute. How many minutes to reach 15,000 feet?", "options": ["5", "8", "10", "15"], "answer": 2, "explanation": "Descent needed = 30,000 − 15,000 = 15,000. Time = 15,000 / 1,500 = 10 minutes.", "difficulty": "Hard"},
      {"question": "n = 450 − 15t gives people n in a theater t minutes after a movie ends. What does 15 represent?", "options": ["The number of people when the movie ends", "The number of people who leave each minute", "The time it takes for all people to leave", "The total number of minutes the movie lasted"], "answer": 1, "explanation": "The slope is −15. For each minute, 15 people leave the theater.", "difficulty": "Medium"},
      {"question": "A gardener charges $25 to come plus $15/hour. If a job cost $85, how many hours did the gardener work?", "options": ["3", "4", "5", "6"], "answer": 1, "explanation": "85 = 15h + 25 → 60 = 15h → h = 4 hours.", "difficulty": "Hard"},
      {"question": "y = 0.8x + b models earnings y as a function of sales x. If the base salary increases, which part changes?", "options": ["The value 0.8", "The variable x", "The value b", "The variable y"], "answer": 2, "explanation": "Base salary = b (the y-intercept). Increasing base salary changes b.", "difficulty": "Medium"},
      {"question": "A car travels 300 miles on 12 gallons. What is its fuel efficiency in miles per gallon?", "options": ["20", "25", "30", "35"], "answer": 1, "explanation": "Efficiency = 300 / 12 = 25 mpg.", "difficulty": "Medium"},
      {"question": "P = 100 − 0.5t gives percentage P of a project remaining after t hours. What does the t-intercept represent?", "options": ["The total time required to finish the project", "The percentage completed in 1 hour", "The initial amount of work required", "The time when half the project is done"], "answer": 0, "explanation": "Set P = 0: 0.5t = 100 → t = 200. The project is finished in 200 hours.", "difficulty": "Hard"},
      {"question": "A machine produces 120 parts per hour. How many parts in 15 minutes?", "options": ["15", "20", "30", "40"], "answer": 2, "explanation": "15 min = 0.25 hr. Parts = 120 × 0.25 = 30.", "difficulty": "Medium"},
      {"question": "S = 24,000 + 1,200n gives salary S for n years of experience. Which is the best interpretation of 1,200?", "options": ["The starting salary of the employee", "The total salary after n years", "The annual raise the employee receives each year", "The total number of employees in the company"], "answer": 2, "explanation": "Slope = 1,200. For each additional year, salary increases by $1,200 — the annual raise.", "difficulty": "Hard"},
      {"question": "A candle is 15 inches tall and burns to 9 inches in 4 hours. What is the burning rate in inches per hour?", "options": ["1.0", "1.5", "2.0", "2.5"], "answer": 1, "explanation": "Height lost = 15 − 9 = 6 inches. Rate = 6 / 4 = 1.5 inches per hour.", "difficulty": "Hard"}
    ]'::jsonb
  )
  ON CONFLICT (lesson_id)
  DO UPDATE SET
    intro = EXCLUDED.intro,
    steps = EXCLUDED.steps,
    quiz = EXCLUDED.quiz,
    updated_at = now();

  RAISE NOTICE 'Interactive content populated for lesson lid-006: %', lid;
END $$;
