-- CBSE 10 Science — generated from TSV (questions.tsv)
-- Rows: 5

INSERT INTO cbse10_science_questions (
  type, prompt, options, correct_answer, explanation,
  domain, difficulty_tier, chapter, subtopic,
  bank_item_id, image_url, qc_done,
  is_pyq, pyq_year, correct_answer_b
)
VALUES
  (
    'spr',
    'If the charge on an electron is 1.6 × 10⁻¹⁹ C, find the approximate number of electrons in 1 C.',
    NULL,
    '6.25',
    '1 C charge contains 1 / (1.6 × 10⁻¹⁹) = 6.25 × 10¹⁸ electrons.',
    'electricity',
    'easy',
    'Electricity',
    'Electric Charge and Current',
    'cbse10_ch12_custom_q001',
    NULL,
    false,
    true,
    '2016',
    '18'
  ),
  (
    'mcq',
    'Which of the following correctly describes how the resistance $R$ of a conductor depends on its dimensions?',
    '[{"id":"a","text":"$R \\propto l$ and $R \\propto \\frac{1}{A}$"},{"id":"b","text":"$R \\propto \\frac{1}{l}$ and $R \\propto A$"},{"id":"c","text":"$R \\propto l$ and $R \\propto A$"},{"id":"d","text":"$R \\propto \\frac{1}{l}$ and $R \\propto \\frac{1}{A}$"}]'::jsonb,
    'a',
    'For a conductor, $R = \rho \frac{l}{A}$, so resistance is directly proportional to length and inversely proportional to area of cross-section. [CBSE 2016]',
    'electricity',
    'easy',
    'Electricity',
    'Resistance',
    'cbse10_ch12_custom_q002',
    NULL,
    false,
    true,
    '2016',
    NULL
  ),
  (
    'mcq',
    'What is the SI unit of electric potential?',
    '[{"id":"a","text":"Ampere"},{"id":"b","text":"Volt"},{"id":"c","text":"Ohm"},{"id":"d","text":"Watt"}]'::jsonb,
    'b',
    'Volt is the SI unit of electric potential. It is defined as the work done per unit charge (1 V = 1 J/C).',
    'electricity',
    'easy',
    'Electrostatics',
    'Electric Potential',
    'cbse10_ch12_custom_q003',
    NULL,
    false,
    true,
    '2016',
    NULL
  ),
  (
    'mcq',
    'When is the potential difference between two points said to be 1 volt?',
    '[{"id":"a","text":"When 1 J of work is done in moving 1 C charge between them"},{"id":"b","text":"When 1 W of power is dissipated between them"},{"id":"c","text":"When 1 A of current flows between them"},{"id":"d","text":"When 1 Ω of resistance exists between them"}]'::jsonb,
    'a',
    'Potential difference is 1 V when 1 J of work is done in moving 1 C of charge (V = W/Q).',
    'electricity',
    'easy',
    'Electrostatics',
    'Electric Potential',
    'cbse10_ch12_custom_q004',
    NULL,
    false,
    true,
    '2016',
    NULL
  ),
  (
    'mcq',
    'State Ohm''s law.',
    '[{"id":"a","text":"Current is inversely proportional to voltage at constant temperature"},{"id":"b","text":"Voltage across a conductor is proportional to current when physical conditions remain constant"},{"id":"c","text":"Resistance increases linearly with temperature"},{"id":"d","text":"Power dissipated is proportional to resistance"}]'::jsonb,
    'b',
    'Ohm''s Law states V = IR — voltage is directly proportional to current when physical conditions (temperature, material) remain constant.',
    'electricity',
    'easy',
    'Current Electricity',
    'Ohm''s Law',
    'cbse10_ch12_custom_q005',
    NULL,
    false,
    true,
    '2016',
    NULL
  )
ON CONFLICT (bank_item_id) DO UPDATE SET
  type              = EXCLUDED.type,
  prompt            = EXCLUDED.prompt,
  options           = EXCLUDED.options,
  correct_answer    = EXCLUDED.correct_answer,
  explanation       = EXCLUDED.explanation,
  domain            = EXCLUDED.domain,
  difficulty_tier   = EXCLUDED.difficulty_tier,
  chapter           = EXCLUDED.chapter,
  subtopic          = EXCLUDED.subtopic,
  image_url         = EXCLUDED.image_url,
  qc_done           = false,
  is_pyq            = EXCLUDED.is_pyq,
  pyq_year          = EXCLUDED.pyq_year,
  correct_answer_b  = EXCLUDED.correct_answer_b;
