-- CBSE 10 Science seed: ch15_ch16_mixed
-- Auto-generated from .tex files. All qc_done = false.
-- Total questions in this batch: 151

INSERT INTO cbse10_science_questions (
  type, prompt, options, correct_answer, explanation,
  domain, difficulty_tier, chapter, subtopic,
  bank_item_id, image_url, qc_done
)
VALUES
  (
    'mcq',
    'Which one of the following is an artificial ecosystem?',
    '[{"id": "a", "text": "Pond"}, {"id": "b", "text": "Crop field"}, {"id": "c", "text": "Lake"}, {"id": "d", "text": "Forest"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'In a food chain, the third trophic level is always occupied by',
    '[{"id": "a", "text": "carnivores"}, {"id": "b", "text": "herbivores"}, {"id": "c", "text": "decomposers"}, {"id": "d", "text": "producers"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'An ecosystem includes',
    '[{"id": "a", "text": "all living organisms"}, {"id": "b", "text": "non-living objects"}, {"id": "c", "text": "both living organisms and non-living objects"}, {"id": "d", "text": "sometimes living organisms and sometimes non-living objects"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'In the given food chain, suppose the amount of energy at fourth trophic level is $5 \mathrm{~kJ}$, what will be the energy available at the producer level?

Grass $\rightarrow$ Grasshopper $\rightarrow$ Frog $\rightarrow$ Snake $\rightarrow$ Hawk',
    '[{"id": "a", "text": "$5 \\mathrm{~kJ}$"}, {"id": "b", "text": "$50 \\mathrm{k} \\mathrm{J}$"}, {"id": "c", "text": "$500 \\mathrm{k} \\mathrm{J}$"}, {"id": "d", "text": "$5000 \\mathrm{k} \\mathrm{J}$"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Accumulation of non-biodegradable pesticides in the food chain in increasing amount at each higher trophic level is known as',
    '[{"id": "a", "text": "eutrophication"}, {"id": "b", "text": "pollution"}, {"id": "c", "text": "biomagnification"}, {"id": "d", "text": "accumulation"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Depletion of ozone is mainly due to',
    '[{"id": "a", "text": "chlorofluorocarbon compounds"}, {"id": "b", "text": "carbon monoxide"}, {"id": "c", "text": "methane"}, {"id": "d", "text": "pesticides"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'Organisms which synthesise carbohydrates from inorganic compounds using radiant energy are called',
    '[{"id": "a", "text": "decomposers"}, {"id": "b", "text": "producers"}, {"id": "c", "text": "herbivores"}, {"id": "d", "text": "carnivores"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'In an ecosystem, the $10 \%$ of energy available for transfer from one trophic level to the next is in the form of',
    '[{"id": "a", "text": "heat energy"}, {"id": "b", "text": "light energy"}, {"id": "c", "text": "chemical energy"}, {"id": "d", "text": "mechanical energy"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'Organisms of a higher trophic level which feed on several types of organisms belonging to a lower trophic level constitute the',
    '[{"id": "a", "text": "food web"}, {"id": "b", "text": "ecological pyramid"}, {"id": "c", "text": "ecosystem"}, {"id": "d", "text": "food chain"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'Flow of energy in an ecosystem is always',
    '[{"id": "a", "text": "unidirectional"}, {"id": "b", "text": "bidirectional"}, {"id": "c", "text": "multi directional"}, {"id": "d", "text": "no specific direction"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'Excessive exposure of humans to U V-rays results in
\begin{enumerate}[label=\roman*)]
    \item damage to immune system
    \item damage to lungs
    \item skin cancer
    \item peptic ulcers
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(ii) and (iv)"}, {"id": "c", "text": "(i) and (iii)"}, {"id": "d", "text": "(iii) and (iv)"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'In the following groups of materials, which group (s) contains only non-biodegradable items?
\begin{enumerate}[label=\roman*)]
    \item Wood, paper, leather
    \item Polythene, detergent, PVC
    \item Plastic, detergent, grass
    \item Plastic, bakelite, DDT
\end{enumerate}',
    '[{"id": "a", "text": "(iii)"}, {"id": "b", "text": "(iv)"}, {"id": "c", "text": "(i) and (iii)"}, {"id": "d", "text": "(ii) and (iv)"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following limits the number of trophic levels in a food chain?',
    '[{"id": "a", "text": "Decrease in energy at higher trophic levels"}, {"id": "b", "text": "Dufficient food supply"}, {"id": "c", "text": "Polluted air"}, {"id": "d", "text": "Water"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the statement is incorrect?',
    '[{"id": "a", "text": "All green plants and blue green algae are producers"}, {"id": "b", "text": "Green plants get their food from organic compounds"}, {"id": "c", "text": "Producers prepare their own food from inorganic compounds"}, {"id": "d", "text": "Plants convert solar energy into chemical energy"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Which group of organisms are not constituents of a food chain?
\begin{enumerate}[label=\roman*)]
    \item Grass, lion, rabbit, wolf
    \item Plankton, man, fish, grasshopper
    \item Wolf, grass, snake, tiger
    \item Frog, snake, eagle, grass, grasshopper
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iii)"}, {"id": "b", "text": "(iii) and (iv)"}, {"id": "c", "text": "(ii) and (iii)"}, {"id": "d", "text": "(i) and (iv)"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'The percentage of solar radiation absorbed by all the green plants for the process of photosynthesis is about',
    '[{"id": "a", "text": "$1 \\%$"}, {"id": "b", "text": "$5 \\%$"}, {"id": "c", "text": "$8 \\%$"}, {"id": "d", "text": "$10 \\%$"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'In the given Figure the various trophic levels are shown in a pyramid. At which trophic level is maximum energy available?
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.4\textwidth]{15.Class 10_NCERT Exempler_Our Environment_1.jpg}
    \end{center}
% Diagram Ends',
    '[{"id": "a", "text": "$\\mathrm{T}_{4}$"}, {"id": "b", "text": "$\\mathrm{T}_{2}$"}, {"id": "c", "text": "$\\mathrm{T}_{1}$"}, {"id": "d", "text": "$\\mathrm{T}_{3}$"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q017',
    'our-environment/cbse10_ch15_exemplar_q017.jpg',
    false
  ),
  (
    'mcq',
    'What will happen if deer is missing in the food chain given below?

Grass $\rightarrow$ Deer $\rightarrow$ Tiger',
    '[{"id": "a", "text": "The population of tiger increases"}, {"id": "b", "text": "The population of grass decreases"}, {"id": "c", "text": "Tiger will start eating grass"}, {"id": "d", "text": "The population of tiger decreases and the population of grass increases"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'The decomposers in an ecosystem',
    '[{"id": "a", "text": "convert inorganic material, to simpler forms"}, {"id": "b", "text": "convert organic material to inorganic forms"}, {"id": "c", "text": "convert inorganic materials into organic compounds"}, {"id": "d", "text": "do not breakdown organic compounds"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q019',
    NULL,
    false
  ),
  (
    'mcq',
    'If a grass hopper is eaten by a frog, then the energy transfer will be from',
    '[{"id": "a", "text": "producer to decomposer"}, {"id": "b", "text": "producer to primary consumer"}, {"id": "c", "text": "primary consumer to secondary consumer"}, {"id": "d", "text": "secondary consumer to primary consumer"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'Disposable plastic plates should not be used because',
    '[{"id": "a", "text": "they are made of materials with light weight"}, {"id": "b", "text": "they are made of toxic materials"}, {"id": "c", "text": "they are made of biodegradable materials"}, {"id": "d", "text": "they are made of non-biodegradable materials"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q021',
    NULL,
    false
  ),
  (
    'spr',
    'Why is improper disposal of waste a curse to environment?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q022',
    NULL,
    false
  ),
  (
    'spr',
    'Write the common food chain of a pond ecosystem.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q023',
    NULL,
    false
  ),
  (
    'spr',
    'What are the advantages of cloth bags over plastic bags during shopping?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q024',
    NULL,
    false
  ),
  (
    'spr',
    'Why are crop fields known as artificial ecosystems?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q025',
    NULL,
    false
  ),
  (
    'spr',
    'Differentiate between biodegradable and non-biodegradable substances. Cite examples.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q026',
    NULL,
    false
  ),
  (
    'mcq',
    'Suggest one word for each of the following statements/definitions',
    '[{"id": "a", "text": "The physical and biological world where we live in"}, {"id": "b", "text": "Each level of food chain where transfer of energy takes place"}, {"id": "c", "text": "The physical factors like temperature, rainfall, wind and soil of an ecosystem"}, {"id": "d", "text": "Organisms which depend on the producers either directly or indirectly for food"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q027',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the role of decomposers in the environment?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q028',
    NULL,
    false
  ),
  (
    'spr',
    'Select the mis-matched pair in the following and correct it.
% Table Begins
    \begin{center}
    \renewcommand{\arraystretch}{1.5}
    \begin{tabular}{| c | c |} 
    \hline
    (a) Biomagnification & Accumulation of chemicals at the successive trophic levels of a food chain \\
    \hline
    (b) Ecosystem & Biotic components of environment \\
    \hline
    (c) Aquarium & A man-made ecosystem \\
    \hline
    (d) Parasites & Organisms which obtain food from other living organisms \\
    \hline
    \end{tabular}
    \end{center}
% Table Ends',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q029',
    NULL,
    false
  ),
  (
    'spr',
    'We do not clean ponds or lakes, but an aquarium needs to be cleaned. Why?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q030',
    NULL,
    false
  ),
  (
    'spr',
    'Indicate the flow of energy in an ecosystem. Why is it unidirectional? Justify.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q031',
    NULL,
    false
  ),
  (
    'spr',
    'What are decomposers? What will be the consequence of their absence in an ecosystem?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q032',
    NULL,
    false
  ),
  (
    'spr',
    'Suggest any four activities in daily life which are eco-friendly.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q033',
    NULL,
    false
  ),
  (
    'spr',
    'Give two differences between food chain and food web.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q034',
    NULL,
    false
  ),
  (
    'spr',
    'Name the wastes which are generated in your house daily. What measures would you take for their disposal?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q035',
    NULL,
    false
  ),
  (
    'spr',
    'Suggest suitable mechanism (s) for waste management in fertiliser industries.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q036',
    NULL,
    false
  ),
  (
    'spr',
    'What are the by-products of fertiliser industries? How do they affect the environment?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q037',
    NULL,
    false
  ),
  (
    'spr',
    'Explain some harmful effects of agricultural practices on the environment.

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_exemplar_q038',
    NULL,
    false
  ),
  (
    'spr',
    'What are trophic levels? Give an example of a food chain and state the different trophic levels in it.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What is the role of decomposers in the ecosystem?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'Why are some substances biodegradable and some non-biodegradable?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'Give any two ways in which blodegradable substances would affect the environment.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'Give any two ways in which non-biodegradable substances would affect the environment.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'What is ozone and how does it affect any ecosystem?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'How can you help in reducing the problem of waste disposal? Give any two methods.',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following groups contain only biodegradable items?',
    '[{"id": "a", "text": "Grass, flowers and leather"}, {"id": "b", "text": "Grass, wood and plastic"}, {"id": "c", "text": "Fruit-peels, cake and lime-juice"}, {"id": "d", "text": "Cake, wood and grass"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following constitute a food-chain?',
    '[{"id": "a", "text": "Grass, wheat and mango"}, {"id": "b", "text": "Grass, goat and human"}, {"id": "c", "text": "Goat, cow and elephant"}, {"id": "d", "text": "Grass, fish and goat"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following are environment-friendly practices?',
    '[{"id": "a", "text": "Carrying cloth-bags to put purchases in while shopping"}, {"id": "b", "text": "Switching off unnecessary lights and fans"}, {"id": "c", "text": "Walking to school instead of getting your mother to drop you on her scooter"}, {"id": "d", "text": "All of the above"}]'::jsonb,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q010',
    NULL,
    false
  ),
  (
    'spr',
    'What will happen if we kill all the organisms in one trophic level?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'Will the impact of removing all the organisms in a trophic level be different for different trophic levels? Can the organisms of any trophic level be removed without causing any damage to the ecosystem?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q012',
    NULL,
    false
  ),
  (
    'spr',
    'What is biological magnification? Will the levels of this magnification be different at different levels of the ecosystem?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q013',
    NULL,
    false
  ),
  (
    'spr',
    'What are the problems caused by the non-biodegradable wastes that we generate?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q014',
    NULL,
    false
  ),
  (
    'spr',
    'If all the waste we generate is biodegradable, will this have no impact on the environment?',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q015',
    NULL,
    false
  ),
  (
    'spr',
    'Why is damage to the ozone layer a cause for concern? What steps are being taken to limit this damage?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'our-environment',
    'medium',
    'Our Environment',
    NULL,
    'cbse10_ch15_ncert_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'From the list given below pick the item that is not a natural resource',
    '[{"id": "a", "text": "Soil"}, {"id": "b", "text": "Water"}, {"id": "c", "text": "Electricity"}, {"id": "d", "text": "Air"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'The most rapidly dwindling natural resource in the world is',
    '[{"id": "a", "text": "water"}, {"id": "b", "text": "forests"}, {"id": "c", "text": "wind"}, {"id": "d", "text": "sunlight"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'The most appropriate definition of a natural resource is that it is a substance/commodity that is',
    '[{"id": "a", "text": "present only on land"}, {"id": "b", "text": "a gift of nature which is very useful to mankind"}, {"id": "c", "text": "a man-made substance placed in nature"}, {"id": "d", "text": "available only in the forest"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'The main cause for abundant coliform bacteria in the river Ganga is',
    '[{"id": "a", "text": "disposal of unburnt corpses into water"}, {"id": "b", "text": "discharge of effluents from electroplating industries"}, {"id": "c", "text": "washing of clothes"}, {"id": "d", "text": "immersion of ashes"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'The $\mathrm{pH}$ of water sample collected from a river was found to be acidic in the range of $3.5-4.5$, on the banks of the river were several factories that were discharging effluents into the river. The effluents of which one of the following factories is the most likely cause for lowering the $\mathrm{pH}$ of river water?',
    '[{"id": "a", "text": "Soap and detergent factory"}, {"id": "b", "text": "Lead battery manufacturing factory"}, {"id": "c", "text": "Plastic cup manufacturing factory"}, {"id": "d", "text": "Alcohol distillery"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'The $\mathrm{pH}$ range most conducive for life of fresh water plants and animals is',
    '[{"id": "a", "text": "$6.5-7.5$"}, {"id": "b", "text": "$2.0-3.5$"}, {"id": "c", "text": "$3.5-5.0$"}, {"id": "d", "text": "$9.0-10.5$"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'The three R''s that will help us to conserve natural resources for long term use are',
    '[{"id": "a", "text": "recycle, regenerate, reuse"}, {"id": "b", "text": "reduce, regenerate, reuse"}, {"id": "c", "text": "reduce, reuse, redistribute"}, {"id": "d", "text": "reduce, recycle, reuse"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'Given below are a few statements related to biodiversity. Pick those that correctly describe the concept of biodiversity
\begin{enumerate}[label=\roman*)]
    \item Biodiversity refers to the different species of flora and fauna present in an area
    \item Biodiversity refers to only the flora of a given area
    \item Biodiversity is greater in a forest
    \item Biodiversity refers to the total number of individuals of a particular species living in an area
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(ii) and (iv)"}, {"id": "c", "text": "(i) and (iii)"}, {"id": "d", "text": "(ii) and (iii)"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'Among the statements given below select the ones that correctly describe the concept of sustainable development
\begin{enumerate}[label=\roman*)]
    \item Planned growth with minimum damage to the environment
    \item Growth irrespective of the extent of damage caused to the environment
    \item Stopping all developmental work to conserve the environment
    \item Growth that is acceptable to all the stakeholders
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(ii) and (iv)"}, {"id": "d", "text": "(iii) only"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'In our country, vast tracts of forests are cleared and a single species of plant is cultivated. This practice promotes',
    '[{"id": "a", "text": "biodiversity in the area"}, {"id": "b", "text": "monoculture in the area"}, {"id": "c", "text": "growth of natural forest"}, {"id": "d", "text": "preserves the natural ecosystem in the area"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'A successful forest conservation strategy should involve',
    '[{"id": "a", "text": "protection of animals at the highest trophic level"}, {"id": "b", "text": "protection of only consumers"}, {"id": "c", "text": "protection of only herbivores"}, {"id": "d", "text": "comprehensive programme to protect all the physical and biological components"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'The important message conveyed by the ''Chipko Movement'' is',
    '[{"id": "a", "text": "to involve the community in forest conservation efforts"}, {"id": "b", "text": "to ignore the community in forest conservation efforts"}, {"id": "c", "text": "to cut down forest trees for developmental activities"}, {"id": "d", "text": "government agencies have the unquestionable right to order destruction of trees in forests"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'In our country, there are attempts to increase the height of several existing dams like Tehri and Almati, dams across Narmada.

Choose the correct statements among the following that are a consequence of raising the height of dams
\begin{enumerate}[label=\roman*)]
    \item Terrestrial flora and fauna of the area is destroyed completely
    \item Dislocation of people and domestic animals living in the area
    \item Valuable agricultural land may be permanently lost
    \item It will generate permanent employment for people
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(i), (ii) and (iii)"}, {"id": "c", "text": "(ii) and (iv)"}, {"id": "d", "text": "(i), (iii) and (iv)"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Expand the abbreviation GAP',
    '[{"id": "a", "text": "Governmental Agency for Pollution Control"}, {"id": "b", "text": "Gross Assimilation by Photosynthesis"}, {"id": "c", "text": "Ganga Action Plan"}, {"id": "d", "text": "Governmental Agency for Animal Protection"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Select the incorrect statement',
    '[{"id": "a", "text": "Economic development is linked to environmental conservation"}, {"id": "b", "text": "Sustainable development encourages development for current generation and conservation of resources for future generations"}, {"id": "c", "text": "Sustainable development does not consider the view points of stakeholders"}, {"id": "d", "text": "Sustainable development is a long planned and persistent development"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is not a natural resource?',
    '[{"id": "a", "text": "Mango tree"}, {"id": "b", "text": "Snake"}, {"id": "c", "text": "Wind"}, {"id": "d", "text": "Wooden house"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'Select the wrong statement',
    '[{"id": "a", "text": "Forests provide variety of products"}, {"id": "b", "text": "Forests have greater plant diversity"}, {"id": "c", "text": "Forests do not conserve soil"}, {"id": "d", "text": "Forests conserve water"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'Arabari forests of Bengal is dominated by',
    '[{"id": "a", "text": "Teak"}, {"id": "b", "text": "Sal"}, {"id": "c", "text": "Bamboo"}, {"id": "d", "text": "Mangroove"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'Ground water will not be depleted due to',
    '[{"id": "a", "text": "afforestation"}, {"id": "b", "text": "thermal power plants"}, {"id": "c", "text": "loss of forest, and decreased rainfall"}, {"id": "d", "text": "cropping of high water demanding crops"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q019',
    NULL,
    false
  ),
  (
    'mcq',
    'Opposition to the constrution of large dams is due to',
    '[{"id": "a", "text": "social reasons"}, {"id": "b", "text": "economic reasons"}, {"id": "c", "text": "enviromental reasons"}, {"id": "d", "text": "all the above"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'Khadins, Bundhis, Ahars and Kattas are ancient structures that are examples for',
    '[{"id": "a", "text": "grain storage"}, {"id": "b", "text": "wood storage"}, {"id": "c", "text": "water harvesting"}, {"id": "d", "text": "soil conservation"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q021',
    NULL,
    false
  ),
  (
    'mcq',
    'Pick the right combination of terms which has no fossil fuel.',
    '[{"id": "a", "text": "Wind, ocean and coal"}, {"id": "b", "text": "Kerosene, wind and tide"}, {"id": "c", "text": "Wind, wood, sun"}, {"id": "d", "text": "Petroleum, wood, sun"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'Select the eco-friendly activity among the following',
    '[{"id": "a", "text": "Using car for transportation"}, {"id": "b", "text": "Using polybags for shopping"}, {"id": "c", "text": "Using dyes for colouring clothes"}, {"id": "d", "text": "Using windmills to generate power for irrigation"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'It is important to make small check dams across the flooded gullies because they
\begin{enumerate}[label=\roman*)]
    \item hold water for irrigation
    \item hold water and prevent soil erosion
    \item recharge ground water
    \item hold water permanently
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(iii) and (iv)"}, {"id": "d", "text": "(ii) and (iv)"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q024',
    NULL,
    false
  ),
  (
    'spr',
    'Prepare a list of five items that you use daily in the school. Identify from the list such items that can be recycled.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q025',
    NULL,
    false
  ),
  (
    'spr',
    'List two advantages associated with water harvesting at the community level.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q026',
    NULL,
    false
  ),
  (
    'spr',
    'In a village in Karnataka, people started cultivating crops all around a lake which was always filled with water. They added fertilisers to their field in order to enhance the yield. Soon they discovered that the waterbody was completely covered with green floating plants and fishes started dying in large numbers.

Analyse the situation and give reasons for excessive growth of plants and death of fish in the lake.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q027',
    NULL,
    false
  ),
  (
    'spr',
    'What measures would you take to conserve electricity in your house?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q028',
    NULL,
    false
  ),
  (
    'spr',
    'Although coal and petroleum are produced by degradatioin of bio- mass, yet we need to conserve them. Why?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q029',
    NULL,
    false
  ),
  (
    'spr',
    'Suggest a few measures for controlling carbon dioxide levels in the atmosphere.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q030',
    NULL,
    false
  ),
  (
    'mcq',
    '% Diagram Begins
    \begin{center}
    \includegraphics[width=0.6\textwidth]{16.Class 10_NCERT Exempler_Management of Natural Resources_1.jpg}
    \end{center}
% Diagram Ends

% Diagram Begins
    \begin{center}
    \includegraphics[width=0.4\textwidth]{16.Class 10_NCERT Exempler_Management of Natural Resources_2.jpg}
    \end{center}
% Diagram Ends',
    '[{"id": "a", "text": "Locate and name the water reservoirs in Figures."}, {"id": "b", "text": "Which has an advantage over the other and why?"}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q031',
    'sustainable-management/cbse10_ch16_exemplar_q031.jpg',
    false
  ),
  (
    'spr',
    'In the context of conservation of natural resources, explain the terms reduce, recycle and reuse. From among the materials that we use in daily life, identify two materials for each category.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q032',
    NULL,
    false
  ),
  (
    'spr',
    'Prepare a list of five activities that you perform daily in which natural resources can be conserved or energy utilisation can be minimised.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q033',
    NULL,
    false
  ),
  (
    'spr',
    'Is water conservation necessary? Give reasons.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q034',
    NULL,
    false
  ),
  (
    'spr',
    'Suggest a few useful ways of utilising waste water.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q035',
    NULL,
    false
  ),
  (
    'spr',
    'What is the importance of forest as a resource?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q036',
    NULL,
    false
  ),
  (
    'spr',
    'Why are the Arabari forests of Bengal known to be a good example of conserved forest?

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_exemplar_q037',
    NULL,
    false
  ),
  (
    'spr',
    'What changes can you make in your habits to become more environment friendly?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What would be the advantages of exploiting resources with short-term aims?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'How would these advantages differ from the advantages of using a longterm perspective in managing our resources?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'Why do you think that there should be equitable distribution of resources? \newline
What forces would be working against an equitable distribution of our resources?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'Why should we conserve forests and wildlife?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'Suggest some approaches towards the conservation of forests.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'Find out about the traditional systems of water harvesting/ management in your region.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q007',
    NULL,
    false
  ),
  (
    'spr',
    'Compare the above system with the probable systems in hilly/ mountainous areas or plains or plateau reglons.',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q008',
    NULL,
    false
  ),
  (
    'spr',
    'Find out the source of water in your region/locality. Is water from this source avallable to all people living in that area?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q009',
    NULL,
    false
  ),
  (
    'spr',
    'What changes would you suggest in your home in order to be environment-friendly?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q010',
    NULL,
    false
  ),
  (
    'spr',
    'Can you suggest some changes in your school which would make it environment-friendly?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'We saw in this chapter that there are four main stakeholders when it comes to forests and wildlife. Which among these should have the authority to decide the management of forest produce? Why do you think so?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q012',
    NULL,
    false
  ),
  (
    'spr',
    'How can you as an individual contribute or make a difference to the management of (a) forests and wildiffe, (b) water resources and (c) coal and petroleum?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q013',
    NULL,
    false
  ),
  (
    'spr',
    'What can you as an individual do to reduce your consumption of the various natural resources?',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'List five things you have done over the last one week to -',
    '[{"id": "a", "text": "conserve our natural resources."}, {"id": "b", "text": "increase the pressure on our natural resources."}]'::jsonb,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q015',
    NULL,
    false
  ),
  (
    'spr',
    'On the basis of the issues raised in this chapter, what changes would you incorporate in your lifestyle in a move towards a sustainable use of our resources?

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'sustainable-management',
    'medium',
    'Sustainable Management of Natural Resources',
    NULL,
    'cbse10_ch16_ncert_q016',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "What constitutes the central and peripheral nervous systems?"}, {"id": "b", "text": "How are the components of the nervous system protected?\nWhich signals will get disrupted in case of a spinal cord injury?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'Write the function of the following:',
    '[{"id": "a", "text": "Salivary amylase"}, {"id": "b", "text": "Pepsin"}, {"id": "c", "text": "Mucous"}, {"id": "d", "text": "Trypsin"}, {"id": "e", "text": "Bile Salt"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q002',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Tabulate the differences between nervous control and chemical control?"}, {"id": "b", "text": "what is the difference between involuntary action and reflex action."}, {"id": "c", "text": "Why does the flow of signals in a synapse from the axonal end of one neuron to the dendritic end of another neuron take place but not in the reverse direction? Explain."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q003',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Name the organs that form the excretory system in human beings ?"}, {"id": "b", "text": "With help of a well-labeled diagram. Describe in brief how urine is produced in human body, explain through steps."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q004',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Mention any two components of blood"}, {"id": "b", "text": "Trace the movements of oxygenated blood in the body"}, {"id": "c", "text": "Write the function of valves present in between atria and ventricles"}, {"id": "d", "text": "Write one structural differences between the composition of artery and vein."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Give reasons for the following:',
    '[{"id": "a", "text": "The glottis is guarded by epiglottis."}, {"id": "b", "text": "It is said to not speak while eating."}, {"id": "c", "text": "Walls of trachea are supported by cartilage rings"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q006',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Draw a flow chart showing the three different pathways involved in the breakdown of glucose in different organisms."}, {"id": "b", "text": "Name the respiratory pigment present in human beings."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q007',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "With the help of an activity, explain the action of saliva on the food we eat."}, {"id": "b", "text": "Explain oxygen and carbon dioxide transport in human beings."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'Because both oxygen and carbon dioxide have to transported by the blood, the heart has different chambers prevent the oxygen-rich blood from mixing with the blo containing carbon dioxide. The carbon dioxide-rich blood $h$ to reach the lungs for the carbon dioxide to be removed, a the oxygenated blood from the linas has to be brought back the heart. This oxygen-rich $b^{\prime}$ hen pumped to the rest the body.',
    '[{"id": "a", "text": "How many chambers are $g$ reptiles? 4 the heart of mammals a"}, {"id": "b", "text": "Who carry deoxygenated b body to heart?"}, {"id": "c", "text": "What do you meant by the term doub le  circulation?"}, {"id": "d", "text": "What is hypertension?"}, {"id": "e", "text": "Which device measures blood pressure"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q009',
    NULL,
    false
  ),
  (
    'spr',
    'How are the lungs designed to maximise the area for exchanging gases in humans?',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q010',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "We do not clean ponds or lakes, but an aquarium needs to be cleaned regularly."}, {"id": "b", "text": "\"Although gardens are created by mon, they ore considered to be ecosystems.\" Justify this statement."}, {"id": "c", "text": "How is ozone formed in the higher levels of the atmosphere? \" Damage to the ozone layer is a couse of concern? Justify this statement."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q011',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "A food chain generally has three or four trophic levels. Explain. \nWhat is biological magnification?"}, {"id": "b", "text": "What is ten percent law? Explain with on example how energy flows through different trophic levels"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Aarya, a 32-year-old female, visits her doctor with complaints of indigestion, bloating, and diarthea after meals. She is concerned about her digestive health and wants to understand more about the role of hormones in digestion.',
    '[{"id": "a", "text": "Symptoms might be related to the digestive hormones. Can you name some of the key hormones involved in the digestive process?"}, {"id": "b", "text": "Can you tell me which hormone stimulates the release of stom\u00e0ch acid?"}, {"id": "c", "text": "Which hormone is responsible for regulating blood sugar levels esnecially after a meal?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'The function of nervous system is to coordinate the activities of our body. Bt is the control system for all our actions, thinking and behaviour. The nervous system helps all other systems of our body to work together.the system is like a manager inside our body. Bts job is to control and coordinate the parts of our body so that they work together, doing their job at the right time.',
    '[{"id": "a", "text": "The function of nervous system is to coordinate\n- the $\\qquad$"}, {"id": "b", "text": "How nervous system process the information"}, {"id": "c", "text": "Nervous system is made of special cells called"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'The endocrine system is a complex network of glands and hormones that play a crucial role in regulating various physiological processes in the human body. In males, the endocrine system is responsible for the development and mainteriance of secondary sexual characteristics, as well as the overall functioning of the body',
    '[{"id": "a", "text": "What is testosterone, and where is it produced in males?"}, {"id": "b", "text": "What are the functions of testosterone in males?"}, {"id": "c", "text": "What is the role of luteinizing hormone in the male endocrine system?12 th"}, {"id": "d", "text": "What happens if there is a deficiency of LH in males?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Insulin is a type of hormone. Hormones are chemical messengers that instruct certain cells or tissues to act in a certain way that supports a particular function in the body.',
    '[{"id": "a", "text": "What is insulin, and what is its primary role in the body?"}, {"id": "b", "text": "What happens when the body doesn''t produce enough insulin?"}, {"id": "c", "text": "What triggers the release of insulin in the body?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q016',
    NULL,
    false
  ),
  (
    'spr',
    'what is feedback mechanism ? 

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed1_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'Anita added a drop each of diluted acetic acid and diluted hydrochloric acid on pH paper and compared the colors. Which of the following is the correct conclusion?',
    '[{"id": "a", "text": "pH of acetic acid is more than that of hydrochloric acid."}, {"id": "b", "text": "pH of acetic acid is less than that of hydrochloric acid."}, {"id": "c", "text": "Acetic acid dissociates completely in aqueous solution."}, {"id": "d", "text": "Acetic acid is a strong acid"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'Calamine is used to reduce the irritating effect of ant bite/ sting because it reacts with $X$ released due to the bite/sting ants with Y present in calamine. Then X and Y respectively',
    '[{"id": "a", "text": "Sodium hydrogen carbonate and formic acid"}, {"id": "b", "text": "Formic acid and zinc carbonate"}, {"id": "c", "text": "Acetic acid and common salt"}, {"id": "d", "text": "Hydrochloric acid and zinc oxide"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q002',
    NULL,
    false
  ),
  (
    'spr',
    'What are antacids ? What will happen if a person takes antacids in excess amount ?',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q003',
    NULL,
    false
  ),
  (
    'spr',
    'What is meant by the term water of crystallisation? How would you show that copper sulphate crystals contains water of crystallisation?',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Crystals of a substance changes their colour on heating in a closed vessel but regained it after sometime, when they were allowed to cool down.',
    '[{"id": "a", "text": "Name one such substance."}, {"id": "b", "text": "Explain the phenomenon involved."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q005',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Why does aqueous solution of an acid conduct electricity?"}, {"id": "b", "text": "How does the concentration of $\\mathrm{H}_3 \\mathrm{O}^{-}$ions change when a solution of an acid is diluted?"}, {"id": "c", "text": "Which one has a higher pH , a concentrated or a dilute solution of hydrochloric acid?"}, {"id": "d", "text": "What would to be the gas evolved on adding dilute to hydrochloric acid to\n(i) Solid sodium carbonate placed in a test tube?\n(ii) Zinc metal in a test tube?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q006',
    NULL,
    false
  ),
  (
    'spr',
    'A white chemical compound becomes hard on mixing proper quantity of water. It is also used to maintain joints in fixed position. Name the chemical compound and write its chemical formula. Write the chemical equation to show what happens when water is added to this compound in proper quantity.',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'A substance '' $X$ '' is used as antacid reacts with hydrochloric acid to produce a gas W which is used in fire extinguishers:',
    '[{"id": "a", "text": "Name the substance X and Y"}, {"id": "b", "text": "Write a balanced equation of the reaction between X and hydrochloric acid."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q008',
    NULL,
    false
  ),
  (
    'spr',
    'Dil. HCl is added to Zn granules." How will you prove that chemical change has taken place here? Support your response with two arguments',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q009',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Write the chemical name and formula of marble."}, {"id": "b", "text": "It has been found that marbles of Taj are getting corroded due to development of industrial areas around it. Explain this fact giving a chemical equation."}, {"id": "c", "text": "What happens when $\\mathrm{CO}_2$ is passed through lime water?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'A Milkman Adds a Very Small Amount of Baking Soda to Fresh Milk.',
    '[{"id": "a", "text": "Why does he shift the pH of the fresh milk from 6 to slightly alkaline?"}, {"id": "b", "text": "Why Does This Milk Toke a Long Time To Set As Curd?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q011',
    NULL,
    false
  ),
  (
    'spr',
    'Give two Important Uses of Washing Soda and Baking Soda.',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q012',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "What is the molecular formula of gypsum?"}, {"id": "b", "text": "What are the uses of Ploster of Paris?"}, {"id": "c", "text": "Crystals of a substance changed their colour on heating in a closed test tube but regained it after some time when they were allowed to cool down.\n(i) Name the substance and write its formula (ii) Explain the phenomenon involved"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q013',
    NULL,
    false
  ),
  (
    'spr',
    'A compound X is bitter in toste. It is a component of washing powder reacts with dil. HCl to produce brisk effervescence due to colorless, odorless gas Y which turns lime water milky due to formation of $Z$. When an excess of is passed, milkiness disappears due to the formation of P. Identify X, Y, And Z.',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q014',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "What are the products obtained when Lead nitrate is heated in a boiling tube ?"}, {"id": "b", "text": "The products obtained when Lead nitrate is heated in a boiling tube:"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Translate the following statements into chemical equations and then balance them:',
    '[{"id": "a", "text": "Solution of barium chloride and aluminium sulphate in water reacts to give insoluble barium sulphate and the solution of aluminium chloride."}, {"id": "b", "text": "Aluminium metal reacts with steam to give aluminium oxide and hydrogen gas."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'In the electrolysis of water,',
    '[{"id": "a", "text": "Name the gasses liberated at anode \\& cathode."}, {"id": "b", "text": "Why is it that the volume of gas collected on one electrode is two times that on the other electrode?"}, {"id": "c", "text": "What would happen if dilute $\\mathrm{H}_2 \\mathrm{SO}_4$ is not added to water?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'Give reasons for the following:',
    '[{"id": "a", "text": "Platinum, gold and silver are used for making jewellery."}, {"id": "b", "text": "Sodium, potassium and lithium are stored under kerosene oil."}, {"id": "c", "text": "Aluminium is highly reactive metal but still used for making cooking utensils."}, {"id": "d", "text": "Carbonate and sulphide ores are usually converted into oxides during the process of extraction."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q018',
    NULL,
    false
  ),
  (
    'spr',
    'Show the electronic transfer in formation of $\mathrm{MgCl}_2$ from its elements.',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q019',
    NULL,
    false
  ),
  (
    'mcq',
    '% =============================================================
%Question End
% =============================================================',
    '[{"id": "a", "text": "Why do silver articles turn black after sometime?"}, {"id": "b", "text": "Hydrogen gas is not evolved when most of the metals react with nitric acid."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed2_q020',
    NULL,
    false
  ),
  (
    'spr',
    'What is the difference between mineral acids and organic acids?',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q001',
    NULL,
    false
  ),
  (
    'spr',
    'Explain oxidation and reduction with two examples in each case.',
    NULL,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'Write the balanced chemical equations for the following reactions.',
    '[{"id": "a", "text": "Calcium Hydroxide + Carbon Dioxide $\\longrightarrow$  Calcium Carbonate + Water"}, {"id": "b", "text": "Barium Chloride + Aluminium Sulphate $\\longrightarrow$  Barium Sulphate + Aluminium Chloride"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'Oxidation is the gain of oxygen or loss of hydrogen. Reduction is the loss of oxygen or gain of hydrogen in the reaction.

$\mathrm{MnO}_2+4 \mathrm{HCl} \longrightarrow \mathrm{MnCl}_2+2 \mathrm{H}_2 \mathrm{O}+\mathrm{Cl}_2
$',
    '[{"id": "a", "text": "Name the compound oxidised."}, {"id": "b", "text": "Name the compound reduced."}, {"id": "c", "text": "Name the oxidising agent."}, {"id": "d", "text": "Name the reducing agent."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Write chemical equation when zinc granules react with:',
    '[{"id": "a", "text": "Sulphuric acid"}, {"id": "b", "text": "Hydrochloric acid"}, {"id": "c", "text": "Aluminium chloride"}, {"id": "d", "text": "Sodium hydroxide"}, {"id": "e", "text": "Nitric acid"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Sorensen in 1909 suggested a convenient method of expressing the $\mathrm{H}_3 \mathrm{O}^{+}$ion concentration in terms of pH . Thus, to express the acidity or alkalinity of a solution, it is sufficient to express only the $\mathrm{H}_3 \mathrm{O}^{+}$ion concentration.',
    '[{"id": "a", "text": "What is the meaning of the symbol pH ?"}, {"id": "b", "text": "How is the pH of a solution of an acid influenced when it is diluted."}, {"id": "c", "text": "What is the nature of the salt if pH of its solution is greater than 7."}, {"id": "d", "text": "What is the nature of the solution if its pH is below 7."}, {"id": "e", "text": "What is the pH of water?"}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'Two statements (Assertion-A and Reason-R) are given. Select the correct answer to these questions from codes a, b, c and d as given below


\begin{enumerate}
\item Assertion: When an acid reacts with a metal, hydrogen gas is evolved and a corresponding salt is formed.
Reason: When a base reacts with a metal along with the evolution of hydrogen gas a salt is formed which has a negative ion composed of the metal and oxygen.
\item Assertion: When an acid reacts with a metal carbonate or metal hydrogen carbonate, it gives the corresponding salt, carbon dioxide gas and water.
Reason: Acidic and basic solutions in water conduct electricity because they produce hydrogen and hydroxide ions respectively.
\item Assertion: Mixing concentrated acids or bases with water is a highly exothermic process. Reason: Acid and Bases neutralise each other to form corresponding salts and water.
\end{enumerate}

% =============================================================
%Question End
% =============================================================',
    '[{"id": "a", "text": "Both A and R are true, and R is the correct explanation of the assertion."}, {"id": "b", "text": "Both A and R are true, but R is not the correct explanation of the assertion."}, {"id": "c", "text": "A is true but R is false."}, {"id": "d", "text": "A is false but R is true."}]'::jsonb,
    '',
    '',
    NULL,
    'medium',
    'Mixed',
    NULL,
    'cbse10_ch00_mixed3_q007',
    NULL,
    false
  )
ON CONFLICT (bank_item_id) DO NOTHING;

