-- CBSE 10 Science seed: ch07_ch08
-- Auto-generated from .tex files. All qc_done = false.
-- Total questions in this batch: 160

INSERT INTO cbse10_science_questions (
  type, prompt, options, correct_answer, explanation,
  domain, difficulty_tier, chapter, subtopic,
  bank_item_id, image_url, qc_done
)
VALUES
  (
    'mcq',
    'Which of the following statements is correct about receptors?',
    '[{"id": "a", "text": "Gustatory receptors detect taste while olfactory receptors detect smell"}, {"id": "b", "text": "Both gustatory and olfactory receptors detect smell"}, {"id": "c", "text": "Auditory receptors detect smell and olfactory receptors detect taste"}, {"id": "d", "text": "Olfactory receptors detect taste and gustatory receptors smell"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'Electrical impulse travels in a neuron from',
    '[{"id": "a", "text": "Dendrite $\\rightarrow$ axon $\\rightarrow$ axonal end $\\rightarrow$ cell body"}, {"id": "b", "text": "Cell body $\\rightarrow$ dendrite $\\rightarrow$ axon $\\rightarrow$ axonal end"}, {"id": "c", "text": "Dendrite $\\rightarrow$ cell body $\\rightarrow$ axon $\\rightarrow$ axonal end"}, {"id": "d", "text": "Axonal end $\\rightarrow$ axon $\\rightarrow$ cell body $\\rightarrow$ dendrite"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'In a synapse, chemical signal is transmitted from',
    '[{"id": "a", "text": "dendritic end of one neuron to axonal end of another neuron"}, {"id": "b", "text": "axon to cell body of the same neuron"}, {"id": "c", "text": "cell body to axonal end of the same neuron"}, {"id": "d", "text": "axonal end of one neuron to dendritic end of another neuron"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'In a neuron, conversion of electrical signal to a chemical signal occurs at/in',
    '[{"id": "a", "text": "cell body"}, {"id": "b", "text": "axonal end"}, {"id": "c", "text": "dendritic end"}, {"id": "d", "text": "axon"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Which is the correct sequence of the components of a reflex arc?',
    '[{"id": "a", "text": "Receptors $\\rightarrow$ Muscles $\\rightarrow$ Sensory neuron $\\rightarrow$ Motor neuron $\\rightarrow$ Spinal cord"}, {"id": "b", "text": "Receptors $\\rightarrow$ Motor neuron $\\rightarrow$ Spinal cord $\\rightarrow$ Sensory neuron $\\rightarrow$ Muscle"}, {"id": "c", "text": "Receptors $\\rightarrow$ Spinal cord $\\rightarrow$ Sensory neuron $\\rightarrow$ Motor neuron $\\rightarrow$ Muscle"}, {"id": "d", "text": "Receptors $\\rightarrow$ Sensory neuron $\\rightarrow$ Spinal cord $\\rightarrow$ Motor neuron $\\rightarrow$ Muscle"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements are true?
\begin{enumerate}[label=\roman*)]
    \item Sudden action in response to something in the environment is called reflex action
    \item Sensory neurons carry signals from spinal cord to muscles
    \item Motor neurons carry signals from receptors to spinal cord
    \item The path through which signals are transmitted from a receptor to a muscle or a gland is called reflex arc
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(i) and (iii)"}, {"id": "c", "text": "(i) and (iv)"}, {"id": "d", "text": "(i) , (ii) and (iii)"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements are true about the brain?
\begin{enumerate}[label=\roman*)]
    \item The main thinking part of brain is hind brain
    \item Centres of hearing, smell, memory, sight etc are located in fore brain.
    \item Involuntary actions like salivation, vomiting, blood pressure are controlled by the medulla in the hind brain
    \item Cerebellum does not control posture and balance of the body
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(i), (ii) and (iii)"}, {"id": "c", "text": "(ii) and (iii)"}, {"id": "d", "text": "(iii) and (iv)"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'Posture and balance of the body is controlled by',
    '[{"id": "a", "text": "cerebrum"}, {"id": "b", "text": "cerebellum"}, {"id": "c", "text": "medulla"}, {"id": "d", "text": "pons"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'Spinal cord originates from',
    '[{"id": "a", "text": "cerebrum"}, {"id": "b", "text": "medulla"}, {"id": "c", "text": "pons"}, {"id": "d", "text": "cerebellum"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'The movement of shoot towards light is',
    '[{"id": "a", "text": "geotropism"}, {"id": "b", "text": "hydrotropism"}, {"id": "c", "text": "chemotropism"}, {"id": "d", "text": "phototropism"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'The main function of abscisic acid in plants is to',
    '[{"id": "a", "text": "increase the length of cells"}, {"id": "b", "text": "promote cell division"}, {"id": "c", "text": "inhibit growth"}, {"id": "d", "text": "promote growth of stem"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is not associated with growth of plant?',
    '[{"id": "a", "text": "Auxin"}, {"id": "b", "text": "Gibberellins"}, {"id": "c", "text": "Cytokinins"}, {"id": "d", "text": "Abscisic acid"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Iodine is necessary for the synthesis of which hormone?',
    '[{"id": "a", "text": "Adrenaline"}, {"id": "b", "text": "Thyroxin"}, {"id": "c", "text": "Auxin"}, {"id": "d", "text": "Insulin"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the incorrect statement about insulin',
    '[{"id": "a", "text": "It is produced from pancreas"}, {"id": "b", "text": "It regulates growth and development of the body"}, {"id": "c", "text": "It regulates blood sugar level"}, {"id": "d", "text": "Insufficient secretion of insulin will cause diabetes"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Select the mis-matched pair',
    '[{"id": "a", "text": "Adrenaline : Pituitary gland"}, {"id": "b", "text": "Testosterone : Testes"}, {"id": "c", "text": "Estrogen : Ovary"}, {"id": "d", "text": "Thyroxin : Thyroid gland"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'The shape of guard cells changes due to change in the',
    '[{"id": "a", "text": "protein composition of cells"}, {"id": "b", "text": "temperature of cells"}, {"id": "c", "text": "amount of water in cells"}, {"id": "d", "text": "position of nucleus in the cells"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'The growth of tendril in pea plants is due to',
    '[{"id": "a", "text": "effect of light"}, {"id": "b", "text": "effect of gravity"}, {"id": "c", "text": "rapid cell divisions in tendrillar cells that are away from the support"}, {"id": "d", "text": "rapid cell divisions in tendrillar cells in contact with the support"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'The growth of pollen tubes towards ovules is due to',
    '[{"id": "a", "text": "hydrotropism"}, {"id": "b", "text": "chemotropism"}, {"id": "c", "text": "geotropism"}, {"id": "d", "text": "phototropism"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'The movement of sunflower in accordance with the path of sun is due to',
    '[{"id": "a", "text": "phototropism"}, {"id": "b", "text": "geotropism"}, {"id": "c", "text": "chemotropism"}, {"id": "d", "text": "hydrotropism"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q019',
    NULL,
    false
  ),
  (
    'mcq',
    'The substance that triggers the fall of mature leaves and fruits from plants is due to',
    '[{"id": "a", "text": "auxin"}, {"id": "b", "text": "gibberellin"}, {"id": "c", "text": "abscisic acid"}, {"id": "d", "text": "cytokinin"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements about transmission of nerve impulse is incorrect?',
    '[{"id": "a", "text": "Nerve impulse travels from dendritic end towards axonal end"}, {"id": "b", "text": "At the dendritic end electrical impulses bring about the release of some chemicals which generate an electrical impulse at the axonal end of another neuron"}, {"id": "c", "text": "The chemicals released from the axonal end of one neuron cross the synapse and generate a similar electrical impulse in a dendrite of another neuron"}, {"id": "d", "text": "A neuron transmits electrical impulses not only to another neuron but also to muscle and gland cells"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q021',
    NULL,
    false
  ),
  (
    'mcq',
    'Involuntary actions in the body are controlled by',
    '[{"id": "a", "text": "medulla in fore brain"}, {"id": "b", "text": "medulla in mid brain"}, {"id": "c", "text": "medulla in hind brain"}, {"id": "d", "text": "medulla in spinal cord"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is not an involuntary action?',
    '[{"id": "a", "text": "Vomiting"}, {"id": "b", "text": "Salivation"}, {"id": "c", "text": "Heart beat"}, {"id": "d", "text": "Chewing"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'When a person is suffering from severe cold, he or she cannot',
    '[{"id": "a", "text": "differentiate the taste of an apple from that of an ice cream"}, {"id": "b", "text": "differentiate the smell of a perfume from that of an agarbatti"}, {"id": "c", "text": "differentiate red light from green light"}, {"id": "d", "text": "differentiate a hot object from a cold object"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q024',
    NULL,
    false
  ),
  (
    'mcq',
    'What is the correct direction of flow of electrical impulses?',
    '[{"id": "a", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.5\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_4.PNG}\n    \\end{center}\n% Diagram Ends"}, {"id": "b", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.5\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_1.png}\n    \\end{center}\n% Diagram Ends"}, {"id": "c", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.5\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_2.PNG}\n    \\end{center}\n% Diagram Ends"}, {"id": "d", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.5\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_3.PNG}\n    \\end{center}\n% Diagram Ends"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q025',
    'control-coordination/cbse10_ch07_exemplar_q025.png',
    false
  ),
  (
    'mcq',
    'Which statement is not true about thyroxin?',
    '[{"id": "a", "text": "Iron is essential for the synthesis of thyroxin"}, {"id": "b", "text": "It regulates carbohydrates, protein and fat metabolism in the body"}, {"id": "c", "text": "Thyroid gland requires iodine to synthesise thyroxin"}, {"id": "d", "text": "Thyroxin is also called thyroid hormone"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q026',
    NULL,
    false
  ),
  (
    'mcq',
    'Dwarfism results due to',
    '[{"id": "a", "text": "Excess secretion of thyroxin"}, {"id": "b", "text": "Less secretion of growth hormone"}, {"id": "c", "text": "Less secretion of adrenaline"}, {"id": "d", "text": "Excess secretion of growth hormone"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q027',
    NULL,
    false
  ),
  (
    'mcq',
    'Dramatic changes of body features associated with puberty are mainly because of secretion of',
    '[{"id": "a", "text": "oestrogen from testes and testosterone from ovary"}, {"id": "b", "text": "estrogen from adrenal gland and testosterone from pituitary gland"}, {"id": "c", "text": "testosterone from testes and estrogen from ovary"}, {"id": "d", "text": "testosterone from thyroid gland and estrogen from pituitary gland"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q028',
    NULL,
    false
  ),
  (
    'mcq',
    'A doctor advised a person to take an injection of insulin because',
    '[{"id": "a", "text": "his blood pressure was low"}, {"id": "b", "text": "his heart was beating slowly"}, {"id": "c", "text": "he was suffering from goitre"}, {"id": "d", "text": "his sugar level in blood was high"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q029',
    NULL,
    false
  ),
  (
    'mcq',
    'The hormone which increases the fertility in males is called',
    '[{"id": "a", "text": "oestrogen"}, {"id": "b", "text": "testosterone"}, {"id": "c", "text": "insulin"}, {"id": "d", "text": "growth hormone"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q030',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following endocrine glands is unpaired?',
    '[{"id": "a", "text": "Adrenal"}, {"id": "b", "text": "Testes"}, {"id": "c", "text": "Pituitary"}, {"id": "d", "text": "Ovary"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q031',
    NULL,
    false
  ),
  (
    'mcq',
    'Junction between two neurons is called',
    '[{"id": "a", "text": "cell junction"}, {"id": "b", "text": "neuro muscular junction"}, {"id": "c", "text": "neural joint"}, {"id": "d", "text": "synapse"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q032',
    NULL,
    false
  ),
  (
    'mcq',
    'In humans, the life processes are controlled and regulated by',
    '[{"id": "a", "text": "reproductive and endocrine systems"}, {"id": "b", "text": "respiratory and nervous systems"}, {"id": "c", "text": "endocrine and digestive systems"}, {"id": "d", "text": "nervous and endocrine systems"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q033',
    NULL,
    false
  ),
  (
    'spr',
    'Label the parts (a), (b), (c) and (d) and show the direction of flow of electrical signals in Figure.
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_5.png}
    \end{center}
% Diagram Ends',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q034',
    'control-coordination/cbse10_ch07_exemplar_q034.png',
    false
  ),
  (
    'mcq',
    'Name the plant hormones responsible for the following',
    '[{"id": "a", "text": "elongation of cells"}, {"id": "b", "text": "growth of stem"}, {"id": "c", "text": "promotion of cell division"}, {"id": "d", "text": "falling of senescent leaves."}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q035',
    NULL,
    false
  ),
  (
    'spr',
    'Label the endocrine glands in Figure.
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_10.PNG}
    \end{center}
% Diagram Ends',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q036',
    'control-coordination/cbse10_ch07_exemplar_q036.png',
    false
  ),
  (
    'mcq',
    'In Figure (a), (b) and (c), which appears more accurate and why?',
    '[{"id": "a", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.3\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_6.PNG}\n    \\end{center}\n% Diagram Ends"}, {"id": "b", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.3\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_7.PNG}\n    \\end{center}\n% Diagram Ends"}, {"id": "c", "text": "% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.3\\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_8.PNG}\n    \\end{center}\n% Diagram Ends"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q037',
    'control-coordination/cbse10_ch07_exemplar_q037.png',
    false
  ),
  (
    'spr',
    'Label the parts of a neuron in Figure.
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{07.Class 10_NCERT Exempler_Control and Coordination_9.PNG}
    \end{center}
% Diagram Ends',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q038',
    'control-coordination/cbse10_ch07_exemplar_q038.png',
    false
  ),
  (
    'spr',
    'Match the terms of Column (A) with those of Column (B)

\begin{tabular}{|l|l|}
\hline
Column (A) & Column (B) \\
\hline
(a) Olfactory receptors & (i) Tongue \\
(b) Thermo receptors (temperature receptors) & (ii) Eye \\
(c) Gustatoreceptors & (iii) Nose \\
(d) Photoreceptors & (iv) Skin \\
\hline
\end{tabular}',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q039',
    NULL,
    false
  ),
  (
    'spr',
    'What is a tropic movement? Explain with an example.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q040',
    NULL,
    false
  ),
  (
    'spr',
    'What will happen if intake of iodine in our diet is low?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q041',
    NULL,
    false
  ),
  (
    'spr',
    'What happens at the synapse between two neurons?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q042',
    NULL,
    false
  ),
  (
    'mcq',
    'Answer the following :',
    '[{"id": "a", "text": "Which hormone is responsible for the changes noticed in females at puberty?"}, {"id": "b", "text": "Dwarfism results due to deficiency of which hormone?"}, {"id": "c", "text": "Blood sugar level rises due to deficiency of which hormone?"}, {"id": "d", "text": "Iodine is necessary for the synthesis of which hormone?"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q043',
    NULL,
    false
  ),
  (
    'mcq',
    'Answer the following :',
    '[{"id": "a", "text": "Name the endocrine gland associated with brain?"}, {"id": "b", "text": "Which gland secretes digestive enzymes as well as hormones?"}, {"id": "c", "text": "Name the endocrine gland associated with kidneys?"}, {"id": "d", "text": "Which endocrine gland is present in males but not in females?"}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q044',
    NULL,
    false
  ),
  (
    'spr',
    'Draw the structure of a neuron and explain its function.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q045',
    NULL,
    false
  ),
  (
    'spr',
    'What are the major parts of the brain? Mention the functions of different parts.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q046',
    NULL,
    false
  ),
  (
    'spr',
    'What constitutes the central and peripheral nervous systems? How are the components of central nervous system protected?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q047',
    NULL,
    false
  ),
  (
    'mcq',
    'Mention one function for each of these hormones :',
    '[{"id": "a", "text": "Thyroxin"}, {"id": "b", "text": "Insulin"}, {"id": "c", "text": "Adrenaline"}, {"id": "d", "text": "Growth hormone"}, {"id": "e", "text": "Testosterone."}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q048',
    NULL,
    false
  ),
  (
    'spr',
    'Name various plant hormones. Also give their physiological effects on plant growth and development.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q049',
    NULL,
    false
  ),
  (
    'spr',
    'What are reflex actions? Give two examples. Explain a reflex arc.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q050',
    NULL,
    false
  ),
  (
    'spr',
    '"Nervous and hormonal systems together perform the function of control and coordination in human beings." Justify the statement.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q051',
    NULL,
    false
  ),
  (
    'spr',
    'How does chemical coordination take place in animals?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q052',
    NULL,
    false
  ),
  (
    'spr',
    'Why is the flow of signals in a synapse from axonal end of one neuron to dendritic end of another neuron but not the reverse?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_exemplar_q053',
    NULL,
    false
  ),
  (
    'spr',
    'What is the difference between a reflex action and walking?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What happens at the synapse between two neurons?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'Which part of the brain maintains posture and equilibrium of the body?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'How do we detect the smell of an agarbatti (incense stick)?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'What is the role of the brain in reflex action?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'What are plant hormones?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'How is the movement of leaves of the sensitive plant different from the movement of a shoot towards light?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q007',
    NULL,
    false
  ),
  (
    'spr',
    'Give an example of a plant hormone that promotes growth.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q008',
    NULL,
    false
  ),
  (
    'spr',
    'How do auxins promote the growth of a tendril around a support?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q009',
    NULL,
    false
  ),
  (
    'spr',
    'Design an experiment to demonstrate hydrotropism.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q010',
    NULL,
    false
  ),
  (
    'spr',
    'How does chemieal coordination take place in animals?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'Why is the use of iodised salt advisable?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q012',
    NULL,
    false
  ),
  (
    'spr',
    'How does our body respond when adrenaline is secreted into the blood?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q013',
    NULL,
    false
  ),
  (
    'spr',
    'Why are some patients of diabetes treated by giving injections of insulin?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is a plant hormone?',
    '[{"id": "a", "text": "Insulin"}, {"id": "b", "text": "Thyroxin"}, {"id": "c", "text": "Oestrogen"}, {"id": "d", "text": "Cytokinin."}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'The gap between two neurons is called a',
    '[{"id": "a", "text": "dendrite."}, {"id": "b", "text": "synapse."}, {"id": "c", "text": "axon."}, {"id": "d", "text": "impulse."}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'The brain is responsible for',
    '[{"id": "a", "text": "thinking."}, {"id": "b", "text": "regulating the heart beat."}, {"id": "c", "text": "balancing the body."}, {"id": "d", "text": "all of the above."}]'::jsonb,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q017',
    NULL,
    false
  ),
  (
    'spr',
    'What is the function of receptors in our body? Think of situations where receptors do not work properly. What problems are likely to arise?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q018',
    NULL,
    false
  ),
  (
    'spr',
    'Draw the structure of a neuron and explain its function.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q019',
    NULL,
    false
  ),
  (
    'spr',
    'How does phototropism occur in plants?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q020',
    NULL,
    false
  ),
  (
    'spr',
    'Which signals will get disrupted in case of a spinal cord injury?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q021',
    NULL,
    false
  ),
  (
    'spr',
    'How does chemical coordination occur in plants?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q022',
    NULL,
    false
  ),
  (
    'spr',
    'What is the need for a system of control and coordination in an organism?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q023',
    NULL,
    false
  ),
  (
    'spr',
    'How are involuntary actions and reflex actions different from each other?',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q024',
    NULL,
    false
  ),
  (
    'spr',
    'Compare and contrast nervous and hormonal mechanisms for control and coordination in animals.',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q025',
    NULL,
    false
  ),
  (
    'spr',
    'What is the difference between the manner in which movement takes place in a sensitive plant and the movement in our legs?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'control-coordination',
    'medium',
    'Control and Coordination',
    NULL,
    'cbse10_ch07_ncert_q026',
    NULL,
    false
  ),
  (
    'mcq',
    'In the list of organisms given below, those that reproduce by the asexual method are
\begin{multicols}{2}
\begin{enumerate}[label=\roman*)]
    \item banana
    \item $\operatorname{dog}$
    \item yeast
    \item Amoeba
\end{enumerate}
\end{multicols}',
    '[{"id": "a", "text": "(ii) and (iv)"}, {"id": "b", "text": "(i), (iii) and (iv)"}, {"id": "c", "text": "(i) and (iv)"}, {"id": "d", "text": "(ii), (iii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'In a flower, the parts that produce male and female gametes (germ cells) are',
    '[{"id": "a", "text": "stamen and anther"}, {"id": "b", "text": "filament and stigma"}, {"id": "c", "text": "anther and ovary"}, {"id": "d", "text": "stamen and style"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is the correct sequence of events of sexual reproduction in a flower?',
    '[{"id": "a", "text": "pollination, fertilisation, seedling, embryo"}, {"id": "b", "text": "seedling, embryo, fertilisation, pollination"}, {"id": "c", "text": "pollination, fertilisation, embryo, seedling"}, {"id": "d", "text": "embryo, seedling, pollination, fertilisation"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'Offspring formed by asexual method of reproduction have greater similarity among themselves because
\begin{enumerate}[label=\roman*)]
    \item asexual reproduction involves only one parent
    \item asexual reproduction does not involve gametes
    \item asexual reproduction occurs before sexual reproduction
    \item asexual reproduction occurs after sexual reproduction
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(i) and (iii)"}, {"id": "c", "text": "(ii) and (iv)"}, {"id": "d", "text": "(iii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Characters transmitted from parents to offspring are present in',
    '[{"id": "a", "text": "cytoplasm"}, {"id": "b", "text": "ribosome"}, {"id": "c", "text": "golgi bodies"}, {"id": "d", "text": "genes"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Characters that are transmitted from parents to offspring during reproduction show',
    '[{"id": "a", "text": "only similarities with parents"}, {"id": "b", "text": "only variations with parents"}, {"id": "c", "text": "both similarities and variations with parents"}, {"id": "d", "text": "neither similarities nor variations"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'A feature of reproduction that is common to Amoeba, Spirogyra and Yeast is that',
    '[{"id": "a", "text": "they reproduce asexually"}, {"id": "b", "text": "they are all unicellular"}, {"id": "c", "text": "they reproduce only sexually"}, {"id": "d", "text": "they are all multicellular"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'In Spirogyra, asexual reproduction takes place by',
    '[{"id": "a", "text": "breaking up of filaments into smaller bits"}, {"id": "b", "text": "division of a cell into two cells"}, {"id": "c", "text": "division of a cell into many cells"}, {"id": "d", "text": "formation of young cells from older cells."}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'The ability of a cell to divide into several cells during reproduction in Plasmodium is called',
    '[{"id": "a", "text": "budding"}, {"id": "b", "text": "reduction division"}, {"id": "c", "text": "binary fission"}, {"id": "d", "text": "multiple fission"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'The correct sequence of reproductive stages seen in flowering plants is',
    '[{"id": "a", "text": "gametes, zygote, embryo, seedling"}, {"id": "b", "text": "zygote, gametes, embryo, seedling"}, {"id": "c", "text": "seedling, embryo, zygote, gametes"}, {"id": "d", "text": "gametes, embryo, zygote, seedling"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'The number of chromosomes in parents and offsprings of a particular species remains constant due to',
    '[{"id": "a", "text": "doubling of chromosomes after zygote formation"}, {"id": "b", "text": "halving of chromosomes during gamete formation"}, {"id": "c", "text": "doubling of chromosomes after gamete formation"}, {"id": "d", "text": "halving of chromosomes after gamete formation"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'In Rhizopus, tubular thread-like structures bearing sporangia at their tips are called',
    '[{"id": "a", "text": "filaments"}, {"id": "b", "text": "hyphae"}, {"id": "c", "text": "rhizoids"}, {"id": "d", "text": "root"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Vegetative propagation refers to formation of new plants from',
    '[{"id": "a", "text": "stem, roots and flowers"}, {"id": "b", "text": "stem, roots and leaves"}, {"id": "c", "text": "stem, flowers and fruits"}, {"id": "d", "text": "stem, leaves and flowers"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Factors responsible for the rapid spread of bread mould on slices of bread are
\begin{enumerate}[label=\roman*)]
    \item large number of spores
    \item availability of moisture and nutrients in bread
    \item presence of tubular branched hyphae
    \item formation of round shaped sporangia
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iii)"}, {"id": "b", "text": "(ii) and iv)"}, {"id": "c", "text": "(i) and (ii)"}, {"id": "d", "text": "(iii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Length of pollen tube depends on the distance between',
    '[{"id": "a", "text": "pollen grain and upper surface of stigma"}, {"id": "b", "text": "pollen grain on upper surface of stigma and ovule"}, {"id": "c", "text": "pollen grain in anther and upper surface of stigma"}, {"id": "d", "text": "upper surface of stigma and lower part of style"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements are true for flowers?
\begin{enumerate}[label=\roman*)]
    \item Flowers are always bisexual
    \item They are the sexual reproductive organs
    \item They are produced in all groups of plants
    \item After fertilisation they give rise to fruits
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(i) and (iii)"}, {"id": "d", "text": "(ii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'Which among the following statements are true for unisexual flowers?
\begin{enumerate}[label=\roman*)]
    \item They possess both stamen and pistil
    \item They possess either stamen or pistil
    \item They exhibit cross pollination
    \item Unisexual flowers possessing only stamens cannot produce fruits
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(ii), (iii) and (iv)"}, {"id": "c", "text": "(iii) and (iv)"}, {"id": "d", "text": "(i), (iii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'Which among the following statements are true for sexual reproduction in flowering plants?
\begin{enumerate}[label=\roman*)]
    \item It requires two types of gametes
    \item Fertilisation is a compulsory event
    \item It always results in formation of zygote
    \item Offspring formed are clones
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(i), (ii) and (iv)"}, {"id": "c", "text": "(i), (ii) and (iii)"}, {"id": "d", "text": "(i), (ii) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'In Figure, the parts $\mathrm{A}, \mathrm{B}$ and $\mathrm{C}$ are sequentially
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{08.Class 10_NCERT Exempler_How do Organisms Reproduce_1.jpg}
    \end{center}
% Diagram Ends',
    '[{"id": "a", "text": "cotyledon, plumule and radicle"}, {"id": "b", "text": "plumule, radicle and cotyledon"}, {"id": "c", "text": "plumule, cotyledon and radicle"}, {"id": "d", "text": "radicle, cotyledon and plumule"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q019',
    'reproduction/cbse10_ch08_exemplar_q019.jpg',
    false
  ),
  (
    'mcq',
    'Offspring formed as a result of sexual reproduction exhibit more variations because',
    '[{"id": "a", "text": "sexual reproduction is a lengthy process"}, {"id": "b", "text": "genetic material comes from two parents of the same species"}, {"id": "c", "text": "genetic material comes from two parents of different species"}, {"id": "d", "text": "genetic material comes from many parents"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'eproduction is essential for living organisms in order to',
    '[{"id": "a", "text": "keep the individual organism alive"}, {"id": "b", "text": "fulfill their energy requirement"}, {"id": "c", "text": "maintain growth"}, {"id": "d", "text": "continue the species generation after generation"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q021',
    NULL,
    false
  ),
  (
    'mcq',
    'During adolescence, several changes occur in the human body. Mark one change associated with sexual maturation in boys',
    '[{"id": "a", "text": "loss of milk teeth"}, {"id": "b", "text": "increase in height"}, {"id": "c", "text": "cracking of voice"}, {"id": "d", "text": "weight gain"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'In human females, an event that reflects onset of reproductive phase is',
    '[{"id": "a", "text": "growth of body"}, {"id": "b", "text": "changes in hair pattern"}, {"id": "c", "text": "change in voice"}, {"id": "d", "text": "menstruation"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'In human males, the testes lie in the scrotum, because it helps in the',
    '[{"id": "a", "text": "process of mating"}, {"id": "b", "text": "formation of sperm"}, {"id": "c", "text": "easy transfer of gametes"}, {"id": "d", "text": "all the above"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q024',
    NULL,
    false
  ),
  (
    'mcq',
    'Which among the following is not the function of testes at puberty?
\begin{enumerate}[label=\roman*)]
    \item formation of germ cells
    \item secretion of testosterone
    \item development of placenta
    \item secretion of estrogen
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(iii) and (iv)"}, {"id": "d", "text": "(i) and (iv)"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q025',
    NULL,
    false
  ),
  (
    'mcq',
    'The correct sequence of organs in the male reproductive system for transport of sperms is',
    '[{"id": "a", "text": "testis $\\rightarrow$ vasdeferens $\\rightarrow$ urethra"}, {"id": "b", "text": "testis $\\rightarrow$ ureter $\\rightarrow$ urethra"}, {"id": "c", "text": "testis $\\rightarrow$ urethra $\\rightarrow$ ureter"}, {"id": "d", "text": "testis $\\rightarrow$ vasdeferens $\\rightarrow$ ureter"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q026',
    NULL,
    false
  ),
  (
    'mcq',
    'Which among the following diseases is not sexually transmitted?',
    '[{"id": "a", "text": "Syphillis"}, {"id": "b", "text": "Hepatitis"}, {"id": "c", "text": "HIV - AIDS"}, {"id": "d", "text": "Gonorrhoea"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q027',
    NULL,
    false
  ),
  (
    'spr',
    'In a bisexual flower inspite of the young stamens being removed artificially, the flower produces fruit. Provide a suitable explanation for the above situation.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q028',
    NULL,
    false
  ),
  (
    'spr',
    'Can you consider cell division as a type of reproduction in unicellular organism? Give one reason.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q029',
    NULL,
    false
  ),
  (
    'spr',
    'What is a clone? Why do offsprings formed by asexual reproduction exhibit remarkable similarity?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q030',
    NULL,
    false
  ),
  (
    'spr',
    'Explain how, offspring and parents of organisms reproducing sexually have the same number of chromosomes?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q031',
    NULL,
    false
  ),
  (
    'spr',
    'Colonies of yeast fail to multiply in water, but multiply in sugar solution. Give one reason for this.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q032',
    NULL,
    false
  ),
  (
    'spr',
    'Why does bread mould grow profusely on a moist slice of bread rather than on a dry slice of bread?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q033',
    NULL,
    false
  ),
  (
    'spr',
    'Give two reasons for the appearance of variations among the progeny formed by sexual reproduction.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q034',
    NULL,
    false
  ),
  (
    'spr',
    'Would a Planaria cut vertically into two halves regenerate into two individuals? Complete Figure $\quad \mathrm{D}$ and $\mathrm{E}$ by indicating the regenerated regions.
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{08.Class 10_NCERT Exempler_How do Organisms Reproduce_2.png}
    \end{center}
% Diagram Ends',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q035',
    'reproduction/cbse10_ch08_exemplar_q035.png',
    false
  ),
  (
    'mcq',
    'From the internet, gather information about the chromosome numbers of five animals and five plants. Correlate the number with the size of organism and answer the following questions.',
    '[{"id": "a", "text": "Do larger organisms have more number of chromosomes/cells?"}, {"id": "b", "text": "Can organism with fewer chromosomes reproduce more easily than organisms with more number of chromosomes?"}, {"id": "c", "text": "More the number of chromosomes/cells greater is the DNA content. Justify."}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q036',
    NULL,
    false
  ),
  (
    'spr',
    'In tobacco plant, the male gametes have twenty four chromosomes.

What is the number of chromosomes in the female gamete?

What is the number of chromosomes in the zygote?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q037',
    NULL,
    false
  ),
  (
    'spr',
    'Why cannot fertilisation take place in flowers if pollination does not occur?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q038',
    NULL,
    false
  ),
  (
    'spr',
    'Is the chromosome number of zygote, embryonal cells and adult of a particular organism always constant? How is the constancy maintained in these three stages?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q039',
    NULL,
    false
  ),
  (
    'spr',
    'Where is the zygote located in the flower after fertilization?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q040',
    NULL,
    false
  ),
  (
    'spr',
    'Reproduction is linked to stability of population of a species. Justify the statement.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q041',
    NULL,
    false
  ),
  (
    'spr',
    'How are general growth and sexual maturation different from each other?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q042',
    NULL,
    false
  ),
  (
    'spr',
    'Trace the path of sperm during ejaculation and mention the gland and their functions associated with the male reproductive system.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q043',
    NULL,
    false
  ),
  (
    'spr',
    'What changes are observed in the uterus if fertilisation does not occur?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q044',
    NULL,
    false
  ),
  (
    'spr',
    'What changes are observed in the uterus subsequent to implantation of young embryo?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q045',
    NULL,
    false
  ),
  (
    'spr',
    'What are the benefits of using mechanical barriers during sexual act?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q046',
    NULL,
    false
  ),
  (
    'mcq',
    'In the given Figure label the parts and mention their functions
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.4\textwidth]{08.Class 10_NCERT Exempler_How do Organisms Reproduce_3.jpg}
    \end{center}
% Diagram Ends',
    '[{"id": "a", "text": "Production of egg"}, {"id": "b", "text": "Site of fertilisation"}, {"id": "c", "text": "Site of implantation"}, {"id": "d", "text": "Entry of the sperms"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q047',
    'reproduction/cbse10_ch08_exemplar_q047.jpg',
    false
  ),
  (
    'spr',
    'What would be the ratio of chromosome number between an egg and its zygote? How is the sperm genetically different from the egg?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q048',
    NULL,
    false
  ),
  (
    'spr',
    'Why are budding, fragmentation and regeneration all considered as asexual types of reproduction? With neat diagrams explain the process of regeneration in Planaria.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q049',
    NULL,
    false
  ),
  (
    'spr',
    'Write two points of difference between asexual and sexual types of reproduction. Describe why variations are observed in the offspring formed by sexual reproduction.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q050',
    NULL,
    false
  ),
  (
    'spr',
    'Distinguish between pollination and fertilisation. Mention the site and product of fertilisation in a flower.

Draw a neat, labelled diagram of a pistil showing pollen tube growth and its entry into the ovule.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q051',
    NULL,
    false
  ),
  (
    'spr',
    'Distinguish between a gamete and zygote. Explain their roles in sexual reproduction.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q052',
    NULL,
    false
  ),
  (
    'spr',
    'Draw the diagram of a flower and label the four whorls. Write the names of gamete producing organs in the flower.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q053',
    NULL,
    false
  ),
  (
    'spr',
    'What is placenta? Mention its role during pregnancy?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q054',
    NULL,
    false
  ),
  (
    'spr',
    'What are various ways to avoid pregnancy? Elaborate any one method.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q055',
    NULL,
    false
  ),
  (
    'spr',
    'How does fertilisation take place? Fertilisation occurs once in a month. Comment.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q056',
    NULL,
    false
  ),
  (
    'spr',
    'Reproduction is essentially a phenomenon that is not for survival of an individual but for the stability of a species. Justify.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q057',
    NULL,
    false
  ),
  (
    'spr',
    'Describe sexually transmitted diseases and mention the ways to prevent them.


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_exemplar_q058',
    NULL,
    false
  ),
  (
    'spr',
    'What is the importance of DNA copying in reproduction?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'Why is variation beneficial to the species but not necessarily for the individual?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'How does binary fission differ from multiple fission?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'How will an organism be benefited if it reproduces through spores?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'Can you think of reasons why more complex organisms cannot give rise to new individuals through regeneration?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'Why is vegetative propagation practised for growing some types of plants?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'Why is DNA copying an essential part of the process of reproduction?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q007',
    NULL,
    false
  ),
  (
    'spr',
    'How is the process of pollination different from fertilisation?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q008',
    NULL,
    false
  ),
  (
    'spr',
    'What is the role of the seminal vesicles and the prostate gland?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q009',
    NULL,
    false
  ),
  (
    'spr',
    'What are the changes seen in girls at the time of puberty?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q010',
    NULL,
    false
  ),
  (
    'spr',
    'How does the embryo get nourishment inside the mother''s body?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'If a woman is using a copper- $\mathrm{T}$, will it help in protecting her from sexually transmitted diseases?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Asexual reproduction takes place through budding in',
    '[{"id": "a", "text": "amoeba."}, {"id": "b", "text": "yeast."}, {"id": "c", "text": "plasmodium."}, {"id": "d", "text": "leishmania."}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is not a part of the female reproductive system in human beings?',
    '[{"id": "a", "text": "Ovary"}, {"id": "b", "text": "Uterus"}, {"id": "c", "text": "Vas deferens"}, {"id": "d", "text": "Fallopian tube"}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'The anther contains',
    '[{"id": "a", "text": "sepals."}, {"id": "b", "text": "ovules."}, {"id": "c", "text": "pistil."}, {"id": "d", "text": "pollen grains."}]'::jsonb,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q015',
    NULL,
    false
  ),
  (
    'spr',
    'What are the advantages of sexual reproduction over asexual reproduction?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q016',
    NULL,
    false
  ),
  (
    'spr',
    'What are the functions performed by the testis in human beings?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q017',
    NULL,
    false
  ),
  (
    'spr',
    'Why does menstruation occur?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q018',
    NULL,
    false
  ),
  (
    'spr',
    'Draw a labelled diagram of the longitudinal section of a flower.',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q019',
    NULL,
    false
  ),
  (
    'spr',
    'What are the different methods of contraception?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q020',
    NULL,
    false
  ),
  (
    'spr',
    'How are the modes for reproduction different in unicellular and multicellular organisms?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q021',
    NULL,
    false
  ),
  (
    'spr',
    'How does reproduction help in providing stability to populations of species?',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q022',
    NULL,
    false
  ),
  (
    'spr',
    'What could be the reasons for adopting contraceptive methods?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'reproduction',
    'medium',
    'How do Organisms Reproduce',
    NULL,
    'cbse10_ch08_ncert_q023',
    NULL,
    false
  )
ON CONFLICT (bank_item_id) DO NOTHING;

