-- CBSE 10 Science seed: ch05_ch06
-- Auto-generated from .tex files. All qc_done = false.
-- Total questions in this batch: 213

INSERT INTO cbse10_science_questions (
  type, prompt, options, correct_answer, explanation,
  domain, difficulty_tier, chapter, subtopic,
  bank_item_id, image_url, qc_done
)
VALUES
  (
    'mcq',
    'Upto which element, the Law of Octaves was found to be applicable',
    '[{"id": "a", "text": "Oxygen"}, {"id": "b", "text": "Calcium"}, {"id": "c", "text": "Cobalt"}, {"id": "d", "text": "Potassium"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'According to Mendeléev''s Periodic Law, the elements were arranged in the periodic table in the order of',
    '[{"id": "a", "text": "increasing atomic number"}, {"id": "b", "text": "decreasing atomic number"}, {"id": "c", "text": "increasing atomic masses"}, {"id": "d", "text": "decreasing atomic masses"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'In Mendeléev ''s Periodic Table, gaps were left for the elements to be discovered later. Which of the following elements found a place in the perioidc table later',
    '[{"id": "a", "text": "Germanium"}, {"id": "b", "text": "Chlorine"}, {"id": "c", "text": "Oxygen"}, {"id": "d", "text": "Silicon"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statement (s) about the Modern Periodic Table are incorrect
\begin{enumerate}[label=\roman*)]
    \item The elements in the Modern Periodic Table are arranged on the basis of their decreasing atomic number
    \item The elements in the Modern Periodic Table are arranged on the basis of their increasing atomic masses
    \item Isotopes are placed in adjoining group (s) in the Periodic Table
    \item The elements in the Modern Periodic Table are arranged on the basis of their increasing atomic number
\end{enumerate}',
    '[{"id": "a", "text": "(i) only"}, {"id": "b", "text": "(i), (ii) and (iii)"}, {"id": "c", "text": "(i), (ii) and (iv)"}, {"id": "d", "text": "(iv) only"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements about the Modern Periodic Table is correct:',
    '[{"id": "a", "text": "It has 18 horizontal rows known as Periods"}, {"id": "b", "text": "It has 7 vertical columns known as Periods"}, {"id": "c", "text": "It has 18 vertical columns known as Groups"}, {"id": "d", "text": "It has 7 horizontal rows known as Groups"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the given elements $\mathrm{A}, \mathrm{B}, \mathrm{C}, \mathrm{D}$ and $\mathrm{E}$ with atomic number $2,3,7,10$ and 30 respectively belong to the same period?',
    '[{"id": "a", "text": "A, B, C"}, {"id": "b", "text": "B, C, D"}, {"id": "c", "text": "A, D, E"}, {"id": "d", "text": "$\\mathrm{B}, \\mathrm{D}, \\mathrm{E}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'The elements $\mathrm{A}, \mathrm{B}, \mathrm{C}, \mathrm{D}$ and $\mathrm{E}$ have atomic number $9,11,17,12$ and 13 respectively. Which pair of elements belong to the same group?',
    '[{"id": "a", "text": "A and B"}, {"id": "b", "text": "$\\mathrm{B}$ and $\\mathrm{D}$"}, {"id": "c", "text": "$\\mathrm{A}$ and $\\mathrm{C}$"}, {"id": "d", "text": "$\\mathrm{D}$ and $\\mathrm{E}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'Where would you locate the element with electronic configuration 2,8 in the Modern Periodic Table?',
    '[{"id": "a", "text": "Group 8"}, {"id": "b", "text": "Group 2"}, {"id": "c", "text": "Group 18"}, {"id": "d", "text": "Group 10"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'An element which is an essential constituent of all organic compounds belongs to',
    '[{"id": "a", "text": "group 1"}, {"id": "b", "text": "group 14"}, {"id": "c", "text": "group 15"}, {"id": "d", "text": "group 16"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is the outermost shell for elements of period 2 ?',
    '[{"id": "a", "text": "K shell"}, {"id": "b", "text": "L shell"}, {"id": "c", "text": "M shell"}, {"id": "d", "text": "$\\mathrm{N}$ shell"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'Which one of the following elements exhibit maximum number of valence electrons?',
    '[{"id": "a", "text": "$\\mathrm{Na}$"}, {"id": "b", "text": "Al"}, {"id": "c", "text": "$\\mathrm{Si}$"}, {"id": "d", "text": "$\\mathrm{P}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following gives the correct increasing order of the atomic radii of $\mathrm{O}, \mathrm{F}$ and $\mathrm{N}$ ?',
    '[{"id": "a", "text": "$\\mathrm{O}, \\mathrm{F}, \\mathrm{N}$"}, {"id": "b", "text": "$\\mathrm{N}, \\mathrm{F}, \\mathrm{O}$"}, {"id": "c", "text": "O, N, F"}, {"id": "d", "text": "$\\mathrm{F}, \\mathrm{O}, \\mathrm{N}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Which among the following elements has the largest atomic radii?',
    '[{"id": "a", "text": "$\\mathrm{Na}$"}, {"id": "b", "text": "$\\mathrm{Mg}$"}, {"id": "c", "text": "$\\mathrm{K}$"}, {"id": "d", "text": "$\\mathrm{Ca}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following elements would lose an electron easily?',
    '[{"id": "a", "text": "$\\mathrm{Mg}$"}, {"id": "b", "text": "$\\mathrm{Na}$"}, {"id": "c", "text": "$\\mathrm{K}$"}, {"id": "d", "text": "$\\mathrm{Ca}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following elements does not lose an electron easily?',
    '[{"id": "a", "text": "$\\mathrm{Na}$"}, {"id": "b", "text": "$\\mathrm{F}$"}, {"id": "c", "text": "$\\mathrm{Mg}$"}, {"id": "d", "text": "$\\mathrm{Al}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following are the characteristics of isotopes of an element?
\begin{enumerate}[label=\roman*)]
    \item Isotopes of an element have same atomic masses
    \item Isotopes of an element have same atomic number
    \item Isotopes of an element show same physical properties
    \item Isotopes of an element show same chemical properties
\end{enumerate}',
    '[{"id": "a", "text": "(i), (iii) and (iv)"}, {"id": "b", "text": "(ii), (iii) and (iv)"}, {"id": "c", "text": "(ii) and (iii)"}, {"id": "d", "text": "(ii) and (iv)"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'Arrange the following elements in the order of their decreasing metallic character

$\mathrm{Na}, \mathrm{Si}, \mathrm{Cl}, \mathrm{Mg}, \mathrm{Al}$',
    '[{"id": "a", "text": "$\\mathrm{Cl}>\\mathrm{Si}>\\mathrm{Al}>\\mathrm{Mg}>\\mathrm{Na}$"}, {"id": "b", "text": "$\\mathrm{Na}>\\mathrm{Mg}>\\mathrm{Al}>\\mathrm{Si}>\\mathrm{Cl}$"}, {"id": "c", "text": "$\\mathrm{Na}>\\mathrm{Al}>\\mathrm{Mg}>\\mathrm{Cl}>\\mathrm{Si}$"}, {"id": "d", "text": "$\\mathrm{Al}>\\mathrm{Na}>\\mathrm{Si}>\\mathrm{Ca}>\\mathrm{Mg}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'Arrange the following elements in the order of their increasing nonmetallic character

$\mathrm{Li}, \mathrm{O}, \mathrm{C}, \mathrm{Be}, \mathrm{F}$',
    '[{"id": "a", "text": "$\\mathrm{F}<\\mathrm{O}<\\mathrm{C}<\\mathrm{Be}<\\mathrm{Li}$"}, {"id": "b", "text": "$\\mathrm{Li}<\\mathrm{Be}<\\mathrm{C}<\\mathrm{O}<\\mathrm{F}$"}, {"id": "c", "text": "$\\mathrm{F}<\\mathrm{O}<\\mathrm{C}<\\mathrm{Be}<\\mathrm{Li}$"}, {"id": "d", "text": "$\\mathrm{F}<\\mathrm{O}<\\mathrm{Be}<\\mathrm{C}<\\mathrm{Li}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'What type of oxide would Eka-aluminium form?',
    '[{"id": "a", "text": "$\\mathrm{EO}_{3}$"}, {"id": "b", "text": "$\\mathrm{E}_{3} \\mathrm{O}_{2}$"}, {"id": "c", "text": "$\\mathrm{E}_{2} \\mathrm{O}_{3}$"}, {"id": "d", "text": "$\\mathrm{EO}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q019',
    NULL,
    false
  ),
  (
    'mcq',
    'Three elements $B$, Si and Ge are',
    '[{"id": "a", "text": "metals"}, {"id": "b", "text": "non-metals"}, {"id": "c", "text": "metalloids"}, {"id": "d", "text": "metal, non-metal and metalloid respectively"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following elements will form an acidic oxide?',
    '[{"id": "a", "text": "An element with atomic number 7"}, {"id": "b", "text": "An element with atomic number 3"}, {"id": "c", "text": "An element with atomic number 12"}, {"id": "d", "text": "An element with atomic number 19"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q021',
    NULL,
    false
  ),
  (
    'mcq',
    'The element with atomic number 14 is hard and forms acidic oxide and a covalent halide. To which of the following categories does the element belong?',
    '[{"id": "a", "text": "Metal"}, {"id": "b", "text": "Metalloid"}, {"id": "c", "text": "Non-metal"}, {"id": "d", "text": "Left-hand side element"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'Which one of the following depict the correct representation of atomic radius(r) of an atom?
\begin{multicols}{2}
    \begin{enumerate}[label=\roman*)]
        \item
        % Diagram Begins
            \begin{center}
            \includegraphics[width=0.2\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_4.jpg}
            \end{center}
        % Diagram Ends
        \item 
        % Diagram Begins
            \begin{center}
            \includegraphics[width=0.2\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_2.jpg}
            \end{center}
        % Diagram Ends
        \item 
        % Diagram Begins
            \begin{center}
            \includegraphics[width=0.2\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_1.jpg}
            \end{center}
        % Diagram Ends
        \item 
        % Diagram Begins
            \begin{center}
            \includegraphics[width=0.2\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_3.jpg}
            \end{center}
        % Diagram Ends
    \end{enumerate}
\end{multicols}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(iii) and (iv)"}, {"id": "d", "text": "(i) and (iv)"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q023',
    'periodic-classification/cbse10_ch05_exemplar_q023.jpg',
    false
  ),
  (
    'mcq',
    'Which one of the following does not increase while moving down the group of the periodic table?',
    '[{"id": "a", "text": "Atomic radius"}, {"id": "b", "text": "Metallic character"}, {"id": "c", "text": "Valence"}, {"id": "d", "text": "Number of shells in an element"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q024',
    NULL,
    false
  ),
  (
    'mcq',
    'On moving from left to right in a period in the periodic table, the size of the atom.',
    '[{"id": "a", "text": "increases"}, {"id": "b", "text": "decreases"}, {"id": "c", "text": "does not change appreciably"}, {"id": "d", "text": "first decreases and then increases"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q025',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following set of elements is written in order of their increasing metallic character?',
    '[{"id": "a", "text": "$\\mathrm{Be} \\quad \\mathrm{Mg} \\quad \\mathrm{Ca}$"}, {"id": "b", "text": "$\\mathrm{Na} \\quad \\mathrm{Li} \\quad \\mathrm{K}$"}, {"id": "c", "text": "$\\mathrm{Mg} \\quad \\mathrm{Al} \\quad \\mathrm{Si}$"}, {"id": "d", "text": "$\\mathrm{C} \\quad \\mathrm{O} \\quad \\mathrm{N}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q026',
    NULL,
    false
  ),
  (
    'spr',
    'The three elements A, B and $\mathrm{C}$ with similar properties have atomic masses $\mathrm{X}, \mathrm{Y}$ and $\mathrm{Z}$ respectively. The mass of $\mathrm{Y}$ is approximately equal to the average mass of $\mathrm{X}$ and $\mathrm{Z}$. What is such an arrangement of elements called as? Give one example of such a set of elements.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q027',
    NULL,
    false
  ),
  (
    'mcq',
    'Elements have been arranged in the following sequence on the basis of their increasing atomic masses.

F, $\mathrm{Na}, \mathrm{Mg}, \mathrm{Al}, \mathrm{Si}, \mathrm{P}, \mathrm{S}, \mathrm{Cl}, \mathrm{Ar}, \mathrm{K}$',
    '[{"id": "a", "text": "Pick two sets of elements which have similar properties."}, {"id": "b", "text": "The given sequence represents which law of classification of elements?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q028',
    NULL,
    false
  ),
  (
    'mcq',
    'Can the following groups of elements be classified as Döbereiner''s triad?

 

Atomic mass of $\mathrm{Be}$ 9; $\mathrm{Na}$ 23; $\mathrm{Mg}$ 24; $\mathrm{Si}$ 28; $\mathrm{Cl}$ 35; $\mathrm{Ca}$ 40

Explain by giving reason.',
    '[{"id": "a", "text": "$\\mathrm{Na}, \\mathrm{Si}, \\mathrm{Cl}$"}, {"id": "b", "text": "Be, Mg, Ca"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q029',
    NULL,
    false
  ),
  (
    'spr',
    'In Mendeléev''s Periodic Table the elements were arranged in the increasing order of their atomic masses. However, cobalt with atomic mass of $58.93$ amu was placed before nickel having an atomic mass of $58.71 \mathrm{amu}$. Give reason for the same.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q030',
    NULL,
    false
  ),
  (
    'spr',
    '``Hydrogen occupies a unique position in Modern Periodic Table". Justify the statement.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q031',
    NULL,
    false
  ),
  (
    'spr',
    'Write the formulae of chlorides of Eka-silicon and Eka-aluminium, the elements predicted by Mendeléev.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q032',
    NULL,
    false
  ),
  (
    'spr',
    'Three elements A, B and C have 3,4 and 2 electrons respectively in their outermost shell. Give the group number to which they belong in the Modern Periodic Table. Also, give their valencies.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q033',
    NULL,
    false
  ),
  (
    'spr',
    'If an element $X$ is placed in group 14 , what will be the formula and the nature of bonding of its chloride?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q034',
    NULL,
    false
  ),
  (
    'mcq',
    'Compare the radii of two species $X$ and Y. Give reasons for your answer.',
    '[{"id": "a", "text": "$\\mathrm{X}$ has 12 protons and 12 electrons"}, {"id": "b", "text": "Y has 12 protons and 10 electrons"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q035',
    NULL,
    false
  ),
  (
    'mcq',
    'Arrange the following elements in increasing order of their atomic radii.',
    '[{"id": "a", "text": "$\\mathrm{Li}, \\mathrm{Be}, \\mathrm{F}, \\mathrm{N}$"}, {"id": "b", "text": "$\\mathrm{Cl}$, At, Br I"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q036',
    NULL,
    false
  ),
  (
    'mcq',
    'Identify and name the metals out of the following elements whose electronic configurations are given below.',
    '[{"id": "a", "text": "$2,8,2$"}, {"id": "b", "text": "$2,8,1$"}, {"id": "c", "text": "$2,8,7$"}, {"id": "d", "text": "2,1"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q037',
    NULL,
    false
  ),
  (
    'spr',
    'Write the formula of the product formed when the element A (atomic number 19) combines with the element B (atomic number 17). Draw its electronic dot structure. What is the nature of the bond formed?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q038',
    NULL,
    false
  ),
  (
    'spr',
    'Arrange the following elements in the increasing order of their metallic character

$\mathrm{Mg}, \mathrm{Ca}, \mathrm{K}, \mathrm{Ge}, \mathrm{Ga}$',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q039',
    NULL,
    false
  ),
  (
    'mcq',
    'Identify the elements with the following property and arrange them in increasing order of their reactivity',
    '[{"id": "a", "text": "An element which is a soft and reactive metal"}, {"id": "b", "text": "The metal which is an important constituent of limestone"}, {"id": "c", "text": "The metal which exists in liquid state at room temperature"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q040',
    NULL,
    false
  ),
  (
    'mcq',
    'Properties of the elements are given below. Where would you locate the following elements in the periodic table?',
    '[{"id": "a", "text": "A soft metal stored under kerosene"}, {"id": "b", "text": "An element with variable (more than one) valency stored under water."}, {"id": "c", "text": "An element which is tetravalent and forms the basis of organic chemistry"}, {"id": "d", "text": "An element which is an inert gas with atomic number 2"}, {"id": "e", "text": "An element whose thin oxide layer is used to make other elements corrosion resistant by the process of ``anodising\""}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q041',
    NULL,
    false
  ),
  (
    'mcq',
    'An element is placed in 2 nd Group and 3rd Period of the Periodic Table, burns in presence of oxygen to form a basic oxide.',
    '[{"id": "a", "text": "Identify the element"}, {"id": "b", "text": "Write the electronic configuration"}, {"id": "c", "text": "Write the balanced equation when it burns in the presence of air"}, {"id": "d", "text": "Write a balanced equation when this oxide is dissolved in water"}, {"id": "e", "text": "Draw the electron dot structure for the formation of this oxide"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q042',
    NULL,
    false
  ),
  (
    'mcq',
    'An element $\mathrm{X}$ (atomic number 17) reacts with an element $\mathrm{Y}$ (atomic number 20) to form a divalent halide.',
    '[{"id": "a", "text": "Where in the periodic table are elements $\\mathrm{X}$ and $\\mathrm{Y}$ placed?"}, {"id": "b", "text": "Classify $\\mathrm{X}$ and $\\mathrm{Y}$ as metal (s), non-metal (s) or metalloid (s)"}, {"id": "c", "text": "What will be the nature of oxide of element Y? Identify the nature of bonding in the compound formed"}, {"id": "d", "text": "Draw the electron dot structure of the divalent halide"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q043',
    NULL,
    false
  ),
  (
    'mcq',
    'Atomic number of a few elements are given below

$10,20,7,14$',
    '[{"id": "a", "text": "Identify the elements"}, {"id": "b", "text": "Identify the Group number of these elements in the Periodic Table"}, {"id": "c", "text": "Identify the Periods of these elements in the Periodic Table"}, {"id": "d", "text": "What would be the electronic configuration for each of these elements?"}, {"id": "e", "text": "Determine the valency of these elements"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q044',
    NULL,
    false
  ),
  (
    'spr',
    'Complete the following cross word puzzle
% Diagram Begins
    \begin{center}
    \includegraphics[width=0.5\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_5.jpg}
    \end{center}
% Diagram Ends

(1) An element with atomic number 12.

(3) Metal used in making cans and member of Group 14.

(4) A lustrous non-metal which has 7 electrons in its outermost shell.


(2) Highly reactive and soft metal which imparts yellow colour when subjected to flame and is kept in kerosene.

(5) The first element of second Period

(6) An element which is used in making fluorescent bulbs and is second member of Group 18 in the Modern Periodic Table

(7) A radioactive element which is the last member of halogen family.

(8) Metal which is an important constituent of steel and forms rust when exposed to moist air.

(9) The first metalloid in Modern Periodic Table whose fibres are used in making bullet-proof vests',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q045',
    'periodic-classification/cbse10_ch05_exemplar_q045.jpg',
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "In this ladder symbols of elements are jumbled up. Rearrange these symbols of elements in the increasing order of their atomic number in the Periodic Table."}, {"id": "b", "text": "Arrange them in the order of their group also.\n% Diagram Begins\n    \\begin{center}\n    \\includegraphics[width=0.5\\textwidth]{05.Class 10_NCERT Exempler_Periodic Classification of Elements_6.jpg}\n    \\end{center}\n% Diagram Ends"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q046',
    'periodic-classification/cbse10_ch05_exemplar_q046.jpg',
    false
  ),
  (
    'mcq',
    'Mendeléev predicted the existence of certain elements not known at that time and named two of them as Eka-silicon and Eka-aluminium.',
    '[{"id": "a", "text": "Name the elements which have taken the place of these elements"}, {"id": "b", "text": "Mention the group and the period of these elements in the Modern Periodic Table."}, {"id": "c", "text": "Classify these elements as metals, non-metals or metalloids"}, {"id": "d", "text": "How many valence electrons are present in each one of them?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q047',
    NULL,
    false
  ),
  (
    'mcq',
    '\begin{enumerate}[label=\roman*)]
    \item Electropositive nature of the element(s) increases down the group and decreases across the period
    \item Electronegativity of the element decreases down the group and increases across the period
    \item Atomic size increases down the group and decreases across a period (left to right)
    \item Metallic character increases down the group and decreases across a period.
\end{enumerate}
On the basis of the above trends of the Periodic Table, answer the following about the elements with atomic numbers 3 to 9.',
    '[{"id": "a", "text": "Name the most electropositive element among them"}, {"id": "b", "text": "Name the most electronegative element"}, {"id": "c", "text": "Name the element with smallest atomic size"}, {"id": "d", "text": "Name the element which is a metalloid"}, {"id": "e", "text": "Name the element which shows maximum valency."}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q048',
    NULL,
    false
  ),
  (
    'mcq',
    'An element $\mathrm{X}$ which is a yellow solid at room temperature shows catenation and allotropy. X forms two oxides which are also formed during the thermal decomposition of ferrous sulphate crystals and are the major air pollutants.',
    '[{"id": "a", "text": "Identify the element $\\mathrm{X}$"}, {"id": "b", "text": "Write the electronic configuration of $X$"}, {"id": "c", "text": "Write the balanced chemical equation for the thermal decomposition of ferrous sulphate crystals?"}, {"id": "d", "text": "What would be the nature (acidic/ basic) of oxides formed?"}, {"id": "e", "text": "Locate the position of the element in the Modern Periodic Table."}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q049',
    NULL,
    false
  ),
  (
    'mcq',
    'An element $X$ of group 15 exists as diatomic molecule and combines with hydrogen at $773 \mathrm{~K}$ in presence of the catalyst to form a compound, ammonia which has a characteristic pungent smell.',
    '[{"id": "a", "text": "Identify the element $X$. How many valence electrons does it have?"}, {"id": "b", "text": "Draw the electron dot structure of the diatomic molecule of $\\mathrm{X}$. What type of bond is formed in it?"}, {"id": "c", "text": "Draw the electron dot structure for ammonia and what type of bond is formed in it?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q050',
    NULL,
    false
  ),
  (
    'spr',
    'Which group of elements could be placed in Mendeléev''s Periodic Table without disturbing the original order? Give reason.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q051',
    NULL,
    false
  ),
  (
    'spr',
    'Give an account of the process adopted by Mendeléev for the classification of elements. How did he arrive at ``Periodic Law"?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_exemplar_q052',
    NULL,
    false
  ),
  (
    'spr',
    'Did Döbereiner''s triads also exist in the columns of Newlands'' Octaves? Compare and find out.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What were the limitations of Döbereiner''s classification?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'What were the limitations of Newlands'' Law of Octaves?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'Use Mendeléev''s Periodic Table to predict the formulae for the oxides of the following elements: \newline
K, \quad C, \quad AI, \quad Si, \quad Ba.',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'Besides gallium, which other elements have since been discovered that were left by Mendeléev in his Periodic Table? (any two)',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'What were the criteria used by Mendeléev in creating his Periodic Table?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'Why do you think the noble gases are placed in a separate group?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q007',
    NULL,
    false
  ),
  (
    'spr',
    'How could the Modern Periodic Table remove various anomalies of Mendeléev''s Perlodic Table?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q008',
    NULL,
    false
  ),
  (
    'spr',
    'Name two elements you would expect to show chemical reactions similar to magnesium. What is the basis for your choice?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'Name',
    '[{"id": "a", "text": "three elements that have a single electron in their outermost shells."}, {"id": "b", "text": "two elements that have two electrons in their outermost shells."}, {"id": "c", "text": "three elements with filled outermost shells."}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q010',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Lithium, sodium, potasstum are all metals that react with water to liberate hydrogen gas. Is there any similarity in the atoms of these elements?"}, {"id": "b", "text": "Helium is an unreactive gas and neon is a gas of extremely low reactivity. What, if anything, do their atoms have in common?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'In the Modern Perlodic Table, which are the metals among the first ten elements?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q012',
    NULL,
    false
  ),
  (
    'spr',
    'By considering their position in the Perlodic Table, which one of the following elements would you expect to have maximum metallic characteristic? \newline
Ga \quad Ge \quad As \quad Se \quad Be',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements is not a correct statement about the trends when going from left to right across the periods of periodic Table.',
    '[{"id": "a", "text": "The elements become less metallic in nature."}, {"id": "b", "text": "The number of valence electrons increases."}, {"id": "c", "text": "The atoms lose their electrons more easily."}, {"id": "d", "text": "The oxides become more acidic."}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Element $\mathrm{X}$ forms a chloride with the formula $\mathrm{XCl}_2$, which is a solid with a high melting point. X would most likely be in the same group of the Periodic Table as',
    '[{"id": "a", "text": "$\\mathrm{Na}$"}, {"id": "b", "text": "$\\mathrm{Mg}$"}, {"id": "c", "text": "$\\mathrm{AI}$"}, {"id": "d", "text": "$\\mathrm{Si}$"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'Which element has',
    '[{"id": "a", "text": "two shells, both of which are completely filled with electrons?"}, {"id": "b", "text": "the electronic configuration $2,8,2$ ?"}, {"id": "c", "text": "a total of three shells, with four electrons in its valence shell?"}, {"id": "d", "text": "a total of two shells, with three electrons in its valence shell?"}, {"id": "e", "text": "twice as many electrons in its second shell as in its first shell?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q016',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "What property do all elements in the same column of the Periodic Table as boron have in common?"}, {"id": "b", "text": "What property do all elements in the same column of the Periodic Table as fluorine have in common?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'An atom has electronic configuration $2,8,7$.',
    '[{"id": "a", "text": "What is the atomic number of this element?"}, {"id": "b", "text": "To which of the following elements would it be chemically similar? \\newline\n(Atomic numbers are given in parentheses.) \\newline\nN(7) \\quad F(9) \\quad P(15) \\quad Ar(18)"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'The position of three elements $\mathrm{A}, \mathrm{B}$ and $\mathrm{C}$ in the Periodic Table are shown below -

$\begin{array}{cc} \text{Group 16} & \text{Group 17} \\ - & - \\ - & \text { A } \\ - & - \\ \text { B } & \text { C }\end{array}$',
    '[{"id": "a", "text": "State whether A is a metal or non-metal."}, {"id": "b", "text": "State whether $\\mathrm{C}$ is more reactive or less reactive than $\\mathrm{A}$."}, {"id": "c", "text": "Will $C$ be larger or smaller in size than $B$ ?"}, {"id": "d", "text": "Which type of ion, cation or anion, will be formed by element A?"}]'::jsonb,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q019',
    NULL,
    false
  ),
  (
    'spr',
    'Nitrogen (atomic number 7) and phosphorus (atomic number 15) belong to group 15 of the Periodic Table. Write the electronic configuration of these two elements. Which of these will be more electronegative? Why?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q020',
    NULL,
    false
  ),
  (
    'spr',
    'How does the electronic configuration of an atom relate to its position in the Modern Periodic Table?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q021',
    NULL,
    false
  ),
  (
    'spr',
    'In the Modern Periodic Table, calcium (atomic number 20 ) is surrounded by elements with atomic numbers $12,19,21$ and 38 . Which of these have physical and chemical properties resembling calcium?',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q022',
    NULL,
    false
  ),
  (
    'spr',
    'Compare and contrast the arrangement of elements in Mendeléev''s Periodic Table and the Modern Periodic Table.

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'periodic-classification',
    'medium',
    'Periodic Classification of Elements',
    NULL,
    'cbse10_ch05_ncert_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statements about the autotrophs is incorrect?',
    '[{"id": "a", "text": "They synthesise carbohydrates from carbon dioxide and water in the presence of sunlight and chlorophyll"}, {"id": "b", "text": "They store carbohydrates in the form of starch"}, {"id": "c", "text": "They convert carbon dioxide and water into carbohydrates in the absence of sunlight"}, {"id": "d", "text": "They constitute the first trophic level in food chains"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q001',
    NULL,
    false
  ),
  (
    'mcq',
    'In which of the following groups of organisms, food material is broken down outside the body and absorbed?',
    '[{"id": "a", "text": "Mushroom, green plants, Amoeba"}, {"id": "b", "text": "Yeast, mushroom, bread mould"}, {"id": "c", "text": "Paramecium, Amoeba, Cuscuta"}, {"id": "d", "text": "Cuscuta, lice, tapeworm"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q002',
    NULL,
    false
  ),
  (
    'mcq',
    'Select the correct statement',
    '[{"id": "a", "text": "Heterotrophs do not synthesise their own food"}, {"id": "b", "text": "Heterotrophs utilise solar energy for photosynthesis"}, {"id": "c", "text": "Heterotrophs synthesise their own food"}, {"id": "d", "text": "Heterotrophs are capable of converting carbon dioxide and water into carbohydrates"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q003',
    NULL,
    false
  ),
  (
    'mcq',
    'Which is the correct sequence of parts in human alimentary canal?',
    '[{"id": "a", "text": "Mouth $\\rightarrow$ stomach $\\rightarrow$ small intestine $\\rightarrow$ oesophagus $\\rightarrow$ large intestine"}, {"id": "b", "text": "Mouth $\\rightarrow$ oesophagus $\\rightarrow$ stomach $\\rightarrow$ large intestine $\\rightarrow$ small intestine"}, {"id": "c", "text": "Mouth $\\rightarrow$ stomach $\\rightarrow$ oesophagus $\\rightarrow$ small intestine $\\rightarrow$ large intestine"}, {"id": "d", "text": "Mouth $\\rightarrow$ oesophagus $\\rightarrow$ stomach $\\rightarrow$ small intestine $\\rightarrow$ large intestine"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q004',
    NULL,
    false
  ),
  (
    'mcq',
    'If salivary amylase is lacking in the saliva, which of the following events in the mouth cavity will be affected?',
    '[{"id": "a", "text": "Proteins breaking down into amino acids"}, {"id": "b", "text": "Starch breaking down into sugars"}, {"id": "c", "text": "Fats breaking down into fatty acids and glycerol"}, {"id": "d", "text": "Absorption of vitamins"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q005',
    NULL,
    false
  ),
  (
    'mcq',
    'The inner lining of stomach is protected by one of the following from hydrochloric acid. Choose the correct one',
    '[{"id": "a", "text": "Pepsin"}, {"id": "b", "text": "Mucus"}, {"id": "c", "text": "Salivary amylase"}, {"id": "d", "text": "Bile"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q006',
    NULL,
    false
  ),
  (
    'mcq',
    'Which part of alimentary canal receives bile from the liver?',
    '[{"id": "a", "text": "Stomach"}, {"id": "b", "text": "Small intestine"}, {"id": "c", "text": "Large intestine"}, {"id": "d", "text": "Oesophagus"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'A few drops of iodine solution were added to rice water. The solution turned blue-black in colour. This indicates that rice water contains',
    '[{"id": "a", "text": "complex proteins"}, {"id": "b", "text": "simple proteins"}, {"id": "c", "text": "fats"}, {"id": "d", "text": "starch"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q008',
    NULL,
    false
  ),
  (
    'mcq',
    'In which part of the alimentary canal food is finally digested?',
    '[{"id": "a", "text": "Stomach"}, {"id": "b", "text": "Mouth cavity"}, {"id": "c", "text": "Large intestine"}, {"id": "d", "text": "Small intestine"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the function of the pancreatic juice from the following',
    '[{"id": "a", "text": "trypsin digests proteins and lipase carbohydrates"}, {"id": "b", "text": "trypsin digests emulsified fats and lipase proteins"}, {"id": "c", "text": "trypsin and lipase digest fats"}, {"id": "d", "text": "trypsin digests proteins and lipase emulsified fats"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q010',
    NULL,
    false
  ),
  (
    'mcq',
    'When air is blown from mouth into a test-tube containing lime water, the lime water turned milky due to the presence of',
    '[{"id": "a", "text": "oxygen"}, {"id": "b", "text": "carbon dioxide"}, {"id": "c", "text": "nitrogen"}, {"id": "d", "text": "water vapour"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q011',
    NULL,
    false
  ),
  (
    'mcq',
    'The correct sequence of anaerobic reactions in yeast is',
    '[{"id": "a", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $\\xrightarrow{\\text { mitochondria } }$ Ethanol$+$ Carbondioxide"}, {"id": "b", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $\\xrightarrow{\\text { cytoplasm } }$ Lactic acid"}, {"id": "c", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $\\xrightarrow{\\text { mitochondria } }$ Lactic acid"}, {"id": "d", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $\\xrightarrow{\\text { cytoplasm } }$ Ethanol$+$ Carbondioxide"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q012',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is most appropriate for aerobic respiration?',
    '[{"id": "a", "text": "Glucose $\\xrightarrow{\\text { mitochondria } }$ Pyruvate $\\xrightarrow{\\text { cytoplasm } } \\mathrm{CO}_{2}+\\mathrm{H}_{2} \\mathrm{O}+$ Energy"}, {"id": "b", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $\\xrightarrow{\\text { mitochondria } }$ $\\mathrm{CO}_{2}+\\mathrm{H}_{2} \\mathrm{O}+$ Energy"}, {"id": "c", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $+$ Energy $\\xrightarrow{\\text { mitochondria } }$ $\\mathrm{CO}_{2}+\\mathrm{H}_{2} \\mathrm{O}$"}, {"id": "d", "text": "Glucose $\\xrightarrow{\\text { cytoplasm } }$ Pyruvate $+$ Energy $\\xrightarrow{\\text { mitochondria } }$ $\\mathrm{CO}_{2}+\\mathrm{H}_{2} \\mathrm{O}+$ Energy"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q013',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statement(s) is (are) true about respiration?
\begin{enumerate}[label=\roman*)]
    \item During inhalation, ribs move inward and diaphragm is raised
    \item In the alveoli, exchange of gases takes place i.e., oxygen from alveolar air diffuses into blood and carbon dioxide from blood into alveolar air
    \item Haemoglobin has greater affinity for carbon dioxide than oxygen
    \item Alveoli increase surface area for exchange of gases
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iv)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(i) and (iii)"}, {"id": "d", "text": "(ii) and (iv)"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q014',
    NULL,
    false
  ),
  (
    'mcq',
    'Which is the correct sequence of air passage during inhalation?',
    '[{"id": "a", "text": "Nostrils $\\rightarrow$ larynx $\\rightarrow$ pharynx $\\rightarrow$ trachea $\\rightarrow$ lungs"}, {"id": "b", "text": "Nasal passage $\\rightarrow$ trachea $\\rightarrow$ pharynx $\\rightarrow$ larynx $\\rightarrow$ alveoli"}, {"id": "c", "text": "larynx $\\rightarrow$ nostrils $\\rightarrow$ pharynx $\\rightarrow$ lungs"}, {"id": "d", "text": "Nostrils $\\rightarrow$ pharynx $\\rightarrow$ larynx $\\rightarrow$ trachea $\\rightarrow$ alveoli"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q015',
    NULL,
    false
  ),
  (
    'mcq',
    'During respiration exchange of gases take place in',
    '[{"id": "a", "text": "trachea and larynx"}, {"id": "b", "text": "alveoli of lungs"}, {"id": "c", "text": "alveoli and throat"}, {"id": "d", "text": "throat and larynx"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q016',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statement (s) is (are) true about heart?
\begin{enumerate}[label=\roman*)]
    \item Left atrium receives oxygenated blood from different parts of body while right atrium receives deoxygenated blood from lungs
    \item Left ventricle pumps oxygenated blood to different body parts while right ventricle pumps deoxygenated blood to lungs
    \item Left atrium transfers oxygenated blood to right ventricle which sends it to different body parts
    \item Right atrium receives deoxygenated blood from different parts of the body while left ventricle pumps oxygenated blood to different parts of the body
\end{enumerate}',
    '[{"id": "a", "text": "(i)"}, {"id": "b", "text": "(ii)"}, {"id": "c", "text": "(ii) and (iv)"}, {"id": "d", "text": "(i) and (iii)"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q017',
    NULL,
    false
  ),
  (
    'mcq',
    'What prevents backflow of blood inside the heart during contraction?',
    '[{"id": "a", "text": "Valves in heart"}, {"id": "b", "text": "Thick muscular walls of ventricles"}, {"id": "c", "text": "Thin walls of atria"}, {"id": "d", "text": "All of the above"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q018',
    NULL,
    false
  ),
  (
    'mcq',
    'Single circulation i.e., blood flows through the heart only once during one cycle of passage through the body, is exhibited by',
    '[{"id": "a", "text": "Labeo, Chameleon, Salamander"}, {"id": "b", "text": "Hippocampus, Exocoetus, Anabas"}, {"id": "c", "text": "Hyla, Rana, Draco"}, {"id": "d", "text": "Whale, Dolphin, Turtle"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q019',
    NULL,
    false
  ),
  (
    'mcq',
    'In which of the following vertebrate group/groups, heart does not pump oxygenated blood to different parts of the body?',
    '[{"id": "a", "text": "Pisces and amphibians"}, {"id": "b", "text": "Amphibians and reptiles"}, {"id": "c", "text": "Amphibians only"}, {"id": "d", "text": "Pisces only"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q020',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the correct statement that describes arteries.',
    '[{"id": "a", "text": "They have thick elastic walls, blood flows under high pressure; collect blood from different organs and bring it back to the heart"}, {"id": "b", "text": "They have thin walls with valves inside, blood flows under low pressure and carry blood away from the heart to various organs of the body"}, {"id": "c", "text": "They have thick elastic walls, blood flows under low pressure; carry blood from the heart to various organs of the body"}, {"id": "d", "text": "They have thick elastic walls without valves inside, blood flows under high pressure and carry blood away from the heart to different parts of the body."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q021',
    NULL,
    false
  ),
  (
    'mcq',
    'The filtration units of kidneys are called',
    '[{"id": "a", "text": "ureter"}, {"id": "b", "text": "urethra"}, {"id": "c", "text": "neurons"}, {"id": "d", "text": "nephrons"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'Oxygen liberated during photosynthesis comes from',
    '[{"id": "a", "text": "water"}, {"id": "b", "text": "chlorophyll"}, {"id": "c", "text": "carbon dioxide"}, {"id": "d", "text": "glucose"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'The blood leaving the tissues becomes richer in',
    '[{"id": "a", "text": "carbon dioxide"}, {"id": "b", "text": "water"}, {"id": "c", "text": "heamoglobin"}, {"id": "d", "text": "oxygen"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q024',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following is an incorrect statement?',
    '[{"id": "a", "text": "Organisms grow with time"}, {"id": "b", "text": "Organisms must repair and maintain their structure"}, {"id": "c", "text": "Movement of molecules does not take place among cells"}, {"id": "d", "text": "Energy is essential for life processes"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q025',
    NULL,
    false
  ),
  (
    'mcq',
    'The internal (cellular) energy reserve in autotrophs is',
    '[{"id": "a", "text": "glycogen"}, {"id": "b", "text": "protein"}, {"id": "c", "text": "starch"}, {"id": "d", "text": "fatty acid"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q026',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following equations is the summary of photosynthesis?',
    '[{"id": "a", "text": "$6 \\mathrm{CO}_{2}+12 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow \\mathrm{C}_{6} \\mathrm{H}_{12} \\mathrm{O}_{6}+6 \\mathrm{O}_{2}+6 \\mathrm{H}_{2} \\mathrm{O}$"}, {"id": "b", "text": "$6 \\mathrm{CO}_{2}+\\mathrm{H}_{2} \\mathrm{O}+$ Sunlight $\\rightarrow \\mathrm{C}_{6} \\mathrm{H}_{12} \\mathrm{O}_{6}+\\mathrm{O}_{2}+6 \\mathrm{H}_{2} \\mathrm{O}$"}, {"id": "c", "text": "$6 \\mathrm{CO}_{2}+12 \\mathrm{H}_{2} \\mathrm{O}+$ Chlorophyll + Sunlight $\\rightarrow \\mathrm{C}_{6} \\mathrm{H}_{12} \\mathrm{O}_{6}+6 \\mathrm{O}_{2}+6 \\mathrm{H}_{2} \\mathrm{O}$"}, {"id": "d", "text": "$6 \\mathrm{CO}_{2}+12 \\mathrm{H}_{2} \\mathrm{O}+$ Chlorophyll $+$ Sunlight $\\rightarrow \\mathrm{C}_{6} \\mathrm{H}_{12} \\mathrm{O}_{6}+6 \\mathrm{CO}_{2}+6 \\mathrm{H}_{2} \\mathrm{O}$"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q027',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the event that does not occur in photosynthesis',
    '[{"id": "a", "text": "Absorption of light energy by chlorophyll"}, {"id": "b", "text": "Reduction of carbon dioxide to carbohydrates"}, {"id": "c", "text": "Oxidation of carbon to carbon dioxide"}, {"id": "d", "text": "Conversion of light energy to chemical energy"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q028',
    NULL,
    false
  ),
  (
    'mcq',
    'The opening and closing of the stomatal pore depends upon',
    '[{"id": "a", "text": "oxygen"}, {"id": "b", "text": "temperature"}, {"id": "c", "text": "water in guard cells"}, {"id": "d", "text": "concentration of $\\mathrm{CO}_{2}$ in stomata"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q029',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the forms in which most plants absorb nitrogen
\begin{multicols}{2}
\begin{enumerate}[label=\roman*)]
    \item Proteins
    \item Nitrates and Nitrites
    \item Urea
    \item Atmospheric nitrogen
\end{enumerate}
\end{multicols}',
    '[{"id": "a", "text": "(i) and (ii)"}, {"id": "b", "text": "(ii) and (iii)"}, {"id": "c", "text": "(iii) and (iv)"}, {"id": "d", "text": "(i) and (iv)"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q030',
    NULL,
    false
  ),
  (
    'mcq',
    'Which is the first enzyme to mix with food in the digestive tract?',
    '[{"id": "a", "text": "Pepsin"}, {"id": "b", "text": "Cellulase"}, {"id": "c", "text": "Amylase"}, {"id": "d", "text": "Trypsin"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q031',
    NULL,
    false
  ),
  (
    'mcq',
    'Which of the following statement(s) is (are) correct?
\begin{enumerate}[label=\roman*)]
    \item Pyruvate can be converted into ethanol and carbon dioxide by yeast
    \item Fermentation takes place in aerobic bacteria
    \item Fermentation takes place in mitochondria
    \item Fermentation is a form of anaerobic respiration
\end{enumerate}',
    '[{"id": "a", "text": "(i) and (iii)"}, {"id": "b", "text": "(ii) and (iv)"}, {"id": "c", "text": "(i) and (iv)"}, {"id": "d", "text": "(ii) and (iii)"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q032',
    NULL,
    false
  ),
  (
    'mcq',
    'Lack of oxygen in muscles often leads to cramps among cricketers. This results due to',
    '[{"id": "a", "text": "conversion of pyruvate to ethanol"}, {"id": "b", "text": "conversion of pyruvate to glucose"}, {"id": "c", "text": "non conversion of glucose to pyruvate"}, {"id": "d", "text": "conversion of pyruvate to lactic acid"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q033',
    NULL,
    false
  ),
  (
    'mcq',
    'Choose the correct path of urine in our body',
    '[{"id": "a", "text": "kidney $\\rightarrow$ ureter $\\rightarrow$ urethra $\\rightarrow$ urinary bladder"}, {"id": "b", "text": "kidney $\\rightarrow$ urinary bladder $\\rightarrow$ urethra $\\rightarrow$ ureter"}, {"id": "c", "text": "kidney $\\rightarrow$ ureters $\\rightarrow$ urinary bladder $\\rightarrow$ urethra"}, {"id": "d", "text": "urinary bladder $\\rightarrow$ kidney $\\rightarrow$ ureter $\\rightarrow$ urethra"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q034',
    NULL,
    false
  ),
  (
    'mcq',
    'During deficiency of oxygen in tissues of human beings, pyruvic acid is converted into lactic acid in the',
    '[{"id": "a", "text": "cytoplasm"}, {"id": "b", "text": "chloroplast"}, {"id": "c", "text": "mitochondria"}, {"id": "d", "text": "golgi body"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q035',
    NULL,
    false
  ),
  (
    'mcq',
    'Name the following',
    '[{"id": "a", "text": "The process in plants that links light energy with chemical energy"}, {"id": "b", "text": "Organisms that can prepare their own food"}, {"id": "c", "text": "The cell organelle where photosynthesis occurs"}, {"id": "d", "text": "Cells that surround a stomatal pore"}, {"id": "e", "text": "Organisms that cannot prepare their own food"}, {"id": "f", "text": "An enzyme secreted from gastric glands in stomach that acts on proteins."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q036',
    NULL,
    false
  ),
  (
    'spr',
    '``All plants give out oxygen during day and carbon dioxide during night". Do you agree with this statement? Give reason.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q037',
    NULL,
    false
  ),
  (
    'spr',
    'How do the guard cells regulate opening and closing of stomatal pores?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q038',
    NULL,
    false
  ),
  (
    'spr',
    'Two green plants are kept separately in oxygen free containers, one in the dark and the other in continuous light. Which one will live longer? Give reasons.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q039',
    NULL,
    false
  ),
  (
    'spr',
    'If a plant is releasing carbon dioxide and taking in oxygen during the day, does it mean that there is no photosynthesis occurring? Justify your answer.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q040',
    NULL,
    false
  ),
  (
    'spr',
    'Why do fishes die when taken out of water?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q041',
    NULL,
    false
  ),
  (
    'spr',
    'Differentiate between an autotroph and a heterotroph.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q042',
    NULL,
    false
  ),
  (
    'spr',
    'Is `nutrition'' a necessity for an organism? Discuss.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q043',
    NULL,
    false
  ),
  (
    'spr',
    'What would happen if green plants disappear from earth?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q044',
    NULL,
    false
  ),
  (
    'spr',
    'Leaves of a healthy potted plant were coated with vaseline. Will this plant remain healthy for long? Give reasons for your answer.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q045',
    NULL,
    false
  ),
  (
    'spr',
    'How does aerobic respiration differ from anaerobic respiration?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q046',
    NULL,
    false
  ),
  (
    'spr',
    'Match the words of Column (A) with that of Column (B)

\begin{tabular}{|l|l|}
\hline
Column (A) & Column (B) \\
\hline
(a) Phloem & (i) Excretion \\
(b) Nephron & (ii) Translocation of food \\
(c) Veins & (iii) Clotting of blood \\
(d) Platelets & (iv) Deoxygenated blood \\
\hline
\end{tabular}',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q047',
    NULL,
    false
  ),
  (
    'spr',
    'Differentiate between an artery and a vein.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q048',
    NULL,
    false
  ),
  (
    'spr',
    'What are the adaptations of leaf for photosynthesis?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q049',
    NULL,
    false
  ),
  (
    'spr',
    'Why is small intestine in herbivores longer than in carnivores?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q050',
    NULL,
    false
  ),
  (
    'spr',
    'What will happen if mucus is not secreted by the gastric glands?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q051',
    NULL,
    false
  ),
  (
    'spr',
    'What is the significance of emulsification of fats?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q052',
    NULL,
    false
  ),
  (
    'spr',
    'What causes movement of food inside the alimentary canal?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q053',
    NULL,
    false
  ),
  (
    'spr',
    'Why does absorption of digested food occur mainly in the small intestine?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q054',
    NULL,
    false
  ),
  (
    'spr',
    'Match Group (A) with Group (B)

\begin{tabular}{|l|l|}
\hline
Group (A) & Group (B) \\
\hline
(a) Autotrophic nutrition & (i) Leech \\
(b) Heterotrophic nutrition & (ii) Paramecium \\
(c) Parasitic nutrition & (iii) Deer \\
(d) Digestion in food vacuoles & (iv) Green plant \\
\hline
\end{tabular}',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q055',
    NULL,
    false
  ),
  (
    'spr',
    'Why is the rate of breathing in aquatic organisms much faster than in terrestrial organisms?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q056',
    NULL,
    false
  ),
  (
    'spr',
    'Why is blood circulation in human heart called double circulation?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q057',
    NULL,
    false
  ),
  (
    'spr',
    'What is the advantage of having four chambered heart?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q058',
    NULL,
    false
  ),
  (
    'spr',
    'Mention the major events during photosynthesis',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q059',
    NULL,
    false
  ),
  (
    'mcq',
    'In each of the following situations what happens to the rate of photosynthesis?',
    '[{"id": "a", "text": "Cloudy days"}, {"id": "b", "text": "No rainfall in the area"}, {"id": "c", "text": "Good manuring in the area"}, {"id": "d", "text": "Stomata get blocked due to dust"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q060',
    NULL,
    false
  ),
  (
    'spr',
    'Name the energy currency in the living organisms. When and where is it produced?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q061',
    NULL,
    false
  ),
  (
    'spr',
    'What is common for cuscuta, ticks and leeches?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q062',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the role of mouth in digestion of food.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q063',
    NULL,
    false
  ),
  (
    'spr',
    'What are the functions of gastric glands present in the wall of the stomach?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q064',
    NULL,
    false
  ),
  (
    'spr',
    'Match the terms in Column (A) with those in Column (B)

\begin{tabular}{|l|l|}
\hline
Column (A) & Group (B) \\
\hline
(a) Trypsin & (i) Pancreas \\
(b) Amylase & (ii) Liver \\
(c) Bile & (iii) Gastric glands \\
(d) Pepsin & (iv) Saliva \\
\hline
\end{tabular}',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q065',
    NULL,
    false
  ),
  (
    'mcq',
    'Name the correct substrates for the following enzymes',
    '[{"id": "a", "text": "Trypsin"}, {"id": "b", "text": "Amylase"}, {"id": "c", "text": "Pepsin"}, {"id": "d", "text": "Lipase"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q066',
    NULL,
    false
  ),
  (
    'spr',
    'Why do veins have thin walls as compared to arteries?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q067',
    NULL,
    false
  ),
  (
    'spr',
    'What will happen if platelets were absent in the blood?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q068',
    NULL,
    false
  ),
  (
    'spr',
    'Plants have low energy needs as compared to animals. Explain.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q069',
    NULL,
    false
  ),
  (
    'spr',
    'Why and how does water enter continuously into the root xylem?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q070',
    NULL,
    false
  ),
  (
    'spr',
    'Why is transpiration important for plants?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q071',
    NULL,
    false
  ),
  (
    'spr',
    'How do leaves of plants help in excretion?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q072',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the process of nutrition in Amoeba.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q073',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the alimentary canal of man.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q074',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the process of breathing in man.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q075',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the importance of soil for plant growth.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q076',
    NULL,
    false
  ),
  (
    'spr',
    'Draw the diagram of alimentary canal of man and label the following parts.

Mouth, Oesophagus, Stomach, Intestine',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q077',
    NULL,
    false
  ),
  (
    'spr',
    'How do carbohydrates, proteins and fats get digested in human beings?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q078',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the mechanism of photosynthesis.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q079',
    NULL,
    false
  ),
  (
    'spr',
    'Explain the three pathways of breakdown in living organisms.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q080',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the flow of blood through the heart of human beings.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q081',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the process of urine formation in kidneys.

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_exemplar_q082',
    NULL,
    false
  ),
  (
    'spr',
    'Why is diffusion insufficient to meet the oxygen requirements of multi-cellular organisms like humans?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What criteria do we use to decide whether something is alive?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q002',
    NULL,
    false
  ),
  (
    'spr',
    'What are outside raw materials used for by an organism?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q003',
    NULL,
    false
  ),
  (
    'spr',
    'What processes would you consider essential for maintaining life?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q004',
    NULL,
    false
  ),
  (
    'spr',
    'What are the differences between autotrophic nutrition and heterotrophic nutrition?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q005',
    NULL,
    false
  ),
  (
    'spr',
    'Where do plants get each of the raw materlals required for photosynthesis?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q006',
    NULL,
    false
  ),
  (
    'spr',
    'What is the role of the acid in our stomach?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q007',
    NULL,
    false
  ),
  (
    'spr',
    'What is the function of digestive enzymes?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q008',
    NULL,
    false
  ),
  (
    'spr',
    'How is the small intestine designed to absorb digested food?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q009',
    NULL,
    false
  ),
  (
    'spr',
    'What advantage over an aquatic organism does a terrestrial organism have with regard to obtaining oxygen for respiration?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q010',
    NULL,
    false
  ),
  (
    'spr',
    'What are the different ways in which glucose is oxidised to provide energy in varlous organisms?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q011',
    NULL,
    false
  ),
  (
    'spr',
    'How is oxygen and carbon dioxide transported in human beings?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q012',
    NULL,
    false
  ),
  (
    'spr',
    'How are the lungs designed in human beings to maximise the area for exchange of gases?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q013',
    NULL,
    false
  ),
  (
    'spr',
    'What are the components of the transport system in human beings? What are the functions of these components?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q014',
    NULL,
    false
  ),
  (
    'spr',
    'What are the components of the transport system in human beings? \newline
What are the functions of these components?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q015',
    NULL,
    false
  ),
  (
    'spr',
    'Why is it necessary to separate oxygenated and deoxygenated blood in mammals and birds?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q016',
    NULL,
    false
  ),
  (
    'spr',
    'What are the components of the transport system in highly organised plants?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q017',
    NULL,
    false
  ),
  (
    'spr',
    'How are water and minerals transported in plants?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q018',
    NULL,
    false
  ),
  (
    'spr',
    'How is food transported in plants?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q019',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the structure and functioning of nephrons.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q020',
    NULL,
    false
  ),
  (
    'spr',
    'What are the methods used by plants to get rid of excretory products?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q021',
    NULL,
    false
  ),
  (
    'spr',
    'How is the amount of urine produced regulated?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q022',
    NULL,
    false
  ),
  (
    'mcq',
    'The kidneys in human beings are a part of the system for',
    '[{"id": "a", "text": "nutrition."}, {"id": "b", "text": "excretion."}, {"id": "c", "text": "respiration."}, {"id": "d", "text": "transportation."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q023',
    NULL,
    false
  ),
  (
    'mcq',
    'The xylem in plants are responsible for',
    '[{"id": "a", "text": "transport of water."}, {"id": "b", "text": "transport of amino acids."}, {"id": "c", "text": "transport of food."}, {"id": "d", "text": "transport of oxygen."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q024',
    NULL,
    false
  ),
  (
    'mcq',
    'The autotrophic mode of nutrition requires',
    '[{"id": "a", "text": "carbon dioxide and water."}, {"id": "b", "text": "sunlight."}, {"id": "c", "text": "chlorophyll."}, {"id": "d", "text": "all of the above."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q025',
    NULL,
    false
  ),
  (
    'mcq',
    'The breakdown of pyruvate to give carbon dioxide, water and energy takes place in',
    '[{"id": "a", "text": "cytoplasm."}, {"id": "b", "text": "chloroplast."}, {"id": "c", "text": "mitochondria."}, {"id": "d", "text": "nucleus."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q026',
    NULL,
    false
  ),
  (
    'spr',
    'How are fats digested in our bodies? Where does this process take place?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q027',
    NULL,
    false
  ),
  (
    'spr',
    'What is the role of saliva in the digestion of food?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q028',
    NULL,
    false
  ),
  (
    'spr',
    'What are the necessary conditions for autotrophic nutrition and what are its byproducts?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q029',
    NULL,
    false
  ),
  (
    'spr',
    'What are the differences between aerobic and anaerobic respiration? Name some organisms that use the anaerobic mode of respiration.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q030',
    NULL,
    false
  ),
  (
    'spr',
    'How are the alveoli designed to maximise the exchange of gases?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q031',
    NULL,
    false
  ),
  (
    'spr',
    'What would be the consequences of a deficiency of haemoglobin in our bodies?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q032',
    NULL,
    false
  ),
  (
    'spr',
    'Describe double circulation of blood in human beings. Why is it necessary?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q033',
    NULL,
    false
  ),
  (
    'spr',
    'What are the differences between the transport of materials in xylem and phloem?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q034',
    NULL,
    false
  ),
  (
    'spr',
    'Compare the functioning of alveoli in the lungs and nephrons in the kidneys with respect to their structure and functioning.

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_ncert_q035',
    NULL,
    false
  ),
  (
    'spr',
    'Some organisms derive nutrition from plants or animals without killing them. What are these organisms called? Write one example.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q001',
    NULL,
    false
  ),
  (
    'spr',
    'What are enzymes ? Name the enzymes, which initiates the protein and fat digestion.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q002',
    NULL,
    false
  ),
  (
    'spr',
    'What is the primary requirement for pancreatic enzymes to act?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q003',
    NULL,
    false
  ),
  (
    'spr',
    'Two green plants are kept separately in oxygen free containers, one in the dark and other in the continuous light. Which one will live longer? Give reasons.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q004',
    NULL,
    false
  ),
  (
    'spr',
    'Energy is required by an organism even during sleep. Why?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q005',
    NULL,
    false
  ),
  (
    'spr',
    'List the three events that occur during the process of photosynthesis. Explain the role of stomata in this process.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q006',
    NULL,
    false
  ),
  (
    'spr',
    'Explain with the help of neat and well-labelled diagrams the different steps involved in the nutrition in Amoeba.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q007',
    NULL,
    false
  ),
  (
    'mcq',
    'The graph shows how the amount of carbon dioxide taken in by a plant varies through a 24 hour period.

\begin{center}
\includegraphics[scale=0.25]{Life Processes_Nutrition_1.png}
\end{center}',
    '[{"id": "a", "text": "At what time did photosynthesis start?"}, {"id": "b", "text": "At what time was the rate of photosynthesis greatest?"}, {"id": "c", "text": "At what time of the day did it get dark?\n\\begin{enumerate}[label=\\roman*)]\n    \\item  How does plant obtain $\\mathrm{CO}_2$ ?\n    \\item  What happens to this $\\mathrm{CO}_2$ ?\n\\end{enumerate}"}, {"id": "d", "text": "What other factors could affect the rate of photosynthesis?"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q008',
    'life-processes/cbse10_ch06_test_q008.png',
    false
  ),
  (
    'spr',
    'Explain the process of digestion of food in mouth, stomach and small intestine in human body.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q009',
    NULL,
    false
  ),
  (
    'spr',
    'In an experiment, saliva is added to the test tube containing pieces of bread (powdered). What will be the result?


% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_test_q010',
    NULL,
    false
  ),
  (
    'spr',
    'What are Nephrons? How is a Nephron involved in the filtration of blood and formation of urine?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q001',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Draw the structure of a nephron and label the following parts on it.\n\n\\begin{enumerate}[label=\\roman*)]\n\\item Renal artery\n\\item Bowman''s capsule\n\\item Glomerulus\n\\item Collecting duct\n\\end{enumerate}"}, {"id": "b", "text": "Name four substances in the initial filtrate which are selectively reabsorbed as the filtrate floor along the tubule."}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q002',
    NULL,
    false
  ),
  (
    'spr',
    'What are kidney stones? How are these developed in the kidney ?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q003',
    NULL,
    false
  ),
  (
    'spr',
    'What causes the liquid part of blood to filter out from glomerulus into the renal tubule?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q004',
    NULL,
    false
  ),
  (
    'spr',
    'What is photolysis and when does it occur?',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q005',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the process of urine formation in kidneys.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q006',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Draw a diagram depicting human alimentary canal and label the components gall bladder, liver and pancreas in it."}, {"id": "b", "text": "State the role of liver and pancreas."}, {"id": "c", "text": "Name the organs which perform the following functions in humans.\n\n\\begin{enumerate}[label=\\roman*)]\n    \\item Absorption of digested food\n    \\item Absortion of water\n\\end{enumerate}"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q007',
    NULL,
    false
  ),
  (
    'spr',
    'Describe the holozoic nutrition in details using one example.',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q008',
    NULL,
    false
  ),
  (
    'mcq',
    '',
    '[{"id": "a", "text": "Why is nutrition a necessity for an organism? State three reasons."}, {"id": "b", "text": "What is likely to happen if green plants disappear from Earth?"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q009',
    NULL,
    false
  ),
  (
    'mcq',
    'The graph shows how the amount of carbon dioxide taken in by a plant varies through a 24 hour period.

\begin{center}
\includegraphics[scale=0.25]{Life Processes_Nutrition_1.png}
\end{center}',
    '[{"id": "a", "text": "At what time did photosynthesis start?"}, {"id": "b", "text": "At what time was the rate of photosynthesis greatest?"}, {"id": "c", "text": "At what time of the day did it get dark?\n\\begin{enumerate}[label=\\roman*)]\n    \\item  How does plant obtain $\\mathrm{CO}_2$ ?\n    \\item  What happens to this $\\mathrm{CO}_2$ ?\n\\end{enumerate}"}, {"id": "d", "text": "What other factors could affect the rate of photosynthesis?"}]'::jsonb,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q010',
    'life-processes/cbse10_ch06_misc_q010.png',
    false
  ),
  (
    'spr',
    'How is Chemosynthetic mode of nutrition is different than Photosynthetic mode of nutrition

% =============================================================
%Question End
% =============================================================',
    NULL,
    '',
    '',
    'life-processes',
    'medium',
    'Life Processes',
    NULL,
    'cbse10_ch06_misc_q011',
    NULL,
    false
  )
ON CONFLICT (bank_item_id) DO NOTHING;

