-- GRE questions: set 4, section 2, difficulty easy
-- Total rows: 15
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('single-choice', 'Attendees at a charity dinner gave at least \$85 each. If $6,450 was collected, what is the maximum number of people who could have attended?', '[{"id": "a", "text": "73"}, {"id": "b", "text": "74"}, {"id": "c", "text": "75"}, {"id": "d", "text": "76"}, {"id": "e", "text": "77"}]'::jsonb, 'c', '$6450/85 = 75.88$. Max is 75.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('multi-select', 'Let $x$ be the interior angle of a regular hexagon and $y$ be the interior angle of a regular octagon. Which of the following is true? Indicate all such statements.', '[{"id": "a", "text": "$y > x$"}, {"id": "b", "text": "$x + y = 255$"}, {"id": "c", "text": "$y - x = 15$"}]'::jsonb, '["a","b","c"]', 'Hexagon: 120. Octagon: 135. All three statements are true.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Beth is 12 years younger than Alan. In 20 years, Beth will be 80% of Alan''s age. How old is Beth now?', NULL, '28', 'Alan = 40. Beth = 28.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('multi-select', 'Data: A bar chart shows monthly freezing days and days above 90F for St. Louis. January has over 25 freezing days, July has the most days above 90F, and June and July have zero freezing days. Which statements about St. Louis temperatures are true? Indicate all such statements.', '[{"id": "a", "text": "St. Louis had more than 25 freezing days in January."}, {"id": "b", "text": "July was the month with the most days above 90F."}, {"id": "c", "text": "There were no freezing days in June or July."}]'::jsonb, '["a","b","c"]', 'All three statements are confirmed by the data.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'A circle is inscribed in a square that has an area of 50. What is the area of the circle?', '[{"id": "a", "text": "$12.5\\pi$"}, {"id": "b", "text": "$25\\pi$"}, {"id": "c", "text": "$50\\pi$"}, {"id": "d", "text": "$100\\pi$"}]'::jsonb, 'a', 'Radius $= \\sqrt{50}/2$. Area $= 12.5\\pi$.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A line passes through $(3, -2)$ and $(-8, 0)$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', 'Slope $= 2/(-11)$. Negative, so less than 0.', 'The slope of the line', '0', 'A line passes through $(3, -2)$ and $(-8, 0)$.', 'easy', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Rey is 12 years younger than Sebastian. Five years ago, Rey was half Sebastian''s age. How old will Sebastian be next year?', '[{"id": "a", "text": "25"}, {"id": "b", "text": "29"}, {"id": "c", "text": "30"}, {"id": "d", "text": "32"}, {"id": "e", "text": "35"}]'::jsonb, 'c', 'Sebastian = 29. Next year: 30.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'On a standardized test, the 75th percentile corresponds to a score of 700, and the 25th percentile corresponds to a score of 450.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'd', 'Without knowing the distribution shape, the 95th percentile cannot be calculated.', 'A 95th percentile score', '800', 'On a standardized test, the 75th percentile corresponds to a score of 700, and the 25th percentile corresponds to a score of 450.', 'easy', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'If the radius of a circle is doubled, the new area is how many times the original?', '[{"id": "a", "text": "2"}, {"id": "b", "text": "3"}, {"id": "c", "text": "4"}, {"id": "d", "text": "5"}, {"id": "e", "text": "8"}]'::jsonb, 'c', 'Area scales by $r^2$. $(2r)^2 = 4r^2$. 4 times.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'The length of a rectangle is 2 more than twice its width. The area is 40. What is the perimeter of the rectangle?', '[{"id": "a", "text": "20"}, {"id": "b", "text": "26"}, {"id": "c", "text": "28"}, {"id": "d", "text": "32"}, {"id": "e", "text": "36"}]'::jsonb, 'c', '$w = 4$, $l = 10$. Perimeter $= 2(10+4) = 28$.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'In a figure, $ZW = 3$, $XZ = 6$, and $YZ = 5$. Triangle $XYW$ is a right triangle with the right angle at $W$. Point $Z$ lies on $XW$ between $X$ and $W$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'By Pythagorean theorem: $YW = 4$. Area $= (1/2)(6)(4) = 12$.', 'The area of triangle $XYZ$', '12', '$ZW = 3$, $XZ = 6$, $YZ = 5$. Right angle at $W$.', 'easy', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'If the average of $n$ and 11 is $2n$, what is the average of $n$ and $13/3$?', NULL, '4', '$n = 11/3$. Average of $11/3$ and $13/3$: $(24/3)/2 = 4$.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A store sold three times as many jeans as chinos. The profit for a pair of chinos is twice the profit for a pair of jeans.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Chinos profit share: $2np/5np = 40\%$.', 'Percent of total profit from chinos', '40%', 'A store sold three times as many jeans as chinos. The profit for a pair of chinos is twice the profit for a pair of jeans.', 'easy', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Two sides of an isosceles triangle are 2 and 11.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Only valid triangle: 11, 11, 2. Perimeter = 24.', 'The perimeter of the triangle', '24', 'Two sides of an isosceles triangle are 2 and 11.', 'easy', 2, 4, 'quantitative', true, NULL, true),
('multi-select', 'Which of the following points lie on the line $y = 2x - 8$? Indicate all such points.', '[{"id": "a", "text": "$(3, -2)$"}, {"id": "b", "text": "$(0, -8)$"}, {"id": "c", "text": "$(4, 0)$"}, {"id": "d", "text": "$(-8, 0)$"}]'::jsonb, '["a","b","c"]', 'A, B, C satisfy the equation. D does not.', NULL, NULL, NULL, 'easy', 2, 4, 'quantitative', true, NULL, true);
