-- GRE questions: set 5, section 2, difficulty hard
-- Total rows: 15
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('numeric-entry', 'Data: Student GPA Distribution in 1950 (3,000 total) — 4.0: 410, 3.7: 300, 3.3: 320, 3.0: 480, 2.7: 420, 2.3: 450, 2.0: 500. In 1950, what was the total number of students who earned a GPA of 2.7 or lower?', NULL, '1370', '$420 + 450 + 500 = 1370$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Line segments $AC$ and $BD$ are parallel. Points $W$, $Z$ on $AC$; points $X$, $Y$ on $BD$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'd', 'Without exact positions, cannot determine.', 'The area of triangle $WYX$', 'The area of triangle $WZX$', 'Parallel lines $AC$ and $BD$.', 'hard', 2, 5, 'quantitative', true, 'https://dxhxpfouzjlzpeazwrqo.supabase.co/storage/v1/object/public/gre-question-images/07b47ef4-b10c-4a33-b5be-37d616ef05c0.png', true),
('single-choice', 'Data: Student GPA Distribution in 2000 (3,000 total) — 4.0: 550, 3.7: 620, 3.3: 450, 3.0: 350, 2.7: 300, 2.3: 150, 2.0: 80. What was the mode for GPA of the 3,000 students in 2000?', '[{"id": "a", "text": "4.0"}, {"id": "b", "text": "3.7"}, {"id": "c", "text": "3.3"}, {"id": "d", "text": "3.0"}]'::jsonb, 'b', '3.7 has highest count (620). Mode = 3.7.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Five students are arranged in a line. How many arrangements are possible if Beth is not allowed to stand next to Dan?', '[{"id": "a", "text": "24"}, {"id": "b", "text": "48"}, {"id": "c", "text": "72"}, {"id": "d", "text": "96"}, {"id": "e", "text": "120"}]'::jsonb, 'c', 'Total $120 - 48 = 72$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('multi-select', 'If $3^x(5^2)$ is divided by $3^5(5^3)$, the quotient terminates with one decimal digit. If $x > 0$, which must be true? Indicate all.', '[{"id": "a", "text": "$x = 5$"}, {"id": "b", "text": "$x \\geq 5$"}, {"id": "c", "text": "$x$ is even"}]'::jsonb, '["a","b"]', 'Quotient = $3^{x-5}/5$. For one decimal digit, $x = 5$. Both A and B hold.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Parabola $y = (x - h)^2 + k$ has vertex at $(2, 0)$. Point $(-3, n)$ lies on it.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$n = (-3-2)^2 = 25$. Equal.', '$n$', '25', 'Parabola vertex $(2,0)$, point $(-3,n)$ on it.', 'hard', 2, 5, 'quantitative', true, NULL, true),
('multi-select', 'If $x$ is the $y$-intercept of $y = -(x - 1)^2 + 4$, which is true? Indicate all such statements.', '[{"id": "a", "text": "$x$ is prime"}, {"id": "b", "text": "$x$ is odd"}, {"id": "c", "text": "$x > 0$"}]'::jsonb, '["a","b","c"]', '$y$-intercept = 3. Prime, odd, and positive. All true.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'Car A travels at 8 mph faster than Car B. They cover 62 miles total. Car B drove 15 minutes; Car A started 30 minutes before Car B. How many miles had Car B driven?', NULL, '14', '$r = 56$. Car B distance = $56 \\times 0.25 = 14$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A right triangle is inscribed in a circle with an area of $16\\pi$ sq cm.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$r = 4$, diameter = 8. Hypotenuse = diameter = 8. Equal.', 'The length of the hypotenuse', '8', 'Right triangle inscribed in circle with area $16\\pi$.', 'hard', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'A solid cylinder has height 9 and radius 2. It is cut into three equal-height cylinders. What is the ratio of total new SA to original SA?', '[{"id": "a", "text": "1:1"}, {"id": "b", "text": "3:2"}, {"id": "c", "text": "13:11"}, {"id": "d", "text": "15:11"}]'::jsonb, 'd', 'Original SA = $44\\pi$. Total new SA = $60\\pi$. Ratio = 15:11.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'If the width of a rectangle $w$ is twice the length, and the area is 72, what is $w$?', NULL, '12', '$w = 2L$, $2L^2 = 72$, $L = 6$, $w = 12$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Events $A$ and $B$ are independent. $P(A) = 0.6$, $P(B) = 0.8$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$P(\\text{neither}) = 0.4 \\times 0.2 = 0.08$. Equal.', 'The probability that neither event occurs', '0.08', 'Independent events, $P(A)=0.6$, $P(B)=0.8$.', 'hard', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'A batch of widgets costs $p + 15$ dollars to produce and sells for $p(9 - p)$ dollars. For which value of $p$ does the company make a profit?', '[{"id": "a", "text": "3"}, {"id": "b", "text": "4"}, {"id": "c", "text": "5"}, {"id": "d", "text": "6"}]'::jsonb, 'b', '$(p-3)(p-5) < 0$ for $3 < p < 5$. Only $p = 4$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Data: Student GPA Distribution in 2000 (3,000 total) — 4.0: 550, 3.7: 620, 3.3: 450, 3.0: 350, 2.7: 300, 2.3: 150, 2.0: 80. Approximately what percent of students in 2000 earned at least a 3.0 GPA?', '[{"id": "a", "text": "50%"}, {"id": "b", "text": "67%"}, {"id": "c", "text": "80%"}, {"id": "d", "text": "95%"}]'::jsonb, 'b', '$1970/3000 \\approx 67\\%$.', NULL, NULL, NULL, 'hard', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', '$x$ and $y$ are positive integers such that $x^2 \\cdot 5^y = 10125$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', '$10125 = 5^3 \\times 9^2$. $x^2 = 81$, $5^y = 125$. $81 < 125$. B is greater.', '$x^2$', '$5^y$', '$x^2 \\cdot 5^y = 10125$, positive integers.', 'hard', 2, 5, 'quantitative', true, NULL, true);
