-- GRE questions: set 5, section 2, difficulty medium
-- Total rows: 15
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('single-choice', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. What is the ratio of female Basketball players to female Track and Field players?', '[{"id": "a", "text": "15:61"}, {"id": "b", "text": "24:37"}, {"id": "c", "text": "1:4"}, {"id": "d", "text": "1:3"}]'::jsonb, 'a', 'Ratio = 15:61.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'A bag of snack mix contains 3oz pretzels, 1oz chocolate, and 2oz nuts. $x$ ounces of dried fruit are added. What percent of the mix is dried fruit?', '[{"id": "a", "text": "$x/(6+x) \\cdot 100$"}, {"id": "b", "text": "$100x/6$"}, {"id": "c", "text": "$x/600$"}, {"id": "d", "text": "$100/(6x)$"}]'::jsonb, 'a', 'Total = $6+x$. Percent = $x/(6+x) \\times 100$.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'The total cost of 3 bananas, 2 apples, and 1 mango is \$3.50. The cost of 3 bananas, 2 apples, and 1 papaya is \$4.20. The ratio of mango to papaya cost is 3:5. What is the cost of a mango?', '[{"id": "a", "text": "$0.60"}, {"id": "b", "text": "$0.90"}, {"id": "c", "text": "$1.05"}, {"id": "d", "text": "$1.50"}]'::jsonb, 'c', '$P - M = 0.70$. $M:P = 3:5$. $k = 0.35$. Mango = $1.05.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. How many more female athletes are in Track and Field than in all other sports combined?', NULL, '-2', 'Others = 63. Track/Field = 61. Difference = -2.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'In a barter system, 1 sack of rice = 2.5 lbs of beans OR $1/3$ bushel of tomatoes.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', '1 lb beans = 0.4 sacks. 1 bushel tomatoes = 3 sacks. B is greater.', 'Sacks of rice for 1 lb of beans', 'Sacks of rice for 1 bushel of tomatoes', '1 sack = 2.5 lbs beans OR 1/3 bushel tomatoes.', 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Kurt is behind 200 people in line. 4 people board every 15 seconds. How many minutes until Kurt boards the coaster?', '[{"id": "a", "text": "8"}, {"id": "b", "text": "10"}, {"id": "c", "text": "12.5"}, {"id": "d", "text": "15"}]'::jsonb, 'c', '16 people/min. $200/16 = 12.5$ minutes.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. If 11 males are on both Track/Field and Cross Country, what percent of male Cross Country athletes are also on the Track team?', '[{"id": "a", "text": "45%"}, {"id": "b", "text": "55%"}, {"id": "c", "text": "65%"}, {"id": "d", "text": "75%"}]'::jsonb, 'c', '$11/17 \\approx 65\\%$.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'Two lines intersect such that 35 degrees is one of the angles. What is the sum of the other three angles?', NULL, '325', '$360 - 35 = 325$.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'A shirt costs $k$ dollars. It increases by 30%, then by an additional 50%. What is the coefficient of $k$ in the new price?', NULL, '1.95', '$1.30k \\times 1.50 = 1.95k$. Coefficient = 1.95.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A line has a slope of $-2$ and passes through the point $(4, 9)$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$y = -2x + 17$. Y-intercept = 17. Equal.', 'The $y$-intercept of the line', '17', 'Slope $-2$, through $(4,9)$.', 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'A circle is inscribed in a square that has an area of 50. What is the area of the circle?', '[{"id": "a", "text": "$12.5\\pi$"}, {"id": "b", "text": "$25\\pi$"}, {"id": "c", "text": "$50\\pi$"}, {"id": "d", "text": "$625\\pi/16$"}]'::jsonb, 'a', 'Radius = $\\sqrt{50}/2$. Area = $12.5\\pi$.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Francisco''s MP3 player (64GB) was 3/4 full. He deleted 25% of the data, then saved 20GB of new data.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Initial: 48GB. After delete: 36GB. After save: 56GB. 56/64 = 87.5%. Equal.', 'Final data as a percent of capacity', '87.5%', '64GB player, 3/4 full, deleted 25%, saved 20GB.', 'medium', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Two distinct lines intersect at a single point, forming four angles. One of the angles measures $a$ degrees, where $a > 90$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'At an intersection, opposite (vertical) angles are equal. The angle opposite $a$ is also $a$. The two adjacent angles are each $180 - a$. Sum of adjacent angles: $2(180 - a) = 360 - 2a$. This equals Quantity B. The two quantities are equal.', 'The sum of the two angles adjacent to the $a$-degree angle', '$360 - 2a$', 'Two lines intersect at a point. One angle is $a$ degrees, $a > 90$.', 'medium', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Last year a magazine charged \$50 per subscription. This year the price increases by \$10. If the magazine loses 4 subscribers but collects the same revenue, how many subscribers were there last year?', '[{"id": "a", "text": "20"}, {"id": "b", "text": "21"}, {"id": "c", "text": "24"}, {"id": "d", "text": "25"}]'::jsonb, 'c', '$50n = 60(n-4)$. $n = 24$.', NULL, NULL, NULL, 'medium', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'In a figure, $XZ = 6$, $ZW = 3$, $YZ = 5$. Angle $XWY$ is 90 degrees. Point $Z$ lies on $XW$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$YW = 4$. Area = $(1/2)(6)(4) = 12$. Equal.', 'The area of triangle $XYZ$', '12', '$XZ=6$, $ZW=3$, $YZ=5$, right angle at $W$.', 'medium', 2, 5, 'quantitative', true, NULL, true);
