-- GRE questions: set 4, section 2, difficulty hard
-- Total rows: 14
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('single-choice', 'A city has a $1/3$ chance of rain on any given day. What is the probability it rains at least once in a 3-day period?', '[{"id": "a", "text": "$1/3$"}, {"id": "b", "text": "$8/27$"}, {"id": "c", "text": "$19/27$"}, {"id": "d", "text": "$1$"}]'::jsonb, 'c', 'P(no rain 3 days) = $(2/3)^3 = 8/27$. P(at least once) = $1 - 8/27 = 19/27$.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('multi-select', 'If $k$ is the sum of the reciprocals of consecutive integers from 41 to 60 inclusive, which of the following are less than $k$? Indicate all such values.', '[{"id": "a", "text": "$1/4$"}, {"id": "b", "text": "$1/3$"}, {"id": "c", "text": "$1/2$"}]'::jsonb, '["a"]', 'Lower bound: $20/60 = 1/3$. Upper bound: $20/41 \\approx 0.49$. Only $1/4$ is less than $k$.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', NULL, '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', '$100000 = 2^5 \\cdot 5^5$ (2 primes). $99000 = 2^3 \\cdot 3^2 \\cdot 5^3 \\cdot 11$ (4 primes). B is greater.', 'The number of distinct prime factors of 100,000', 'The number of distinct prime factors of 99,000', NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A 2-foot by 2-foot by 2-foot solid cube is cut into 2-inch by 2-inch by 4-inch rectangular solids.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'a', '864 small solids, each SA = 40. Total SA = 34560. Original SA = 3456. Ratio = 10 > 8.', 'The ratio of total surface area of all small solids to the surface area of the original cube', '8', 'A 2-foot cube cut into 2x2x4 inch solids.', 'hard', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Data: Owner-Occupied Housing by Household Size (75,986,074 total) — 1-person: 25.6%, 2-person: 34%, 3-person: 14.5%, 5-person: 6.4%, Other: 11.1%. What
  percent of owner-occupied housing units are households with 4 or more people?', '[{"id": "a", "text": "11.1%"}, {"id": "b", "text": "25.6%"}, {"id": "c", "text": "41.0%"}, {"id": "d", "text": "74.4%"}]'::jsonb, 'b', 'Fewer than 4: approximately 74.5%. So 4+: approximately 25.5%, closest to 25.6%.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Lines $j$ and $k$ intersect at $(1, 3)$. Line $j$: $y = ax + 10$ and Line $k$: $y = bx + a$. What is the value of $b$?', NULL, '10', '$a = -7$. Then $3 = b - 7$, so $b = 10$.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'In triangle $ADC$, point $B$ lies on $AC$, with $AB = BD = DC$. If angle $C = 66$ degrees, what is the value of angle $x$ at vertex $A$?', '[{"id": "a", "text": "11"}, {"id": "b", "text": "22"}, {"id": "c", "text": "33"}, {"id": "d", "text": "44"}]'::jsonb, 'c', 'Isosceles triangle BDC: angle DBC = 66. Isosceles ABD: 66 = 2x, x = 33.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('multi-select', 'Which of the following values, when multiplied by 12, is NOT a multiple of 64? Indicate all such values.', '[{"id": "a", "text": "$6^6$"}, {"id": "b", "text": "$12^2$"}, {"id": "c", "text": "$18^3$"}, {"id": "d", "text": "$30^3$"}]'::jsonb, '["c","d"]', '12 provides $2^2$. Need $2^4$ more. $18^3$ and $30^3$ only provide $2^3$. Not enough.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Data: Owner-Occupied Housing by Household Size (75,986,074 total) — 1-person: 25.6%, 2-person: 34%, 5-person: 6.4%, Other: 11.1%. Approximately how many 
  households are 5-person households?  ', '[{"id": "a", "text": "2 million"}, {"id": "b", "text": "3 million"}, {"id": "c", "text": "4 million"}, {"id": "d", "text": "5 million"}]'::jsonb, 'd', '$0.064 \\times 76,000,000 \\approx 4,864,000 \\approx 5$ million.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Line $p$ is defined by $3y - 9x = 9$. Which of the following is true?', '[{"id": "a", "text": "Slope > x-intercept"}, {"id": "b", "text": "Slope = x-intercept"}, {"id": "c", "text": "Slope < x-intercept"}]'::jsonb, 'a', '$y = 3x + 3$. Slope = 3, x-intercept = -1. $3 > -1$.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'An inventory contains 100 different coins.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'By symmetry: C(100,56) = C(100,44). Equal.', 'The number of possible collections of 56 coins that can be selected', 'The number of possible collections of 44 coins that can be selected', 'An inventory contains 100 different coins.', 'hard', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'A polygon has 12 edges. How many different diagonals does it have?', NULL, '54', '$n(n-3)/2 = 12(9)/2 = 54$.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Data: Owner-Occupied Housing by Household Size (75,986,074 total) — 1-person: 25.6%, 2-person: 34%, 5-person: 6.4%, Other (4+ person): 11.1%. If the     
  total number of households increases by 10%, but the percentage of 1-person households remains the same, how many 1-person households will there be (in  
  millions)?', NULL, '21.4', 'New total = 83.6M. $0.256 \\times 83.6 \\approx 21.4$ million.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'A figure is divided into 5 squares of equal area arranged in an L-shape. If the total area is 45, what is the perimeter of the entire figure?', NULL, '36', 'Each square side = 3. 12 outer edges. Perimeter = 36.', NULL, NULL, NULL, 'hard', 2, 4, 'quantitative', true, NULL, true);
