-- GRE questions: set 4, section 2, difficulty medium
-- Total rows: 15
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('quantitative-comparison', 'Rock sample weights are normally distributed. One standard deviation below the mean is 250g and one standard deviation above is 420g.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Mean = median = $(250+420)/2 = 335$g. Equal.', 'The median weight in grams', '335 grams', 'Normally distributed. 1 SD below = 250g, 1 SD above = 420g.', 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. Which sport has the largest     
  total roster (Male + Female combined)?', '[{"id": "a", "text": "Basketball"}, {"id": "b", "text": "Track and Field"}, {"id": "c", "text": "Volleyball"}, {"id": "d", "text": "Cross Country"}]'::jsonb, 'b', 'Track and Field: 37+61 = 98. Largest.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'How many 10-digit numbers can be formed using only the digits 2 and 5?', '[{"id": "a", "text": "$2^{10}$"}, {"id": "b", "text": "$10!$"}, {"id": "c", "text": "$(5!)(5!)$"}, {"id": "d", "text": "$10!/2$"}]'::jsonb, 'a', '2 choices per digit, 10 digits: $2^{10}$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'In a school of 150 students, 75 study Latin, 110 study Spanish, and 11 study neither.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', 'Both = 46. Only Latin = 75 - 46 = 29. 29 < 46.', 'The number of students who study ONLY Latin', '46', '150 students, 75 Latin, 110 Spanish, 11 neither.', 'medium', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', '$a$, $b$, and $c$ are positive constants.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Both equal $c(a+b)/100$. Identical expressions.', '$(a + b)$% of $c$', '$c$% of $(a + b)$', '$a$, $b$, $c$ are positive constants.', 'medium', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'Sector $OAB$ is a quarter-circle. The central angle of $90$ degrees is divided into three parts: $2x$, $3x$, and $x$ degrees.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$6x = 90$, so $x = 15$. Equal.', '$x$', '15', 'Quarter-circle with central angle split into $2x$, $3x$, and $x$ degrees.', 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Mason is now twice as old as Gunther was 10 years ago. If $G$ is Gunther''s current age, which represents the sum of their ages 4 years from now?', '[{"id": "a", "text": "$3G - 12$"}, {"id": "b", "text": "$3G + 28$"}, {"id": "c", "text": "$3G - 20$"}, {"id": "d", "text": "$8 - G$"}]'::jsonb, 'a', '$M = 2(G-10) = 2G - 20$. Sum in 4 years: $(2G-16) + (G+4) = 3G - 12$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'A 6-sided die is rolled twice. What is the probability that the sum is exactly 8?', '[{"id": "a", "text": "$1/9$"}, {"id": "b", "text": "$1/8$"}, {"id": "c", "text": "$5/36$"}, {"id": "d", "text": "$1/6$"}]'::jsonb, 'c', '5 outcomes sum to 8 out of 36 total. $P = 5/36$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Jarod uses $2/3$ of an ounce of vinegar for every 2 cups of sushi rice. How many ounces of vinegar does he need for 7 cups of rice?', NULL, '2.33', 'Rate = 1/3 oz per cup. $7 \\times 1/3 = 7/3 \\approx 2.33$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. If there are 76 unique male     
  athletes, how many are on both Track/Field and Cross Country? ', NULL, '11', 'Sum = 87. Unique = 76. Overlap = 87 - 76 = 11.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', '16 ounces of birdseed contains 10% sesame. How much sesame must be added to produce a 20% sesame mix?', '[{"id": "a", "text": "1 ounce"}, {"id": "b", "text": "1.6 ounces"}, {"id": "c", "text": "2 ounces"}, {"id": "d", "text": "2.4 ounces"}]'::jsonb, 'c', '$(1.6 + x)/(16 + x) = 0.20$. Solving: $x = 2$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'Data: Sport | Male | Female: Volleyball 0, 16; Track/Field 37, 61; Tennis 9, 9; Cross Country 17, 23; Basketball 24, 15. What is the ratio of male
  athletes to female athletes on the Track and Field roster?', '[{"id": "a", "text": "$37/61$"}, {"id": "b", "text": "$14/9$"}, {"id": "c", "text": "$61/37$"}, {"id": "d", "text": "$17/23$"}]'::jsonb, 'a', 'Male: 37, Female: 61. Ratio = 37/61.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A team of 8 chefs produce 3,200 tarts in 5 days at a constant rate.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Rate = 80 tarts/chef/day. Qty A: 15 chefs. Qty B: 15 days. Equal.', 'The number of chefs needed to produce 3,600 tarts in 3 days', 'The number of days that 4 chefs need to produce 4,800 tarts', '8 chefs produce 3,200 tarts in 5 days at constant rate.', 'medium', 2, 4, 'quantitative', true, NULL, true),
('single-choice', 'A circle with center $O$ has a circumference of $12\\pi\\sqrt{3}$. $AC$ is a diameter and angle $ACB = 30$ degrees. Find the length of $AB$.', '[{"id": "a", "text": "$3\\sqrt{2}$"}, {"id": "b", "text": "6"}, {"id": "c", "text": "$6\\sqrt{3}$"}, {"id": "d", "text": "18"}]'::jsonb, 'd', 'Diameter = $12\\sqrt{3}$. Angle B = 90 (subtends diameter). 30-60-90 triangle. $AB = 18$.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true),
('numeric-entry', 'Chocolate chip cookies are made in batches of 7 and peanut butter in batches of 6. If 95 total cookies were made, what is the minimum number of chocolate chip cookies?', NULL, '35', '$7(5) + 6(10) = 95$. Min chocolate chip = 35.', NULL, NULL, NULL, 'medium', 2, 4, 'quantitative', true, NULL, true);
