-- GRE questions: set 5, section 1, difficulty medium
-- Total rows: 11
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('single-choice', 'When $n$ is an integer and $n^3$ is divisible by 24, what is the largest number that MUST be a factor of $n$?', '[{"id": "a", "text": "2"}, {"id": "b", "text": "4"}, {"id": "c", "text": "6"}, {"id": "d", "text": "8"}, {"id": "e", "text": "12"}]'::jsonb, 'c', '$n$ must be divisible by 2 and 3. Largest guaranteed factor is 6.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', '$x > y$ and $xy \\neq 0$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'd', 'Depends on signs of $x$ and $y$. Cannot be determined.', '$\\dfrac{x^2}{y + 1/y}$', '$\\dfrac{y^2}{x + 1/x}$', '$x > y$ and $xy \\neq 0$.', 'medium', 1, 5, 'quantitative', true, NULL, true),
('single-choice', 'If $\\sqrt[3]{x^6} = x^{a/b}$, what is the value of $a/b$?', '[{"id": "a", "text": "$1/2$"}, {"id": "b", "text": "$2/3$"}, {"id": "c", "text": "2"}, {"id": "d", "text": "3"}, {"id": "e", "text": "6"}]'::jsonb, 'c', '$(x^6)^{1/3} = x^2$. So $a/b = 2$.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'If $x$ is even, $\\sqrt{x}$ is a prime number, and $x + y = 11$, what is the value of $y$?', NULL, '7', '$\\sqrt{x} = 2$, $x = 4$, $y = 7$.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('multi-select', 'If $|-x| \\geq 6$ and $xy^2 < 0$, which of the following could be the value of $x$? Indicate all such values.', '[{"id": "a", "text": "$-10$"}, {"id": "b", "text": "$-6$"}, {"id": "c", "text": "$0$"}, {"id": "d", "text": "$6$"}, {"id": "e", "text": "$10$"}]'::jsonb, '["a","b"]', '$|x| \\geq 6$ and $x < 0$. So $x \\leq -6$. Values: $-10$ and $-6$.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('multi-select', '$a, b, c$ are consecutive integers such that $a < b < c < 4$. Which of the following could be the average of $a, b,$ and $c$? Indicate all such values.', '[{"id": "a", "text": "0"}, {"id": "b", "text": "1"}, {"id": "c", "text": "2"}, {"id": "d", "text": "3"}]'::jsonb, '["a","b","c"]', 'Average = middle term $b$. Max $c = 3$. Possible: $b = 0, 1, 2$.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'On a number line, 0 and 2 are marked. The value $\\sqrt[3]{p}$ is exactly halfway between them.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', 'Halfway = 1. $\\sqrt[3]{p} = 1$, so $p = 1 < 1.5$.', '$p$', '1.5', '$\\sqrt[3]{p}$ is halfway between 0 and 2.', 'medium', 1, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', '$n = 10!$ is divisible by $3^x \\cdot 5^y$, where $x$ and $y$ are positive integers.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Max $x = 4$. Max $y = 2$. Twice $y = 4$. Equal.', 'The greatest possible value for $x$', 'Twice the greatest possible value for $y$', '$n = 10!$ divisible by $3^x \\cdot 5^y$.', 'medium', 1, 5, 'quantitative', true, NULL, true),
('single-choice', 'What is the greatest prime factor of $2^{99} - 2^{96}$?', '[{"id": "a", "text": "2"}, {"id": "b", "text": "3"}, {"id": "c", "text": "5"}, {"id": "d", "text": "7"}, {"id": "e", "text": "11"}]'::jsonb, 'd', '$2^{96}(2^3 - 1) = 2^{96} \\cdot 7$. Greatest prime factor is 7.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'If $3^{11} = 9^x$, what is the value of $x$?', NULL, '5.5', '$3^{11} = 3^{2x}$, so $x = 5.5$.', NULL, NULL, NULL, 'medium', 1, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A line in the $xy$-plane passes through the points $(2, 3)$ and $(k, 11)$. The slope of the line is 4.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Slope = $8/(k-2) = 4$, so $k = 4$. Equal.', '$k$', '4', 'Line through $(2,3)$ and $(k,11)$ with slope 4.', 'medium', 1, 5, 'quantitative', true, NULL, true);
