-- GRE questions: set 5, section 2, difficulty easy
-- Total rows: 15
-- Auto-generated for prod insert

INSERT INTO gre_questions (type, prompt, options, correct_answer, explanation, quantity_a, quantity_b, quantity_info, difficulty_tier, section_number, set_number, section_type, is_active, image_url, qc_done)
VALUES
('quantitative-comparison', 'A species of insect has an average mass of 5.2g and a standard deviation of 0.6g (normally distributed).', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'a', 'Qty A spans 0 to +1 SD (~34.1%). Qty B spans -0.5 to +0.5 SD. Qty A is greater.', 'Percent of insects between 5.2g and 5.8g', 'Percent of insects between 4.9g and 5.5g', 'Mean 5.2g, SD 0.6g, normally distributed.', 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Data: Winnemucca Days 90°F+ — June: 2, July: 16, August: 8, September: 2. What was the total number of days in the year that Winnemucca reached these temperatures?', '[{"id": "a", "text": "22"}, {"id": "b", "text": "28"}, {"id": "c", "text": "34"}, {"id": "d", "text": "42"}, {"id": "e", "text": "59"}]'::jsonb, 'b', '$2 + 16 + 8 + 2 = 28$.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'John bought 5 books for an average of \$12 each. If he buys a 6th book for \$18, what is the new average price?', '[{"id": "a", "text": "$13"}, {"id": "b", "text": "$14"}, {"id": "c", "text": "$15"}, {"id": "d", "text": "$16"}, {"id": "e", "text": "$17"}]'::jsonb, 'a', 'Total = $78. Average = $78/6 = $13.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'In July, Galveston had approximately 23 days with max temperature 90F or more. What percent of July does this represent?', '[{"id": "a", "text": "55%"}, {"id": "b", "text": "68%"}, {"id": "c", "text": "74%"}, {"id": "d", "text": "82%"}, {"id": "e", "text": "95%"}]'::jsonb, 'c', '$23/31 \\approx 74\\%$.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Data: St. Louis Freezing Days — Jan: 27, Feb: 22, Mar: 11, Apr: 2, Oct: 5, Nov: 16, Dec: 24. In how many months did St. Louis have more than 15 freezing days?', '[{"id": "a", "text": "2"}, {"id": "b", "text": "3"}, {"id": "c", "text": "4"}, {"id": "d", "text": "5"}, {"id": "e", "text": "6"}]'::jsonb, 'c', 'Jan (27), Feb (22), Nov (16), Dec (24). 4 months.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'If the average of $n$ and 11 is $2n$, what is the value of $n$? (Round to two decimal places.)', NULL, '3.67', '$n = 11/3 \\approx 3.67$.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Marcy bought jeans at 70% off and a blouse at 40% off. She paid \$12 more for the blouse and spent \$84 total. What was the original price of the jeans?', '[{"id": "a", "text": "$76"}, {"id": "b", "text": "$96"}, {"id": "c", "text": "$100"}, {"id": "d", "text": "$120"}, {"id": "e", "text": "$140"}]'::jsonb, 'd', 'Sale price of jeans = $36. Original = $36/0.30 = $120.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Which of the following points lies on the line $y = 2x - 8$?', '[{"id": "a", "text": "$(3, -2)$"}, {"id": "b", "text": "$(2, 4)$"}, {"id": "c", "text": "$(0, 8)$"}, {"id": "d", "text": "$(-8, 0)$"}, {"id": "e", "text": "$(5, 1)$"}]'::jsonb, 'a', '$2(3) - 8 = -2$. Point $(3,-2)$ satisfies.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A set of numbers $N$ is multiplied by $-3$ to create a new set.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'a', 'SD multiplied by $|-3| = 3$. New SD is 3x larger. ', 'The standard deviation of the new set', 'The standard deviation of set $N$', 'Set $N$ multiplied by $-3$.', 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'Wall-to-wall carpeting costs $4.25 per square foot. How much will it cost to carpet a hallway that is 4 feet wide and 15 feet long?', '[{"id": "a", "text": "$60"}, {"id": "b", "text": "$170"}, {"id": "c", "text": "$240"}, {"id": "d", "text": "$255"}, {"id": "e", "text": "$300"}]'::jsonb, 'd', 'Area = 60 sq ft. Cost = $60 \\times 4.25 = $255.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('numeric-entry', 'A hallway is 6 feet by 8 feet. How many 2-foot by 2-foot square tiles are needed to cover it?', NULL, '12', '$48/4 = 12$ tiles.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A circle is inscribed in a square that has an area of 50.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', 'Radius = $\\sqrt{50}/2$. Area = $12.5\\pi$. Equal.', 'The area of the circle', '$12.5\\pi$', 'Circle inscribed in square with area 50.', 'easy', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'In a triangle with angles $x$, $y$, and $z$ degrees, $x + z = 110$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'c', '$y = 180 - 110 = 70$. Equal.', '$y$', '70', 'Triangle with $x + z = 110$.', 'easy', 2, 5, 'quantitative', true, NULL, true),
('single-choice', 'A circle with an area of $4\\pi$ has its radius doubled. What is the new area?', '[{"id": "a", "text": "$8\\pi$"}, {"id": "b", "text": "$12\\pi$"}, {"id": "c", "text": "$16\\pi$"}, {"id": "d", "text": "$32\\pi$"}, {"id": "e", "text": "$64\\pi$"}]'::jsonb, 'c', '$r = 2$, new $r = 4$. New area = $16\\pi$.', NULL, NULL, NULL, 'easy', 2, 5, 'quantitative', true, NULL, true),
('quantitative-comparison', 'A line has a slope of $-2$ and passes through the points $(4, 9)$ and $(6, y)$.', '[{"id": "a", "text": "Quantity A is greater"}, {"id": "b", "text": "Quantity B is greater"}, {"id": "c", "text": "The two quantities are equal"}, {"id": "d", "text": "The relationship cannot be determined"}]'::jsonb, 'b', '$y = 5 < 6$. Quantity B is greater.', '$y$', '6', 'Line with slope $-2$ through $(4,9)$ and $(6,y)$.', 'easy', 2, 5, 'quantitative', true, NULL, true);
