-- Practice-mode math from lid_034.tex (sat_lid_034)
-- Chapter: Distributions, measures of center/spread | Topic: Mean, Median, Mode, Range
-- sat_questions: section=math, domain=problem-solving, bank_item_id=sat_lid_034_N, practice module/set 0.

INSERT INTO public.sat_questions (
  type,
  section,
  prompt,
  options,
  correct_answer,
  explanation,
  domain,
  difficulty_tier,
  module_number,
  set_number,
  bank_item_id,
  chapter,
  subtopic
)
VALUES
  (
  'mcq',
  'math',
  '4, 10, 18, 4, 4, 5, 6, 5 What is the median of the data set shown?',
  '[{"id":"a","text":"4"},{"id":"b","text":"5"},{"id":"c","text":"7"},{"id":"d","text":"14"}]'::jsonb,
  'b',
  '\\textbf{Conceptual Explanation:}

The median is the middle value of an ordered data set. For an even number of values, it is the average of the two middle terms.

\\textbf{Calculation and Logic:}

1. \\textbf{Order the data:} 4, 4, 4, 5, 5, 6, 10, 18.

2. \\textbf{Identify middle pair:} The 4th and 5th values are 5 and 5.

3. \\textbf{Average:} $(5+5)/(2) = 5$.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_1',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  '2, 2, 2, 3, 4, 4, 11 What is the median of the seven data values shown?',
  '[{"id":"a","text":"2"},{"id":"b","text":"3"},{"id":"c","text":"4"},{"id":"d","text":"9"}]'::jsonb,
  'b',
  '\\textbf{Calculation and Logic:}

The data is ordered: 2, 2, 2, \\textbf{3}, 4, 4, 11. The middle value (4th position) is 3.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_2',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'The box plots summarize the masses, in kilograms, of two groups of gazelles. Based on the box plots, which of the following statements must be true?',
  '[{"id":"a","text":"The mean mass of group 1 is greater than the mean mass of group 2."},{"id":"b","text":"The mean mass of group 1 is less than the mean mass of group 2."},{"id":"c","text":"The median mass of group 1 is greater than the median mass of group 2."},{"id":"d","text":"The median mass of group 1 is less than the median mass of group 2."}]'::jsonb,
  'c',
  '\\textbf{Calculation and Logic:}

1. Group 1 Median: 25 kg.

2. Group 2 Median: 24 kg.

3. Since $25 > 24$, the median of Group 1 is greater.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_3',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Ages of 20 Students Enrolled in a College Class \\begin{center} \\begin{tabular}{|c|c|} \\hline Age & Frequency \\hline 18 & 6 \\hline 19 & 5 \\hline 20 & 4 \\hline 21 & 2 \\hline 22 & 1 \\hline 23 & 1 \\hline 30 & 1 \\hline \\end{tabular} \\end{center} Which of the following gives the correct order of the mean, median, and mode of the ages?',
  '[{"id":"a","text":"mode $<$ median $<$ mean"},{"id":"b","text":"mode $<$ mean $<$ median"},{"id":"c","text":"median $<$ mode $<$ mean"},{"id":"d","text":"mean $<$ mode $<$ median"}]'::jsonb,
  'a',
  '\\textbf{Calculation:}

1. \\textbf{Mode:} 18 (highest frequency).

2. \\textbf{Median:} 10th and 11th values are both 19.

3. \\textbf{Mean:} $((18\\cdot6)+(19\\cdot5)+(20\\cdot4)+(21\\cdot2)+22+23+30)/(20) = (400)/(20) = 20$.

Comparison: $18 < 19 < 20$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_4',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Data set A: 72, 73, 73, 76, 76 Data set B: 61, 64, 74, 85, $x$ If the mean of data set A is equal to the mean of data set B, what is the value of $x$?',
  '[{"id":"a","text":"77"},{"id":"b","text":"85"},{"id":"c","text":"86"},{"id":"d","text":"95"}]'::jsonb,
  'c',
  '\\textbf{Calculation:}

Sum A = 370. Sum B must be 370.

$61+64+74+85+x = 370 → 284+x=370 → x=86$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_5',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Men''s Height: Group A (Mean 186, SD 12.5), Group B (Mean 186, SD 19.1). Which statement is true?',
  '[{"id":"a","text":"The Group A data set was identical to the Group B data set."},{"id":"b","text":"Group B contained the tallest participant."},{"id":"c","text":"Heights in Group B had a larger spread than in Group A."},{"id":"d","text":"The median height of Group B is larger than Group A."}]'::jsonb,
  'c',
  '\\textbf{Logic:} Standard deviation measures spread. Group B (19.1) $>$ Group A (12.5), so Group B has a larger spread.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_6',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Adding 7 to numbers above the median and subtracting 7 from numbers below the median. Which measure changes?',
  '[{"id":"a","text":"Median"},{"id":"b","text":"Mean"},{"id":"c","text":"Sum of numbers"},{"id":"d","text":"Standard deviation"}]'::jsonb,
  'd',
  '\\textbf{Logic:} Values move further from the mean, increasing the spread. Standard deviation measures spread, so it will change.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_7',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'Class A range (0 to 5), Class B range (1 to 10). What is the positive difference between the ranges?',
  NULL,
  '4',
  '\\textbf{Calculation:} Range A = 5. Range B = 9. Difference = $9 - 5 = 4$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_8',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'Median of arrivals 2012 vs 2013 (9 values each). How much greater was the 2013 median?',
  NULL,
  '1.3',
  '\\textbf{Calculation:} 2012 Median = 46.4. 2013 Median = 47.7. $47.7 - 46.4 = 1.3$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_9',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  '[Dot Plots A and B] Which is true? I. Medians are equal. II. SDs are equal.',
  '[{"id":"a","text":"I only"},{"id":"b","text":"II only"},{"id":"c","text":"I and II"},{"id":"d","text":"Neither"}]'::jsonb,
  'a',
  '\\textbf{Logic:} Both are symmetric at 13 (I is true). Set A has more dots at the extremes than B, so SDs are not equal (II is false).',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_10',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A set of 5 positive integers has a mean of 10 and a median of 8. What is the largest possible value?',
  '[{"id":"a","text":"31"},{"id":"b","text":"32"},{"id":"c","text":"33"},{"id":"d","text":"34"}]'::jsonb,
  'b',
  '\\textbf{Calculation:} Sum = 50. Set: 1, 1, 8, 8, $x$. $1+1+8+8+x=50 → x=32$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_11',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Adding an outlier (10 siblings) to a set where max was 4. Which measure increases most?',
  '[{"id":"a","text":"Mean"},{"id":"b","text":"Median"},{"id":"c","text":"Mode"},{"id":"d","text":"Range"}]'::jsonb,
  'd',
  '\\textbf{Logic:} Range changes from 4 to 10 (+6). Mean changes slightly. Median/Mode likely stay same.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_12',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'Set: 15, 18, 20, 22, 25. Add $k$ to make new mean 22. What is $k$?',
  NULL,
  '32',
  '\\textbf{Calculation:} Old sum = 100. New sum ($22 × 6$) = 132. $k = 132 - 100 = 32$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_13',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Right-skewed distribution. Which is true?',
  '[{"id":"a","text":"mean $<$ median $<$ mode"},{"id":"b","text":"mode $<$ median $<$ mean"},{"id":"c","text":"median $<$ mean $<$ mode"},{"id":"d","text":"mean = median = mode"}]'::jsonb,
  'b',
  '\\textbf{Logic:} Tail on right pulls mean highest. Mode is peak on left. Mode $<$ Median $<$ Mean.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_14',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Set X: 5, 10, 15, 20, 25. Set Y: 105, 110, 115, 120, 125. Compare SD.',
  '[{"id":"a","text":"SD X is 100 less than SD Y"},{"id":"b","text":"SD X is equal to SD Y"},{"id":"c","text":"SD X is greater than SD Y"},{"id":"d","text":"SD X is 5 times less than SD Y"}]'::jsonb,
  'b',
  '\\textbf{Logic:} Adding a constant doesn''t change spread. SD remains identical.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_15',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'Range of 10 numbers is 45. Smallest is 12. Largest?',
  NULL,
  '57',
  '\\textbf{Calculation:} Max - 12 = 45 $→$ Max = 57.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_16',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Median is 20. Every number $\\times 3$ then $+4$. New median?',
  '[{"id":"a","text":"20"},{"id":"b","text":"60"},{"id":"c","text":"64"},{"id":"d","text":"75"}]'::jsonb,
  'c',
  '\\textbf{Calculation:} $(20 × 3) + 4 = 64$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_17',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Which is NOT affected by a single extreme outlier in a large set?',
  '[{"id":"a","text":"Mean"},{"id":"b","text":"Range"},{"id":"c","text":"Standard Deviation"},{"id":"d","text":"Mode"}]'::jsonb,
  'd',
  '\\textbf{Logic:} Mode is the most frequent value; one outlier won''t change frequency rankings in a large set.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_18',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Class A box is wider than Class B. Which is true?',
  '[{"id":"a","text":"Class A has a higher median."},{"id":"b","text":"IQR of Class A is greater."},{"id":"c","text":"Class A has more students."},{"id":"d","text":"Means are equal."}]'::jsonb,
  'b',
  '\\textbf{Logic:} Box width = IQR ($Q3 - Q1$). A wider box means a larger IQR.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_19',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Mode of: 2, 5, 8, 2, 10, 5, 2, 7, 8',
  '[{"id":"a","text":"2"},{"id":"b","text":"5"},{"id":"c","text":"7"},{"id":"d","text":"8"}]'::jsonb,
  'a',
  '\\textbf{Logic:} 2 appears three times; others appear less.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_20',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'If the mean of a set is 50 and the SD is 0, which must be true?',
  '[{"id":"a","text":"There is only one number in the set."},{"id":"b","text":"All numbers in the set are 50."},{"id":"c","text":"The median is 0."},{"id":"d","text":"The range is 50."}]'::jsonb,
  'b',
  '\\textbf{Logic:} SD = 0 means there is zero spread; every value must be identical to the mean.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_21',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A set of 7 numbers has a mean of 12. If 4 is added to the set, new mean?',
  '[{"id":"a","text":"8"},{"id":"b","text":"10"},{"id":"c","text":"11"},{"id":"d","text":"12"}]'::jsonb,
  'c',
  '\\textbf{Calculation:} Old sum = $7 × 12 = 84$. New sum = $84 + 4 = 88$. New $n = 8$. Mean = $88/8 = 11$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_22',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'The average of $x, y,$ and $z$ is 15. The average of $x, y, z,$ and $w$ is 20. Value of $w$?',
  NULL,
  '35',
  '\\textbf{Calculation:} Sum(3) = 45. Sum(4) = 80. $w = 80 - 45 = 35$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_23',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Which measure is most sensitive to an outlier?',
  '[{"id":"a","text":"Median"},{"id":"b","text":"IQR"},{"id":"c","text":"Range"},{"id":"d","text":"Mode"}]'::jsonb,
  'c',
  '\\textbf{Logic:} Range is determined solely by Max and Min. An extreme outlier immediately changes one of these.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_24',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Mean of 100 values is 70. If 10 values are removed (all being 70), new mean?',
  '[{"id":"a","text":"60"},{"id":"b","text":"70"},{"id":"c","text":"77"},{"id":"d","text":"80"}]'::jsonb,
  'b',
  '\\textbf{Logic:} Removing values equal to the mean does not change the mean of the remaining set.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_25',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A data set of 150 values has a mean of 45 and a standard deviation of 8. If every value in the data set is increased by 10%, what will be the new mean and the new standard deviation?',
  '[{"id":"a","text":"Mean: 45, SD: 8"},{"id":"b","text":"Mean: 49.5, SD: 8"},{"id":"c","text":"Mean: 49.5, SD: 8.8"},{"id":"d","text":"Mean: 55, SD: 18"}]'::jsonb,
  'c',
  '\\textbf{Conceptual Explanation:}

When every value in a data set is multiplied by a constant $k$ (in this case, $1.10$), both the mean and the standard deviation are multiplied by that same constant.

\\textbf{Calculation and Logic:}

1. \\textbf{New Mean:} $45 × 1.10 = 49.5$.

2. \\textbf{New SD:} $8 × 1.10 = 8.8$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_26',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'The median of a set of 9 distinct integers is 20. If the largest number is increased by 50, how does the median change?',
  '[{"id":"a","text":"It increases."},{"id":"b","text":"It decreases."},{"id":"c","text":"It stays the same."},{"id":"d","text":"It cannot be determined without the other values."}]'::jsonb,
  'c',
  '\\textbf{Logic:} The median is the middle value. Changing the largest value (which is to the right of the median) does not shift the middle position or the value at that position.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_27',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Which of the following describes a data set where the mean is significantly greater than the median?',
  '[{"id":"a","text":"The data is perfectly symmetric."},{"id":"b","text":"The data is skewed to the left."},{"id":"c","text":"The data is skewed to the right."},{"id":"d","text":"The standard deviation is zero."}]'::jsonb,
  'c',
  '\\textbf{Logic:} In a right-skewed distribution, high-value outliers pull the mean toward the right tail, while the median remains closer to the bulk of the data.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_28',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'What is the range of the following data set? -12, -5, 0, 4, 15, 22',
  NULL,
  '34',
  '\\textbf{Calculation:} Range = Max - Min = $22 - (-12) = 22 + 12 = 34$.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_29',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Two groups of students took a test. Group A ($n=20$) had a mean score of 80. Group B ($n=30$) had a mean score of 90. What is the mean score of all 50 students combined?',
  '[{"id":"a","text":"84"},{"id":"b","text":"85"},{"id":"c","text":"86"},{"id":"d","text":"88"}]'::jsonb,
  'c',
  '\\textbf{Calculation:}

1. Total Score A = $20 × 80 = 1600$.

2. Total Score B = $30 × 90 = 2700$.

3. Total Combined = $1600 + 2700 = 4300$.

4. Combined Mean = $4300 / 50 = 86$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_30',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A data set consists of 10 identical values. Which of the following must be true?',
  '[{"id":"a","text":"The mean is 10."},{"id":"b","text":"The standard deviation is 0."},{"id":"c","text":"The range is 1."},{"id":"d","text":"The median is 0."}]'::jsonb,
  'b',
  '\\textbf{Logic:} If all values are the same, there is no variation, meaning the spread (Range and SD) is zero.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_31',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'The interquartile range (IQR) of a data set is 15. If the first quartile ($Q1$) is 42, what is the value of the third quartile ($Q3$)?',
  NULL,
  '57',
  '\\textbf{Calculation:} $IQR = Q3 - Q1 → 15 = Q3 - 42 → Q3 = 57$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_32',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A set of data has a range of 20. If every value in the set is multiplied by -2, what is the range of the new set?',
  '[{"id":"a","text":"-40"},{"id":"b","text":"20"},{"id":"c","text":"40"},{"id":"d","text":"60"}]'::jsonb,
  'c',
  '\\textbf{Logic:} Range is a measure of distance and must always be positive. If all values are multiplied by $k$, the range is multiplied by $|k|$. $20 × |-2| = 40$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_33',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Which measure is least likely to be affected by an outlier?',
  '[{"id":"a","text":"Mean"},{"id":"b","text":"Median"},{"id":"c","text":"Range"},{"id":"d","text":"Standard Deviation"}]'::jsonb,
  'b',
  '\\textbf{Logic:} The median is resistant to outliers because it only depends on the rank/position of values, not their actual numerical weight.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_34',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'In a box plot, what does the rightmost whisker end represent?',
  '[{"id":"a","text":"Mean"},{"id":"b","text":"Median"},{"id":"c","text":"Maximum"},{"id":"d","text":"Third Quartile"}]'::jsonb,
  'c',
  '\\textbf{Logic:} The whiskers in a standard SAT box plot extend from the minimum to the maximum values.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_35',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A student scored 85, 90, and 88 on three tests. What score does he need on the fourth test to have a mean of 90?',
  '[{"id":"a","text":"90"},{"id":"b","text":"93"},{"id":"c","text":"95"},{"id":"d","text":"97"}]'::jsonb,
  'd',
  '\\textbf{Calculation:} Total needed for 4 tests = $4 × 90 = 360$. Current total = $85 + 90 + 88 = 263$. $360 - 263 = 97$.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_36',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Data Set A: {1, 2, 3, 4, 5}. Data Set B: {1, 1, 3, 5, 5}. Which is true?',
  '[{"id":"a","text":"Mean A $>$ Mean B"},{"id":"b","text":"Median A $>$ Median B"},{"id":"c","text":"SD A $>$ SD B"},{"id":"d","text":"SD B $>$ SD A"}]'::jsonb,
  'd',
  '\\textbf{Logic:} Both have the same mean (3) and median (3). Set B has more values at the extremes (1s and 5s) compared to A, so Set B has a larger standard deviation.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_37',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'A data set has 11 values. If the median is 25, how many values must be less than or equal to 25?',
  NULL,
  '6',
  '\\textbf{Logic:} In an ordered set of 11, the 6th value is the median. Thus, the 1st through 6th values are all $\\le$ the median.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_38',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'If the standard deviation of a set is 5, what is the variance?',
  '[{"id":"a","text":"2.5"},{"id":"b","text":"5"},{"id":"c","text":"10"},{"id":"d","text":"25"}]'::jsonb,
  'd',
  '\\textbf{Logic:} Variance is the square of the standard deviation. $5^2 = 25$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_39',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A frequency table shows 10 students with 0 books, 20 students with 1 book, and $x$ students with 2 books. If the mean is 1, what is $x$?',
  '[{"id":"a","text":"5"},{"id":"b","text":"10"},{"id":"c","text":"15"},{"id":"d","text":"20"}]'::jsonb,
  'b',
  '\\textbf{Calculation:} Mean = Total Books / Total Students.

$1 = ((0\\cdot10) + (1\\cdot20) + (2\\cdot x))/(10 + 20 + x) → 30 + x = 20 + 2x → x = 10$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_40',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'What is the mode of {1, 2, 2, 3, 3, 3, 4}?',
  '[{"id":"a","text":"1"},{"id":"b","text":"2"},{"id":"c","text":"3"},{"id":"d","text":"4"}]'::jsonb,
  'c',
  '\\textbf{Logic:} 3 appears most frequently.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_41',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'A set has a mean of 100. If we remove the largest and smallest values, which measure is guaranteed to change?',
  '[{"id":"a","text":"Mean"},{"id":"b","text":"Median"},{"id":"c","text":"Range"},{"id":"d","text":"Mode"}]'::jsonb,
  'c',
  '\\textbf{Logic:} Removing the extremes will always shrink the distance between the new max and min, thus changing the range.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_42',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'In a left-skewed distribution, which is usually true?',
  '[{"id":"a","text":"mean $<$ median"},{"id":"b","text":"mean $>$ median"},{"id":"c","text":"mean = median"},{"id":"d","text":"SD = 0"}]'::jsonb,
  'a',
  '\\textbf{Logic:} The tail on the left pulls the mean down below the median.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_43',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Find the median of {5, 12, 3, 10, 8}.',
  '[{"id":"a","text":"5"},{"id":"b","text":"8"},{"id":"c","text":"10"},{"id":"d","text":"12"}]'::jsonb,
  'b',
  '\\textbf{Logic:} Ordered: 3, 5, 8, 10, 12. Median = 8.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_44',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'If the sum of 5 numbers is 100, and the median is 20, what is the largest possible value in the set if all numbers are non-negative?',
  '[{"id":"a","text":"20"},{"id":"b","text":"60"},{"id":"c","text":"80"},{"id":"d","text":"100"}]'::jsonb,
  'b',
  '\\textbf{Logic:} To maximize the 5th value, minimize others: 0, 0, 20, 20, $x$. $40 + x = 100 → x = 60$.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_45',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Can the mean be greater than the range?',
  '[{"id":"a","text":"Yes"},{"id":"b","text":"No"}]'::jsonb,
  'a',
  '\\textbf{Logic:} Yes. Consider {100, 100, 101}. Mean $\\approx 100$, Range = 1.',
  'problem-solving',
  'easy',
  0,
  0,
  'sat_lid_034_46',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'spr',
  'math',
  'Median of {1, 2, 3, 4, 5, 100}.',
  NULL,
  '3.5',
  '\\textbf{Calculation:} Even set ($n=6$). Average of 3rd (3) and 4th (4) = 3.5.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_47',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'Standard deviation of {5, 5, 5, 5}?',
  '[{"id":"a","text":"0"},{"id":"b","text":"5"},{"id":"c","text":"25"},{"id":"d","text":"Undefined"}]'::jsonb,
  'a',
  '\\textbf{Logic:} No variation $→$ SD = 0.',
  'problem-solving',
  'hard',
  0,
  0,
  'sat_lid_034_48',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'The median of a set is 10. If we add 5 to every number, the new median is?',
  '[{"id":"a","text":"10"},{"id":"b","text":"15"},{"id":"c","text":"50"},{"id":"d","text":"5"}]'::jsonb,
  'b',
  '\\textbf{Logic:} Addition shifts the entire distribution. $10 + 5 = 15$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_49',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
),
  (
  'mcq',
  'math',
  'If the mean of $x, x+2, x+4$ is 10, what is $x$?',
  '[{"id":"a","text":"6"},{"id":"b","text":"8"},{"id":"c","text":"10"},{"id":"d","text":"12"}]'::jsonb,
  'b',
  '\\textbf{Calculation:} $(3x + 6)/(3) = 10 → x + 2 = 10 → x = 8$.',
  'problem-solving',
  'medium',
  0,
  0,
  'sat_lid_034_50',
  'Distributions, measures of center/spread',
  'Mean, Median, Mode, Range'
)
ON CONFLICT (bank_item_id) DO NOTHING;
