-- Link "Command of Evidence - Quantitative" questions to their images
-- Images uploaded to sat-question-images bucket

UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-01.png' WHERE section = 'rw' AND prompt LIKE 'In many countries, public universities can apply for supplemental government fun%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-02.png' WHERE section = 'rw' AND prompt LIKE 'High levels of public uncertainty about future environmental regulations can com%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-03.png' WHERE section = 'rw' AND prompt LIKE 'It may seem that workers facing tight deadlines would consistently operate at th%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-04.png' WHERE section = 'rw' AND prompt LIKE 'Determining whether chemical compounds found in environmental samples originate %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-05.png' WHERE section = 'rw' AND prompt LIKE 'In many coastal regions, small-scale livelihoods vary by both location and activ%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-06.jpg' WHERE section = 'rw' AND prompt LIKE 'The equilibrium-line altitude (ELA) of a glacier is the elevation at which annua%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-07.png' WHERE section = 'rw' AND prompt LIKE 'Archaeologists studying a prehistoric rock shelter in southern Europe identified%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-08.png' WHERE section = 'rw' AND prompt LIKE 'Physiological variables such as hydration are often homeostatically regulated: w%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-09.png' WHERE section = 'rw' AND prompt LIKE 'Over the past two centuries, both Japan and the United Kingdom experienced subst%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-10.png' WHERE section = 'rw' AND prompt LIKE 'A group of environmental economists analyzed U.S. energy consumption trends to e%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-11.png' WHERE section = 'rw' AND prompt LIKE 'An economic policy student is researching India’s post-1991 energy liberalizatio%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-12.png' WHERE section = 'rw' AND prompt LIKE 'A demography student is studying trends in family formation in Western countries%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-13.png' WHERE section = 'rw' AND prompt LIKE 'Otoliths are calcium carbonate structures in the inner ear of fish that play a c%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-14.png' WHERE section = 'rw' AND prompt LIKE 'Certain plant species form symbiotic relationships with nitrogen-fixing bacteria%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-15.png' WHERE section = 'rw' AND prompt LIKE 'Leaves contain microscopic pores called stomata, which regulate gas exchange by %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-16.png' WHERE section = 'rw' AND prompt LIKE 'Generalist caterpillars feed on a wide range of plant species. Some plants in th%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-17.png' WHERE section = 'rw' AND prompt LIKE 'Prescribed burning has been widely used in temperate grasslands to reduce woody %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-18.png' WHERE section = 'rw' AND prompt LIKE 'The industrial sectors of China, India, and the United States contribute signifi%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-19.png' WHERE section = 'rw' AND prompt LIKE 'In many freshwater ecosystems, the encroachment of invasive or hybridized specie%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-20.png' WHERE section = 'rw' AND prompt LIKE 'While excessive nitrogen runoff can lead to ecological imbalances, nitrogen is a%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-21.png' WHERE section = 'rw' AND prompt LIKE 'To investigate the impact of increased atmospheric CO2 on marine calcification, %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-22.png' WHERE section = 'rw' AND prompt LIKE 'To evaluate whether regular aerobic exercise improves cardiovascular and metabol%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-23.png' WHERE section = 'rw' AND prompt LIKE 'Psychologist Carol Dweck and colleagues have investigated how "growth mindset" i%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-24.png' WHERE section = 'rw' AND prompt LIKE 'The global shift toward renewable energy has accelerated significantly since 199%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-25.png' WHERE section = 'rw' AND prompt LIKE 'The Snow Leopard Trust and partner governments are working to stabilize the popu%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-26.png' WHERE section = 'rw' AND prompt LIKE 'In a nationally representative survey on disease prevention, respondents were as%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-27.png' WHERE section = 'rw' AND prompt LIKE 'A group of behavioral economists investigated consumer preferences for smart-hom%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-28.png' WHERE section = 'rw' AND prompt LIKE 'The search for liquid water on distant worlds is complicated by the "Atmospheric%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-29.png' WHERE section = 'rw' AND prompt LIKE 'Researchers studying mammalian physiology have noted that although mammals diffe%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-30.png' WHERE section = 'rw' AND prompt LIKE 'Astronomers studying exoplanets detected via the transit method define an exopla%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-31.png' WHERE section = 'rw' AND prompt LIKE 'Advancements in agricultural technology significantly altered farming operations%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-32.png' WHERE section = 'rw' AND prompt LIKE 'A meteorology student is researching the average monthly high temperatures in tw%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-33.png' WHERE section = 'rw' AND prompt LIKE 'Archaeologists investigating the FxJj20 Main site in Kenya, dated to approximate%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-34.png' WHERE section = 'rw' AND prompt LIKE 'To maintain energy levels and nutritional balance during the lunar transit, the %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-35.png' WHERE section = 'rw' AND prompt LIKE 'In a comprehensive study of American cinematic history, researchers from the Lib%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-36.png' WHERE section = 'rw' AND prompt LIKE 'Electric grid operators use long-term hydrological forecasts to estimate the max%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-37.png' WHERE section = 'rw' AND prompt LIKE 'A student is investigating the relationship between extreme urban heat and home %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-38.png' WHERE section = 'rw' AND prompt LIKE 'In an ongoing survey of the Milky Way galaxy, astronomers utilize the radial vel%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-39.png' WHERE section = 'rw' AND prompt LIKE 'The Atacama Desert, a plateau in South America, is one of the driest places on E%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-40.png' WHERE section = 'rw' AND prompt LIKE 'Coal had been used as a fuel in the United States since the colonial period, but%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-41.png' WHERE section = 'rw' AND prompt LIKE 'Public health researcher Erica M. Kenney and her colleagues surveyed U.S. adults%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-42.png' WHERE section = 'rw' AND prompt LIKE 'The Earth''s atmosphere changes significantly as altitude increases, with air bec%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-43.png' WHERE section = 'rw' AND prompt LIKE 'An analyst for a global investment firm is evaluating the economic performance o%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-44.png' WHERE section = 'rw' AND prompt LIKE 'A student is explaining how average surface temperatures vary among planets in t%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-45.png' WHERE section = 'rw' AND prompt LIKE 'A student is researching the impact of mechanical and chemical innovations on Am%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-46.png' WHERE section = 'rw' AND prompt LIKE 'Climate scientists study long-term trends in Arctic sea ice extent to understand%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-47.png' WHERE section = 'rw' AND prompt LIKE 'A zoologist is writing a field guide for a conservation program that focuses on %';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-48.png' WHERE section = 'rw' AND prompt LIKE 'Geologists use Interferometric Synthetic Aperture Radar (InSAR) to monitor "unre%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-49.png' WHERE section = 'rw' AND prompt LIKE 'Global biomass represents the total mass of all living individuals within a spec%';
UPDATE sat_questions SET image_url = 'https://ootnqmojcqnzfrtvzzec.supabase.co/storage/v1/object/public/sat-question-images/sat-rw-quant-50.png' WHERE section = 'rw' AND prompt LIKE 'Digital delivery platforms allow customers to order food remotely for a fee. In %';

-- Total UPDATE statements: 50
